/**
 * Regression tests for historicalRegime.js — historical macro-regime
 * classifier that feeds the macro-regime panel and Kelly-lite sizing.
 *
 * Run with: node test/historicalRegime.test.mjs
 *
 * Pure tests — no network. Synthesises Nifty-50 bar series of varying
 * shapes (insufficient, calm uptrend, sharp drop, sustained decline,
 * vol-spike + drop, crash) and pins:
 *   • classifyRegime decision boundaries (each branch in the if/else
 *     ladder including the NEUTRAL default + insufficient-history short
 *     circuit).
 *   • regimeSizeFromLabel mapping (RISK_OFF/NEUTRAL/RISK_ON/unknown).
 *   • shouldSkipScan threshold (only catastrophic >12% drops short
 *     circuit the scan; ordinary RISK_OFF does not).
 *   • Metric rounding contract (2dp for returns/vol-ratio, 3dp for vol
 *     percentages) so downstream UI/serialisation stay stable.
 *   • asOfDate filter — bars after the cutoff are excluded.
 */

import {
  classifyRegime,
  regimeSizeFromLabel,
  shouldSkipScan,
} from "../historicalRegime.js";

let pass = 0;
let fail = 0;
function assert(name, cond, got) {
  if (cond) { pass++; console.log("  ✓", name); }
  else { fail++; console.log("  ✗", name, "→ got", JSON.stringify(got)); }
}

// Helper — build an ascending-by-date series of N bars ending on
// `endDate`, with prices generated by `priceFn(i)` where i=0 is the
// oldest bar and i=N-1 is the latest.
function buildBars(n, endDate, priceFn) {
  const out = [];
  const end = endDate instanceof Date ? endDate : new Date(endDate);
  for (let i = 0; i < n; i++) {
    const d = new Date(end.getTime());
    d.setDate(end.getDate() - (n - 1 - i));
    out.push({ date: d, close: priceFn(i) });
  }
  return out;
}

console.log("historicalRegime.js regression\n");

// ──────────────────── 1. classifyRegime — insufficient history ────────────────────
console.log("classifyRegime insufficient-history short-circuit:");
{
  const bars = buildBars(50, "2026-05-15", () => 20000);
  const r = classifyRegime(bars, "2026-05-15");
  assert("<120 bars → NEUTRAL", r.regime === "NEUTRAL", r);
  assert("<120 bars → reason = insufficient_history", r.metrics.reason === "insufficient_history", r.metrics);

  // Exactly 119 bars also triggers
  const r119 = classifyRegime(buildBars(119, "2026-05-15", () => 20000), "2026-05-15");
  assert("119 bars → still NEUTRAL/insufficient", r119.regime === "NEUTRAL" && r119.metrics.reason === "insufficient_history", r119);

  // Empty/no bars
  const rEmpty = classifyRegime([], "2026-05-15");
  assert("empty bars → NEUTRAL/insufficient", rEmpty.regime === "NEUTRAL" && rEmpty.metrics.reason === "insufficient_history", rEmpty);
}
console.log();

// ──────────────────── 2. classifyRegime — RISK_OFF branches ────────────────────
console.log("classifyRegime RISK_OFF branches:");
{
  // 2a. 20-day return ≤ -8% (catastrophic short-term drop). 200 bars of
  //     20000, then a sharp last-20 collapse to ~18200 (-9% over 20d).
  //     Build by setting bars[0..179] = 20000, bars[180..199] linear
  //     ramp down to 18200. The 20-day reference (bars[N-21] = bars[199]
  //     vs bars[N-1] = bars[219]? no — N=200 so t20 = bars[179] = 20000,
  //     last = bars[199] = 18200 → -9%.
  const crashBars = buildBars(200, "2026-05-15", (i) => {
    if (i < 180) return 20000;
    // Linear from 20000 (i=180) down to 18200 (i=199)
    const t = (i - 180) / 19;
    return 20000 - t * 1800;
  });
  const rCrash = classifyRegime(crashBars, "2026-05-15");
  assert("ret20 ≤ -8% → RISK_OFF", rCrash.regime === "RISK_OFF", rCrash);
  assert("ret20 ≤ -8% → reason = 20d_return_crash", rCrash.metrics.reason === "20d_return_crash", rCrash.metrics);
  assert("ret20 metric ~ -9 (2dp)", Math.abs(rCrash.metrics.ret20 - -9) < 0.5, rCrash.metrics.ret20);

  // 2b. 60-day return ≤ -10% but 20-day return milder (between -8% and
  //     0). 200 bars: bars[0..139] = 22000, bars[140..199] linear ramp
  //     down to 19400 (~-11.8% over 60d). 20-day ref is bars[179],
  //     which is ~19867; last = 19400; ret20 ≈ -2.3%.
  const declineBars = buildBars(200, "2026-05-15", (i) => {
    if (i < 140) return 22000;
    const t = (i - 140) / 59;
    return 22000 - t * 2600;
  });
  const rDecline = classifyRegime(declineBars, "2026-05-15");
  assert("ret60 ≤ -10% (with mild ret20) → RISK_OFF", rDecline.regime === "RISK_OFF", rDecline);
  assert("ret60 ≤ -10% → reason = 60d_sustained_decline", rDecline.metrics.reason === "60d_sustained_decline", rDecline.metrics);
  assert("ret20 in declineBars is between -8 and 0 (so 20d branch did NOT fire)", rDecline.metrics.ret20 > -8 && rDecline.metrics.ret20 < 0, rDecline.metrics.ret20);

  // 2c. ret20 in (-8, -5] + vol spike > 1.5. Need ret20 strictly > -8
  //     (else the 20d_return_crash branch fires FIRST), but ≤ -5.
  //     Construct: bars[0..179] = 20000 (low vol baseline → vol120
  //     dominated by these), last 20 bars zig-zag downward and end at
  //     ~18800 (ret20 ≈ -6.0%). The final price equals the drift target;
  //     the zig adds ±200 around it (last bar at i=199 gets +200 zig so
  //     close = drift_target + 200 = 18800+200 = 19000? — but the
  //     CHECK is bars[N-1] vs bars[N-21]=bars[179]=20000). Pre-compute:
  //     i=199 (odd) → drift = -1200, zig = -200 → 18600. ret20 = -7.0%.
  const volSpikeBars = buildBars(200, "2026-05-15", (i) => {
    if (i < 180) return 20000; // calm baseline → vol120 dominated by this
    const stepIdx = i - 180; // 0..19
    const drift = -1200 * (stepIdx / 19); // ends at -1200 when stepIdx=19
    const zig = stepIdx % 2 === 0 ? +200 : -200;
    return 20000 + drift + zig;
  });
  const rVolSpike = classifyRegime(volSpikeBars, "2026-05-15");
  assert("ret20 ≤ -5 + volRatio > 1.5 → RISK_OFF", rVolSpike.regime === "RISK_OFF", rVolSpike);
  assert("vol-spike + drop → reason = 20d_drop_plus_vol_spike", rVolSpike.metrics.reason === "20d_drop_plus_vol_spike", rVolSpike.metrics);
  assert("volRatio metric > 1.5 (vol spike confirmed)", rVolSpike.metrics.volRatio > 1.5, rVolSpike.metrics.volRatio);
}
console.log();

// ──────────────────── 3. classifyRegime — RISK_ON branch ────────────────────
console.log("classifyRegime RISK_ON sustained-uptrend-calm:");
{
  // 200 bars: smooth geometric uptrend so ret60 and ret20 both clear
  // their thresholds and per-day log returns are tiny + uniform (low vol).
  // Daily multiplier of 1.0018 → ret20 ≈ +3.66%, ret60 ≈ +11.39%.
  // Log returns are theoretically constant (uniform geometric), so vol20
  // ≈ vol120 ≈ 0; volRatio is dominated by float-noise but consistently
  // resolves under 1.2 at this rate (empirically ≈ 0.67) → RISK_ON
  // criteria all clear. Rate is chosen to give margin on ret20 ≥ 3 so
  // the test isn't brittle to numerical drift.
  const upBars = buildBars(200, "2026-05-15", (i) => 18000 * Math.pow(1.0018, i));
  const rUp = classifyRegime(upBars, "2026-05-15");
  assert("sustained calm uptrend → RISK_ON", rUp.regime === "RISK_ON", rUp);
  assert("RISK_ON reason = sustained_uptrend_calm", rUp.metrics.reason === "sustained_uptrend_calm", rUp.metrics);
  assert("ret20 ≥ 3 (uptrend confirmed)", rUp.metrics.ret20 >= 3, rUp.metrics.ret20);
  assert("ret60 ≥ 5 (sustained)", rUp.metrics.ret60 >= 5, rUp.metrics.ret60);
  assert("volRatio < 1.2 (calm)", rUp.metrics.volRatio < 1.2, rUp.metrics.volRatio);
}
console.log();

// ──────────────────── 4. classifyRegime — NEUTRAL default ────────────────────
console.log("classifyRegime NEUTRAL default:");
{
  // Flat-ish series — neither RISK_OFF triggers nor RISK_ON criteria met.
  const flatBars = buildBars(200, "2026-05-15", () => 20000);
  const rFlat = classifyRegime(flatBars, "2026-05-15");
  assert("flat market → NEUTRAL", rFlat.regime === "NEUTRAL", rFlat);
  assert("NEUTRAL default → reason = default", rFlat.metrics.reason === "default", rFlat.metrics);
  assert("flat market ret20 = 0", rFlat.metrics.ret20 === 0, rFlat.metrics.ret20);
  assert("flat market ret60 = 0", rFlat.metrics.ret60 === 0, rFlat.metrics.ret60);

  // Mild uptrend that misses ret20 threshold (ret20 ~ +2%) → still NEUTRAL.
  const mildBars = buildBars(200, "2026-05-15", (i) => 18000 * Math.pow(1.0005, i));
  const rMild = classifyRegime(mildBars, "2026-05-15");
  assert("mild uptrend below threshold → NEUTRAL", rMild.regime === "NEUTRAL", rMild);
}
console.log();

// ──────────────────── 5. classifyRegime — metric rounding contract ────────────────────
console.log("classifyRegime metric rounding (UI/serialisation stability):");
{
  const bars = buildBars(200, "2026-05-15", (i) => 18000 * Math.pow(1.0015, i));
  const r = classifyRegime(bars, "2026-05-15");
  // 2dp rounding: a 2-decimal-place number, when *100, is integer.
  // Use a tolerance to dodge float artefacts.
  const is2dp = (x) => Math.abs(Math.round(x * 100) - x * 100) < 1e-6;
  const is3dp = (x) => Math.abs(Math.round(x * 1000) - x * 1000) < 1e-6;
  assert("ret20 rounded to 2dp", is2dp(r.metrics.ret20), r.metrics.ret20);
  assert("ret60 rounded to 2dp", is2dp(r.metrics.ret60), r.metrics.ret60);
  assert("vol20 rounded to 3dp", is3dp(r.metrics.vol20), r.metrics.vol20);
  assert("vol120 rounded to 3dp", is3dp(r.metrics.vol120), r.metrics.vol120);
  assert("volRatio rounded to 2dp", is2dp(r.metrics.volRatio), r.metrics.volRatio);
}
console.log();

// ──────────────────── 6. classifyRegime — asOfDate filter ────────────────────
console.log("classifyRegime asOfDate filter excludes future bars:");
{
  // Build 200 bars ending 2026-05-15 (flat at 20000) + 30 future bars
  // climbing aggressively (which, if leaked into the scan, would flip
  // to RISK_ON). Pass asOf=2026-05-15 → future bars MUST be excluded
  // and result MUST stay NEUTRAL.
  const past = buildBars(200, "2026-05-15", () => 20000);
  const future = [];
  for (let i = 1; i <= 30; i++) {
    const d = new Date("2026-05-15");
    d.setDate(d.getDate() + i);
    future.push({ date: d, close: 30000 + i * 200 }); // huge ramp
  }
  const combined = [...past, ...future];

  const rFiltered = classifyRegime(combined, "2026-05-15");
  assert("asOfDate excludes future → still NEUTRAL", rFiltered.regime === "NEUTRAL", rFiltered);
  assert("asOfDate excludes future → ret20 still 0 (no leak)", rFiltered.metrics.ret20 === 0, rFiltered.metrics.ret20);

  // String asOfDate accepted (constructor handles ISO string)
  const rString = classifyRegime(combined, "2026-05-15");
  assert("string asOfDate parses to Date and filters identically", rString.regime === rFiltered.regime, { string: rString.regime, date: rFiltered.regime });
}
console.log();

// ──────────────────── 7. regimeSizeFromLabel ────────────────────
console.log("regimeSizeFromLabel mapping:");
{
  assert("RISK_OFF → 0.50", regimeSizeFromLabel("RISK_OFF") === 0.50);
  assert("NEUTRAL → 1.00", regimeSizeFromLabel("NEUTRAL") === 1.00);
  assert("RISK_ON → 1.10", regimeSizeFromLabel("RISK_ON") === 1.10);
  // Unknown / falsy labels default to NEUTRAL multiplier
  assert("unknown label → 1.00 (default)", regimeSizeFromLabel("MYSTERY") === 1.00);
  assert("null label → 1.00 (default)", regimeSizeFromLabel(null) === 1.00);
  assert("undefined label → 1.00 (default)", regimeSizeFromLabel(undefined) === 1.00);
  assert("empty string → 1.00 (default)", regimeSizeFromLabel("") === 1.00);
}
console.log();

// ──────────────────── 8. shouldSkipScan threshold ────────────────────
console.log("shouldSkipScan threshold (only catastrophic >12% drops):");
{
  // Non-RISK_OFF labels never skip, regardless of metrics
  assert("NEUTRAL never skips (even with ret20 = -50)", shouldSkipScan("NEUTRAL", { ret20: -50 }) === false);
  assert("RISK_ON never skips (even with ret20 = -50)", shouldSkipScan("RISK_ON", { ret20: -50 }) === false);
  assert("unknown label never skips", shouldSkipScan("MYSTERY", { ret20: -50 }) === false);

  // RISK_OFF + mild drop → don't skip (reversal picks may still work)
  assert("RISK_OFF + ret20 = -8 (mild) → do NOT skip", shouldSkipScan("RISK_OFF", { ret20: -8 }) === false);
  assert("RISK_OFF + ret20 = -11.99 (just under threshold) → do NOT skip", shouldSkipScan("RISK_OFF", { ret20: -11.99 }) === false);

  // RISK_OFF + catastrophic drop → skip
  assert("RISK_OFF + ret20 = -12 (boundary) → SKIP", shouldSkipScan("RISK_OFF", { ret20: -12 }) === true);
  assert("RISK_OFF + ret20 = -20 (crash) → SKIP", shouldSkipScan("RISK_OFF", { ret20: -20 }) === true);

  // Defensive: missing metrics object → don't skip
  assert("RISK_OFF + null metrics → do NOT skip (defensive default)", shouldSkipScan("RISK_OFF", null) === false);
  assert("RISK_OFF + undefined metrics → do NOT skip", shouldSkipScan("RISK_OFF", undefined) === false);
  assert("RISK_OFF + empty metrics → do NOT skip", shouldSkipScan("RISK_OFF", {}) === false);
}
console.log();

console.log(`\nResult: ${pass} passed, ${fail} failed`);
process.exit(fail === 0 ? 0 : 1);
