/**
 * Regression test for scripts/sws-sanity-gate.mjs picks_recent threshold.
 *
 * Background: the gate's picks_recent check used to fire BLOCK once
 * picks-latest.json was > 6h old. The old two-fire cadence meant the
 * first slightly-late refresh flipped the
 * verdict to FAIL — and because the verdict file itself only gets
 * regenerated by sws-nightly.sh (which the gate is gating!), it then
 * sat stuck at FAIL for days, silently disabling the production
 * safety net. The threshold was loosened from 6h → 14h (12h cadence
 * + 2h slack). This test pins both the constant and the boundary
 * behaviour so a future "tighten it back" change has to come with
 * intent.
 *
 * Run with: node test/swsSanityGate.test.mjs
 */

import { spawnSync } from "child_process";
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, rmSync, existsSync } from "fs";
import { tmpdir } from "os";
import { dirname, join, resolve } from "path";
import { fileURLToPath } from "url";

import {
  PICKS_MAX_AGE_HOURS,
  PICKS_LR_CONSISTENCY_SLACK_SEC,
  GROWW_PE_WARN_COVERAGE_PCT,
  GROWW_PE_BLOCK_COVERAGE_PCT,
  GROWW_PE_STALE_GRACE_DAYS,
  GROWW_STOCK_WARN_COVERAGE_PCT,
  GROWW_STOCK_BLOCK_COVERAGE_PCT,
  GROWW_STOCK_STALE_GRACE_DAYS,
} from "../scripts/sws-sanity-gate.mjs";

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, "..");
const GATE_SCRIPT = resolve(REPO_ROOT, "scripts/sws-sanity-gate.mjs");

let pass = 0;
let fail = 0;
function assert(name, cond, got) {
  if (cond) {
    pass++;
    console.log("  ✓", name);
  } else {
    fail++;
    console.log("  ✗", name, "→ got", JSON.stringify(got));
  }
}

console.log("\nsws-sanity-gate.mjs picks_recent threshold regression\n");

// ---------------------------------------------------------------- assert 1
// Constant pinned at 20h. The original 6h flipped to FAIL the first time
// a refresh slipped slightly and self-perpetuated; 14h (PR #294) was still
// too tight — evening runs blocked at 16.7h on 2026-05-18 (forcing PR #314
// manual sync). 20h is now intentionally below the once-daily cadence: after
// a 00:30 run, the gate should only pass if that run produced fresh picks,
// not if it is still seeing yesterday's committed file.
assert(
  "PICKS_MAX_AGE_HOURS exported and equal to 20",
  PICKS_MAX_AGE_HOURS === 20,
  PICKS_MAX_AGE_HOURS,
);

// ---------------------------------------------------------------- helpers
// Build a minimal SWS_SANITY_ROOT fixture so the gate runs end-to-end.
// We only care about the picks_recent / picks_matches_last_refresh findings
// here, so other layers can be in whatever shape — they'll fail BLOCK and
// FAIL the verdict, but our assertions target specific findings regardless.
function buildFixture(ageHours, opts = {}) {
  const root = mkdtempSync(join(tmpdir(), "sws-sanity-test-"));
  mkdirSync(join(root, "deep"), { recursive: true });

  const nowMs = Date.now();
  const scannedAtMs = nowMs - ageHours * 3600 * 1000;
  const scannedAt = new Date(scannedAtMs).toISOString();
  writeFileSync(
    join(root, "picks-latest.json"),
    JSON.stringify({
      scanned_at: scannedAt,
      sections: {
        top_ranked_30_v3: [],
        best_to_buy_now: [],
        upcoming_earnings: [],
      },
    }),
  );

  // Minimal last-refresh.json — present-but-empty is enough to let
  // layer1() reach the picks_recent block. Other L1 checks will fail
  // BLOCK on missing fields; we don't care.
  //
  // started_at / finished_at default to bracketing scanned_at exactly so
  // the picks_matches_last_refresh check is "consistent" by default. Opts
  // can override either timestamp to test mismatch scenarios.
  //
  // opts.includeStartedAt = false → simulates a pre-upgrade summary file.
  // opts.startedAtOffsetSec / opts.finishedAtOffsetSec → shift the window
  //   for boundary testing (offset relative to scannedAt).
  const includeStarted = opts.includeStartedAt !== false;
  const startedAtMs = scannedAtMs + (opts.startedAtOffsetSec ?? -300) * 1000; // default: 5min before scanned
  const finishedAtMs = scannedAtMs + (opts.finishedAtOffsetSec ?? 300) * 1000; // default: 5min after scanned
  const lr = {
    finished_at: new Date(finishedAtMs).toISOString(),
    scored_count: 0,
    news_populated_count: 0,
    rewards_populated_count: 0,
    risks_populated_count: 0,
    shards_failed: 0,
  };
  if (includeStarted) lr.started_at = new Date(startedAtMs).toISOString();
  writeFileSync(join(root, "last-refresh.json"), JSON.stringify(lr));

  const growwOpt = opts.growwPeCache === undefined
    ? { coveragePct: 90, ageDays: 1, targetCount: 1000 }
    : opts.growwPeCache;
  if (growwOpt) {
    const targetCount = growwOpt.targetCount ?? 1000;
    const usableCount = growwOpt.usableCount ?? Math.round(targetCount * (growwOpt.coveragePct ?? 90) / 100);
    const fetchedAtMs = nowMs - (growwOpt.ageDays ?? 1) * 86400000;
    writeFileSync(join(root, "groww-pe-latest.json"), JSON.stringify({
      schema_version: "groww-pe-v1",
      source: "groww_refinitiv",
      fetched_at: new Date(fetchedAtMs).toISOString(),
      expires_at: new Date(fetchedAtMs + 7 * 86400000).toISOString(),
      coverage: {
        target_count: targetCount,
        usable_count: usableCount,
        coverage_pct: growwOpt.coveragePct ?? (usableCount / targetCount) * 100,
      },
      by_ticker: { JSLL: { peRatio: 39.58, industryPe: 45.3 } },
    }));
  }

  const growwStockOpt = opts.growwStockCache === undefined
    ? { coveragePct: 90, ageDays: 1, targetCount: 1000, peCoveragePct: 55 }
    : opts.growwStockCache;
  if (growwStockOpt) {
    const targetCount = growwStockOpt.targetCount ?? 1000;
    const usableCount = growwStockOpt.usableCount ?? Math.round(targetCount * (growwStockOpt.coveragePct ?? 90) / 100);
    const peUsableCount = Math.round(targetCount * (growwStockOpt.peCoveragePct ?? 55) / 100);
    const fetchedAtMs = nowMs - (growwStockOpt.ageDays ?? 1) * 86400000;
    writeFileSync(join(root, "groww-stock-latest.json"), JSON.stringify({
      schema_version: "groww-stock-v1",
      source: "groww_refinitiv",
      fetched_at: new Date(fetchedAtMs).toISOString(),
      expires_at: new Date(fetchedAtMs + 86400000).toISOString(),
      coverage: {
        target_count: targetCount,
        usable_count: usableCount,
        coverage_pct: growwStockOpt.coveragePct ?? (usableCount / targetCount) * 100,
        pe_usable_count: peUsableCount,
        pe_coverage_pct: growwStockOpt.peCoveragePct ?? (peUsableCount / targetCount) * 100,
      },
      by_ticker: { JSLL: { currentPriceInr: 100, marketCapInr: 1000, peRatio: 39.58, industryPe: 45.3 } },
    }));
  }

  writeFileSync(join(root, "universe.json"), "[]");
  writeFileSync(join(root, "sws-scored-universe.json"), "[]");
  const nseCalOpt = opts.nseCalendar === undefined
    ? { eventCount: 80, rawEventCount: 200, windowDays: 60 }
    : opts.nseCalendar;
  if (nseCalOpt) {
    const eventCount = nseCalOpt.eventCount ?? 0;
    const bySymbol = {};
    for (let i = 0; i < eventCount; i++) {
      bySymbol[`SYM${i}`] = { date: "2026-06-15", purpose: "Financial Results", description: null };
    }
    writeFileSync(join(root, "nse-event-calendar.json"), JSON.stringify({
      fetched_at: new Date(nowMs).toISOString(),
      source: "https://www.nseindia.com/api/event-calendar",
      source_window: { from_date: "2026-06-01", to_date: "2026-07-31", window_days: nseCalOpt.windowDays ?? 60 },
      raw_event_count: nseCalOpt.rawEventCount ?? eventCount,
      event_count: eventCount,
      by_symbol: bySymbol,
    }));
  }
  return root;
}

function runGateAndGetFindings(ageHours, opts = {}) {
  const root = buildFixture(ageHours, opts);
  try {
    const result = spawnSync("node", [GATE_SCRIPT], {
      env: { ...process.env, SWS_SANITY_ROOT: root, SWS_RUN_ID: "" },
      encoding: "utf-8",
    });
    if (result.error) throw result.error;
    const reportPath = join(root, "_sanity", "_latest.json");
    const report = JSON.parse(readFileSync(reportPath, "utf-8"));
    const l1 = report.layers.L1_run_integrity?.checks || [];
    const l2 = report.layers.L2_coverage_audit?.checks || [];
    return {
      picksRecent: l1.find((c) => c.name === "picks_recent"),
      consistency: l1.find((c) => c.name === "picks_matches_last_refresh"),
      upcomingEarnings: l1.find((c) => c.name === "section_upcoming_earnings"),
      growwWarn: l2.find((c) => c.name === "groww_pe_coverage_warn"),
      growwBlock: l2.find((c) => c.name === "groww_pe_coverage_block_floor"),
      growwGrace: l2.find((c) => c.name === "groww_pe_cache_grace_age"),
      growwStockWarn: l2.find((c) => c.name === "groww_stock_coverage_warn"),
      growwStockBlock: l2.find((c) => c.name === "groww_stock_coverage_block_floor"),
      growwStockGrace: l2.find((c) => c.name === "groww_stock_cache_grace_age"),
    };
  } finally {
    try { rmSync(root, { recursive: true, force: true }); } catch {}
  }
}

function runGateInlineMode(ageHours, opts = {}) {
  const root = buildFixture(ageHours, opts);
  try {
    const result = spawnSync("node", [GATE_SCRIPT, "--inline"], {
      env: { ...process.env, SWS_SANITY_ROOT: root, SWS_RUN_ID: "" },
      encoding: "utf-8",
    });
    // Evaluate file presence BEFORE the finally block deletes the fixture root.
    return {
      exitCode: result.status,
      stdout: result.stdout || "",
      stderr: result.stderr || "",
      flagExists: existsSync(join(root, "_sanity", "_inline_pass.flag")),
      latestReportExists: existsSync(join(root, "_sanity", "_latest.json")),
    };
  } finally {
    try { rmSync(root, { recursive: true, force: true }); } catch {}
  }
}

// Backwards-compat shim for the existing picks_recent assertions.
function runGateAndGetPicksFinding(ageHours) {
  return runGateAndGetFindings(ageHours).picksRecent;
}

// ---------------------------------------------------------------- assert 2
// 19.99h < 20h threshold → picks_recent check passes.
const justUnder = runGateAndGetPicksFinding(19.99);
assert(
  "picks_recent age=19.99 → ok=true (under 20h threshold)",
  justUnder && justUnder.ok === true,
  justUnder,
);
assert(
  "picks_recent age=19.99 → detail.threshold=20",
  justUnder && justUnder.detail?.threshold === 20,
  justUnder?.detail,
);

// ---------------------------------------------------------------- assert 3
// 20.01h >= 20h threshold → picks_recent check BLOCKs.
const justOver = runGateAndGetPicksFinding(20.01);
assert(
  "picks_recent age=20.01 → ok=false (over 20h threshold)",
  justOver && justOver.ok === false,
  justOver,
);
assert(
  "picks_recent age=20.01 → severity=BLOCK",
  justOver && justOver.severity === "BLOCK",
  justOver,
);

// ============================================================================
// picks_matches_last_refresh — internal consistency check
// ============================================================================
//
// Background: on 2026-05-18 22:37 IST the sanity gate fired picks_recent
// (age=16.73h vs 14h threshold), but the underlying cause was that
// picks-latest.json had been silently reverted to morning's git-committed
// version somewhere between scoring (20:51 IST) and the sanity gate
// (22:37 IST). The threshold bump to 20h (PR #315) hides that class of
// failure rather than catching it. picks_matches_last_refresh diffs
// picks.scanned_at against lr.started_at/finished_at to catch
// "picks from a different run than last-refresh" with a precise diagnosis.

console.log("\npicks_matches_last_refresh consistency check\n");

// ---------------------------------------------------------------- assert 4
// Slack constant pinned at 60s. Same-machine writes have no NTP skew;
// wider slack risks missing real cross-run mix-ups.
assert(
  "PICKS_LR_CONSISTENCY_SLACK_SEC exported and equal to 60",
  PICKS_LR_CONSISTENCY_SLACK_SEC === 60,
  PICKS_LR_CONSISTENCY_SLACK_SEC,
);

// ---------------------------------------------------------------- assert 5
// Happy path: picks.scanned_at falls cleanly inside [started_at, finished_at].
// Default fixture has scanned bracketed by [-5min, +5min] — well inside slack.
const happy = runGateAndGetFindings(1.0).consistency;
assert(
  "happy path: scanned_at inside run window → ok=true",
  happy && happy.ok === true,
  happy,
);
assert(
  "happy path: severity BLOCK (active check)",
  happy && happy.severity === "BLOCK",
  happy,
);

// ---------------------------------------------------------------- assert 6
// 2026-05-18 reproduction: picks.scanned_at is from a PRIOR run, hours
// before the current run started. This is exactly the bug we shipped.
//
// Fixture: ageHours=16.73 (matches the failure's age_hours exactly).
// started_at = scanned + 14h (= today's evening run window).
// finished_at = scanned + 18h (= today's evening run finished 4h later).
// → picks.scanned_at is 14h BEFORE start, well outside slack → BLOCK.
const reverted = runGateAndGetFindings(16.73, {
  startedAtOffsetSec: 14 * 3600,
  finishedAtOffsetSec: 18 * 3600,
}).consistency;
assert(
  "2026-05-18 reproduction: scanned 14h before run start → ok=false",
  reverted && reverted.ok === false,
  reverted,
);
assert(
  "2026-05-18 reproduction: severity BLOCK",
  reverted && reverted.severity === "BLOCK",
  reverted,
);
assert(
  "2026-05-18 reproduction: drift_outside_run_seconds reflects 14h gap",
  reverted &&
    reverted.detail?.drift_outside_run_seconds >= 14 * 3600 - 60 &&
    reverted.detail?.drift_outside_run_seconds <= 14 * 3600 + 60,
  reverted?.detail?.drift_outside_run_seconds,
);

// ---------------------------------------------------------------- assert 7
// Boundary: scanned exactly 60s before started → still consistent (slack).
const boundaryInside = runGateAndGetFindings(0.001, {
  startedAtOffsetSec: 59, // scanned is 59s before started → inside slack
  finishedAtOffsetSec: 600,
}).consistency;
assert(
  "boundary: scanned 59s before started_at → consistent",
  boundaryInside && boundaryInside.ok === true,
  boundaryInside,
);

// ---------------------------------------------------------------- assert 8
// Boundary: scanned 61s before started → outside slack → BLOCK.
const boundaryOutside = runGateAndGetFindings(0.001, {
  startedAtOffsetSec: 61, // scanned is 61s before started → outside slack
  finishedAtOffsetSec: 600,
}).consistency;
assert(
  "boundary: scanned 61s before started_at → inconsistent",
  boundaryOutside && boundaryOutside.ok === false,
  boundaryOutside,
);

// ---------------------------------------------------------------- assert 9
// First-run / pre-upgrade: lr.started_at missing. Should NOT BLOCK — degrade
// to WARN so existing pre-Layer-C summaries don't break the gate on upgrade.
const preUpgrade = runGateAndGetFindings(1.0, { includeStartedAt: false }).consistency;
assert(
  "pre-upgrade lr without started_at: check present as WARN, not BLOCK",
  preUpgrade && preUpgrade.severity === "WARN" && preUpgrade.ok === false,
  preUpgrade,
);
assert(
  "pre-upgrade detail explains why check is inactive",
  preUpgrade && /started_at missing/i.test(preUpgrade.detail?.reason || ""),
  preUpgrade?.detail,
);

// ---------------------------------------------------------------- assert 10
// Shard-retry simulation: picks.scanned_at is set during scoring (mid-run),
// then retry rewrites it later. Final scanned_at is INSIDE the run window —
// must pass even though scanned_at was overwritten during the run.
// (Simulated by scanned at the finished_at boundary.)
const retryFinal = runGateAndGetFindings(0.001, {
  startedAtOffsetSec: -3600,  // run started 1h before final scanned_at write
  finishedAtOffsetSec: 60,    // run finished 60s after final scanned_at
}).consistency;
assert(
  "shard-retry: scanned_at near finished_at → consistent",
  retryFinal && retryFinal.ok === true,
  retryFinal,
);

// ============================================================================
// Groww/Refinitiv P/E cache coverage checks
// ============================================================================

console.log("\nGroww/Refinitiv P/E cache gate\n");

assert(
  "Groww coverage thresholds exported",
  GROWW_PE_WARN_COVERAGE_PCT === 85 &&
    GROWW_PE_BLOCK_COVERAGE_PCT === 70 &&
    GROWW_PE_STALE_GRACE_DAYS === 21 &&
    GROWW_STOCK_WARN_COVERAGE_PCT === 85 &&
    GROWW_STOCK_BLOCK_COVERAGE_PCT === 70 &&
    GROWW_STOCK_STALE_GRACE_DAYS === 3,
  {
    GROWW_PE_WARN_COVERAGE_PCT,
    GROWW_PE_BLOCK_COVERAGE_PCT,
    GROWW_PE_STALE_GRACE_DAYS,
    GROWW_STOCK_WARN_COVERAGE_PCT,
    GROWW_STOCK_BLOCK_COVERAGE_PCT,
    GROWW_STOCK_STALE_GRACE_DAYS,
  },
);

const growwStockBelowWarn = runGateAndGetFindings(1.0, {
  growwStockCache: { coveragePct: 84.9, ageDays: 1 },
});
assert(
  "Groww stock 84.9% fresh cache: WARN fails below 85%",
  growwStockBelowWarn.growwStockWarn && growwStockBelowWarn.growwStockWarn.ok === false && growwStockBelowWarn.growwStockWarn.severity === "WARN",
  growwStockBelowWarn.growwStockWarn,
);
assert(
  "Groww stock 84.9% fresh cache: BLOCK floor passes",
  growwStockBelowWarn.growwStockBlock && growwStockBelowWarn.growwStockBlock.ok === true,
  growwStockBelowWarn.growwStockBlock,
);

const growwStockAncient = runGateAndGetFindings(1.0, {
  growwStockCache: { coveragePct: 69.9, ageDays: 3.1 },
});
assert(
  "Groww stock 69.9% ancient cache: BLOCK fails after 3d stale grace",
  growwStockAncient.growwStockBlock && growwStockAncient.growwStockBlock.ok === false && growwStockAncient.growwStockBlock.severity === "BLOCK",
  growwStockAncient.growwStockBlock,
);

const growwBelowWarn = runGateAndGetFindings(1.0, {
  growwPeCache: { coveragePct: 84.9, ageDays: 1 },
});
assert(
  "Groww 84.9% fresh cache: WARN fails below 85%",
  growwBelowWarn.growwWarn && growwBelowWarn.growwWarn.ok === false && growwBelowWarn.growwWarn.severity === "WARN",
  growwBelowWarn.growwWarn,
);
assert(
  "Groww 84.9% fresh cache: BLOCK floor passes",
  growwBelowWarn.growwBlock && growwBelowWarn.growwBlock.ok === true,
  growwBelowWarn.growwBlock,
);

const growwBelowBlockButFresh = runGateAndGetFindings(1.0, {
  growwPeCache: { coveragePct: 69.9, ageDays: 1 },
});
assert(
  "Groww 69.9% fresh cache: BLOCK passes because stale fallback is usable",
  growwBelowBlockButFresh.growwBlock && growwBelowBlockButFresh.growwBlock.ok === true,
  growwBelowBlockButFresh.growwBlock,
);

const growwBelowBlockAncient = runGateAndGetFindings(1.0, {
  growwPeCache: { coveragePct: 69.9, ageDays: 21.1 },
});
assert(
  "Groww 69.9% ancient cache: BLOCK fails after 21d stale grace",
  growwBelowBlockAncient.growwBlock && growwBelowBlockAncient.growwBlock.ok === false && growwBelowBlockAncient.growwBlock.severity === "BLOCK",
  growwBelowBlockAncient.growwBlock,
);

const growwMissing = runGateAndGetFindings(1.0, { growwPeCache: null });
assert(
  "Groww missing cache: BLOCK floor fails because no stale fallback exists",
  growwMissing.growwBlock && growwMissing.growwBlock.ok === false,
  growwMissing.growwBlock,
);

// ============================================================================
// Upcoming earnings gate
// ============================================================================

console.log("\nupcoming earnings calendar-aware gate\n");

const sparseCalendar = runGateAndGetFindings(1.0, {
  nseCalendar: { eventCount: 6, rawEventCount: 22, windowDays: 60 },
}).upcomingEarnings;
assert(
  "sparse but nonempty NSE calendar downgrades upcoming_earnings below 25 to WARN",
  sparseCalendar && sparseCalendar.ok === false && sparseCalendar.severity === "WARN",
  sparseCalendar,
);
assert(
  "sparse calendar finding includes NSE event count",
  sparseCalendar && sparseCalendar.detail?.nse_calendar_event_count === 6,
  sparseCalendar?.detail,
);

const missingCalendar = runGateAndGetFindings(1.0, { nseCalendar: null }).upcomingEarnings;
assert(
  "missing NSE calendar keeps upcoming_earnings below 25 as BLOCK",
  missingCalendar && missingCalendar.ok === false && missingCalendar.severity === "BLOCK",
  missingCalendar,
);

// ============================================================================
// --inline mode tests
// ============================================================================
//
// Inline mode runs the gate INSIDE sws-refresh-api.sh between stamp and PDF
// (pre-summary), so lr is from the PREVIOUS run and the consistency check
// must skip itself rather than false-positive. Side-effects also differ:
//   - DOES write data/sws/_sanity/_inline_pass.flag on pass
//   - does NOT write the timestamped <runId>.json or clobber _latest.json
// Outer-gate vs inline-gate verdict divergence is the tripwire that
// sws-nightly.sh uses to diagnose mid-run revert.

console.log("\n--inline mode\n");

// ---------------------------------------------------------------- assert 11
// Inline mode with clean fixture should exit 0 (no BLOCKs from our
// targeted checks; other L1 checks may fail BLOCK on the empty fixture,
// but the test fixture deliberately ships zeros — so exit code depends
// on those. We assert side-effects only: no _latest.json clobber.
const inlineClean = runGateInlineMode(1.0);
assert(
  "inline mode: does NOT write _sanity/_latest.json",
  inlineClean.latestReportExists === false,
  inlineClean,
);

// ---------------------------------------------------------------- assert 12
// The inline gate must NOT fire picks_matches_last_refresh even when
// scanned_at is far from started_at — because in inline mode lr is from
// the PREVIOUS run. We can't read the inline report (it's not written),
// so probe via stdout: the BLOCKING violations list should NOT name
// picks_matches_last_refresh.
const inlineFarMismatch = runGateInlineMode(16.73, {
  startedAtOffsetSec: 14 * 3600,
  finishedAtOffsetSec: 18 * 3600,
});
assert(
  "inline mode: picks_matches_last_refresh SUPPRESSED (no BLOCK output for it)",
  !/picks_matches_last_refresh/.test(inlineFarMismatch.stdout),
  inlineFarMismatch.stdout.split("\n").filter((l) => l.includes("picks_matches")).join("\n") || "(no mention)",
);

// ---------------------------------------------------------------- assert 13
// When the inline gate "passes" (no BLOCKs), it drops _inline_pass.flag
// for the outer nightly to read. The clean fixture doesn't pass — other
// L1 BLOCKs (e.g. shards_failed_zero requires fields the empty fixture
// lacks) fail. So we INVERT the test: confirm that when the gate FAILS
// (e.g. our reproduction fixture), the flag is NOT dropped.
const inlineFailure = runGateInlineMode(16.73, {
  startedAtOffsetSec: 14 * 3600,
  finishedAtOffsetSec: 18 * 3600,
});
assert(
  "inline mode: flag NOT dropped when there are BLOCKs",
  inlineFailure.flagExists === false,
  inlineFailure,
);

// ---------------------------------------------------------------- assert 14
// Inline mode exit code is non-zero when there's a BLOCK (so refresh-api.sh
// captures it in INLINE_GATE_RC).
assert(
  "inline mode: exit code non-zero when BLOCK detected",
  inlineFailure.exitCode !== 0,
  inlineFailure.exitCode,
);

// ---------------------------------------------------------------- summary
console.log(`\n${pass} pass, ${fail} fail`);
if (fail > 0) process.exit(1);
