/**
 * Regression test for scripts/sws-sanity-gate.mjs picks_recent threshold.
 *
 * Background: the gate's picks_recent check used to fire BLOCK once
 * picks-latest.json was > 6h old. The actual nightly cadence is 12h
 * (02:00 + 16:30 IST), so the first slightly-late refresh flipped the
 * verdict to FAIL — and because the verdict file itself only gets
 * regenerated by sws-nightly.sh (which the gate is gating!), it then
 * sat stuck at FAIL for days, silently disabling the production
 * safety net. The threshold was loosened from 6h → 14h (12h cadence
 * + 2h slack). This test pins both the constant and the boundary
 * behaviour so a future "tighten it back" change has to come with
 * intent.
 *
 * Run with: node test/swsSanityGate.test.mjs
 */

import { spawnSync } from "child_process";
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, rmSync } from "fs";
import { tmpdir } from "os";
import { dirname, join, resolve } from "path";
import { fileURLToPath } from "url";

import { PICKS_MAX_AGE_HOURS } from "../scripts/sws-sanity-gate.mjs";

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(__dirname, "..");
const GATE_SCRIPT = resolve(REPO_ROOT, "scripts/sws-sanity-gate.mjs");

let pass = 0;
let fail = 0;
function assert(name, cond, got) {
  if (cond) {
    pass++;
    console.log("  ✓", name);
  } else {
    fail++;
    console.log("  ✗", name, "→ got", JSON.stringify(got));
  }
}

console.log("\nsws-sanity-gate.mjs picks_recent threshold regression\n");

// ---------------------------------------------------------------- assert 1
// Constant pinned at 14h. Any change to this value should come with a
// matching explanation — accidentally reverting to 6 reintroduces the
// self-perpetuating FAIL the loosening was meant to fix.
assert(
  "PICKS_MAX_AGE_HOURS exported and equal to 14",
  PICKS_MAX_AGE_HOURS === 14,
  PICKS_MAX_AGE_HOURS,
);

// ---------------------------------------------------------------- helpers
// Build a minimal SWS_SANITY_ROOT fixture so the gate runs end-to-end.
// We only care about the picks_recent finding here, so other layers can
// be in whatever shape — they'll fail BLOCK and FAIL the verdict, but
// our assertion targets the specific finding regardless of verdict.
function buildFixture(ageHours) {
  const root = mkdtempSync(join(tmpdir(), "sws-sanity-test-"));
  mkdirSync(join(root, "deep"), { recursive: true });

  const scannedAt = new Date(Date.now() - ageHours * 3600 * 1000).toISOString();
  writeFileSync(
    join(root, "picks-latest.json"),
    JSON.stringify({
      scanned_at: scannedAt,
      sections: {
        top_ranked_30_v3: [],
        best_to_buy_now: [],
        upcoming_earnings: [],
      },
    }),
  );

  // Minimal last-refresh.json — present-but-empty is enough to let
  // layer1() reach the picks_recent block. Other L1 checks will fail
  // BLOCK on missing fields; we don't care.
  writeFileSync(
    join(root, "last-refresh.json"),
    JSON.stringify({
      finished_at: new Date().toISOString(),
      scored_count: 0,
      news_populated_count: 0,
      rewards_populated_count: 0,
      risks_populated_count: 0,
      shards_failed: 0,
    }),
  );

  writeFileSync(join(root, "universe.json"), "[]");
  writeFileSync(join(root, "sws-scored-universe.json"), "[]");
  return root;
}

function runGateAndGetPicksFinding(ageHours) {
  const root = buildFixture(ageHours);
  try {
    const result = spawnSync("node", [GATE_SCRIPT], {
      env: { ...process.env, SWS_SANITY_ROOT: root, SWS_RUN_ID: "" },
      encoding: "utf-8",
    });
    if (result.error) throw result.error;
    const reportPath = join(root, "_sanity", "_latest.json");
    const report = JSON.parse(readFileSync(reportPath, "utf-8"));
    const l1 = report.layers.L1_run_integrity?.checks || [];
    return l1.find((c) => c.name === "picks_recent");
  } finally {
    try { rmSync(root, { recursive: true, force: true }); } catch {}
  }
}

// ---------------------------------------------------------------- assert 2
// 13.99h < 14h threshold → picks_recent check passes.
const justUnder = runGateAndGetPicksFinding(13.99);
assert(
  "picks_recent age=13.99 → ok=true (under 14h threshold)",
  justUnder && justUnder.ok === true,
  justUnder,
);
assert(
  "picks_recent age=13.99 → detail.threshold=14",
  justUnder && justUnder.detail?.threshold === 14,
  justUnder?.detail,
);

// ---------------------------------------------------------------- assert 3
// 14.01h >= 14h threshold → picks_recent check BLOCKs.
const justOver = runGateAndGetPicksFinding(14.01);
assert(
  "picks_recent age=14.01 → ok=false (over 14h threshold)",
  justOver && justOver.ok === false,
  justOver,
);
assert(
  "picks_recent age=14.01 → severity=BLOCK",
  justOver && justOver.severity === "BLOCK",
  justOver,
);

// ---------------------------------------------------------------- summary
console.log(`\n${pass} pass, ${fail} fail`);
if (fail > 0) process.exit(1);
