// Flat stock universe with index tagging.
//
// Each entry: { symbol, name, sector, indices: string[] }
// Index tags: "NIFTY50", "NIFTY_NEXT_50", "NIFTY100" (derived), "MIDCAP"
//
// This replaces the old NIFTY_50 + POPULAR_MIDCAPS split. Scans filter via
// getStocksByIndex("NIFTY50") or getAllStocks().

const ALL_STOCKS = [
  // ========== NIFTY 50 ==========
  { symbol: "RELIANCE.NS", name: "Reliance Industries", sector: "Energy", indices: ["NIFTY50"] },
  { symbol: "TCS.NS", name: "Tata Consultancy Services", sector: "IT", indices: ["NIFTY50"] },
  { symbol: "HDFCBANK.NS", name: "HDFC Bank", sector: "Banking", indices: ["NIFTY50"] },
  { symbol: "INFY.NS", name: "Infosys", sector: "IT", indices: ["NIFTY50"] },
  { symbol: "ICICIBANK.NS", name: "ICICI Bank", sector: "Banking", indices: ["NIFTY50"] },
  { symbol: "HINDUNILVR.NS", name: "Hindustan Unilever", sector: "FMCG", indices: ["NIFTY50"] },
  { symbol: "ITC.NS", name: "ITC", sector: "FMCG", indices: ["NIFTY50"] },
  { symbol: "SBIN.NS", name: "State Bank of India", sector: "Banking", indices: ["NIFTY50"] },
  { symbol: "BHARTIARTL.NS", name: "Bharti Airtel", sector: "Telecom", indices: ["NIFTY50"] },
  { symbol: "KOTAKBANK.NS", name: "Kotak Mahindra Bank", sector: "Banking", indices: ["NIFTY50"] },
  { symbol: "LT.NS", name: "Larsen & Toubro", sector: "Infrastructure", indices: ["NIFTY50"] },
  { symbol: "AXISBANK.NS", name: "Axis Bank", sector: "Banking", indices: ["NIFTY50"] },
  { symbol: "WIPRO.NS", name: "Wipro", sector: "IT", indices: ["NIFTY50"] },
  { symbol: "ASIANPAINT.NS", name: "Asian Paints", sector: "Consumer", indices: ["NIFTY50"] },
  { symbol: "MARUTI.NS", name: "Maruti Suzuki", sector: "Auto", indices: ["NIFTY50"] },
  { symbol: "HCLTECH.NS", name: "HCL Technologies", sector: "IT", indices: ["NIFTY50"] },
  { symbol: "TITAN.NS", name: "Titan Company", sector: "Consumer", indices: ["NIFTY50"] },
  { symbol: "SUNPHARMA.NS", name: "Sun Pharma", sector: "Pharma", indices: ["NIFTY50"] },
  { symbol: "BAJFINANCE.NS", name: "Bajaj Finance", sector: "Finance", indices: ["NIFTY50"] },
  { symbol: "ULTRACEMCO.NS", name: "UltraTech Cement", sector: "Cement", indices: ["NIFTY50"] },
  { symbol: "NESTLEIND.NS", name: "Nestle India", sector: "FMCG", indices: ["NIFTY50"] },
  { symbol: "TATAMOTORS.NS", name: "Tata Motors", sector: "Auto", indices: ["NIFTY50"] },
  { symbol: "NTPC.NS", name: "NTPC", sector: "Power", indices: ["NIFTY50"] },
  { symbol: "POWERGRID.NS", name: "Power Grid Corp", sector: "Power", indices: ["NIFTY50"] },
  { symbol: "M&M.NS", name: "Mahindra & Mahindra", sector: "Auto", indices: ["NIFTY50"] },
  { symbol: "TATASTEEL.NS", name: "Tata Steel", sector: "Metals", indices: ["NIFTY50"] },
  { symbol: "ONGC.NS", name: "ONGC", sector: "Energy", indices: ["NIFTY50"] },
  { symbol: "JSWSTEEL.NS", name: "JSW Steel", sector: "Metals", indices: ["NIFTY50"] },
  { symbol: "ADANIENT.NS", name: "Adani Enterprises", sector: "Diversified", indices: ["NIFTY50"] },
  { symbol: "ADANIPORTS.NS", name: "Adani Ports", sector: "Infrastructure", indices: ["NIFTY50"] },
  { symbol: "COALINDIA.NS", name: "Coal India", sector: "Mining", indices: ["NIFTY50"] },
  { symbol: "BPCL.NS", name: "BPCL", sector: "Energy", indices: ["NIFTY50"] },
  { symbol: "GRASIM.NS", name: "Grasim Industries", sector: "Diversified", indices: ["NIFTY50"] },
  { symbol: "TECHM.NS", name: "Tech Mahindra", sector: "IT", indices: ["NIFTY50"] },
  { symbol: "INDUSINDBK.NS", name: "IndusInd Bank", sector: "Banking", indices: ["NIFTY50"] },
  { symbol: "HINDALCO.NS", name: "Hindalco", sector: "Metals", indices: ["NIFTY50"] },
  { symbol: "DRREDDY.NS", name: "Dr Reddy's Labs", sector: "Pharma", indices: ["NIFTY50"] },
  { symbol: "CIPLA.NS", name: "Cipla", sector: "Pharma", indices: ["NIFTY50"] },
  { symbol: "DIVISLAB.NS", name: "Divi's Laboratories", sector: "Pharma", indices: ["NIFTY50"] },
  { symbol: "EICHERMOT.NS", name: "Eicher Motors", sector: "Auto", indices: ["NIFTY50"] },
  { symbol: "BAJAJFINSV.NS", name: "Bajaj Finserv", sector: "Finance", indices: ["NIFTY50"] },
  { symbol: "BRITANNIA.NS", name: "Britannia Industries", sector: "FMCG", indices: ["NIFTY50"] },
  { symbol: "HEROMOTOCO.NS", name: "Hero MotoCorp", sector: "Auto", indices: ["NIFTY50"] },
  { symbol: "APOLLOHOSP.NS", name: "Apollo Hospitals", sector: "Healthcare", indices: ["NIFTY50"] },
  { symbol: "SBILIFE.NS", name: "SBI Life Insurance", sector: "Insurance", indices: ["NIFTY50"] },
  { symbol: "HDFCLIFE.NS", name: "HDFC Life Insurance", sector: "Insurance", indices: ["NIFTY50"] },
  { symbol: "TATACONSUM.NS", name: "Tata Consumer Products", sector: "FMCG", indices: ["NIFTY50"] },
  { symbol: "BAJAJ-AUTO.NS", name: "Bajaj Auto", sector: "Auto", indices: ["NIFTY50"] },
  { symbol: "UPL.NS", name: "UPL", sector: "Chemicals", indices: ["NIFTY50"] },
  { symbol: "SHRIRAMFIN.NS", name: "Shriram Finance", sector: "Finance", indices: ["NIFTY50"] },

  // ========== NIFTY NEXT 50 ==========
  { symbol: "LICI.NS", name: "Life Insurance Corp", sector: "Insurance", indices: ["NIFTY_NEXT_50"] },
  { symbol: "DMART.NS", name: "Avenue Supermarts (DMart)", sector: "Retail", indices: ["NIFTY_NEXT_50"] },
  { symbol: "PIDILITIND.NS", name: "Pidilite Industries", sector: "Chemicals", indices: ["NIFTY_NEXT_50"] },
  { symbol: "SIEMENS.NS", name: "Siemens India", sector: "Capital Goods", indices: ["NIFTY_NEXT_50"] },
  { symbol: "ABB.NS", name: "ABB India", sector: "Capital Goods", indices: ["NIFTY_NEXT_50"] },
  { symbol: "BOSCHLTD.NS", name: "Bosch Ltd", sector: "Auto Components", indices: ["NIFTY_NEXT_50"] },
  { symbol: "HAVELLS.NS", name: "Havells India", sector: "Consumer Durables", indices: ["NIFTY_NEXT_50"] },
  { symbol: "GODREJCP.NS", name: "Godrej Consumer Products", sector: "FMCG", indices: ["NIFTY_NEXT_50"] },
  { symbol: "DABUR.NS", name: "Dabur India", sector: "FMCG", indices: ["NIFTY_NEXT_50"] },
  { symbol: "MARICO.NS", name: "Marico", sector: "FMCG", indices: ["NIFTY_NEXT_50"] },
  { symbol: "ICICIGI.NS", name: "ICICI Lombard General Insurance", sector: "Insurance", indices: ["NIFTY_NEXT_50"] },
  { symbol: "ICICIPRULI.NS", name: "ICICI Prudential Life", sector: "Insurance", indices: ["NIFTY_NEXT_50"] },
  { symbol: "LODHA.NS", name: "Macrotech Developers (Lodha)", sector: "Real Estate", indices: ["NIFTY_NEXT_50"] },
  { symbol: "CHOLAFIN.NS", name: "Cholamandalam Investment", sector: "Finance", indices: ["NIFTY_NEXT_50"] },
  { symbol: "JINDALSTEL.NS", name: "Jindal Steel & Power", sector: "Metals", indices: ["NIFTY_NEXT_50"] },
  { symbol: "VEDL.NS", name: "Vedanta", sector: "Mining", indices: ["NIFTY_NEXT_50"] },
  { symbol: "LTIM.NS", name: "LTIMindtree", sector: "IT", indices: ["NIFTY_NEXT_50"] },
  { symbol: "MPHASIS.NS", name: "Mphasis", sector: "IT", indices: ["NIFTY_NEXT_50"] },
  { symbol: "OFSS.NS", name: "Oracle Financial Services", sector: "IT", indices: ["NIFTY_NEXT_50"] },
  { symbol: "TATAPOWER.NS", name: "Tata Power", sector: "Power", indices: ["NIFTY_NEXT_50"] },
  { symbol: "TORNTPHARM.NS", name: "Torrent Pharma", sector: "Pharma", indices: ["NIFTY_NEXT_50"] },
  { symbol: "ZYDUSLIFE.NS", name: "Zydus Lifesciences", sector: "Pharma", indices: ["NIFTY_NEXT_50"] },
  { symbol: "LUPIN.NS", name: "Lupin", sector: "Pharma", indices: ["NIFTY_NEXT_50"] },
  { symbol: "APOLLOTYRE.NS", name: "Apollo Tyres", sector: "Auto Components", indices: ["NIFTY_NEXT_50"] },
  { symbol: "TVSMOTOR.NS", name: "TVS Motor", sector: "Auto", indices: ["NIFTY_NEXT_50"] },
  { symbol: "BAJAJHLDNG.NS", name: "Bajaj Holdings", sector: "Finance", indices: ["NIFTY_NEXT_50"] },
  { symbol: "IOC.NS", name: "Indian Oil Corp", sector: "Energy", indices: ["NIFTY_NEXT_50"] },
  { symbol: "HINDPETRO.NS", name: "Hindustan Petroleum", sector: "Energy", indices: ["NIFTY_NEXT_50"] },
  { symbol: "GAIL.NS", name: "GAIL India", sector: "Energy", indices: ["NIFTY_NEXT_50"] },
  { symbol: "HAL.NS", name: "Hindustan Aeronautics", sector: "Defence", indices: ["NIFTY_NEXT_50"] },
  { symbol: "BEL.NS", name: "Bharat Electronics", sector: "Defence", indices: ["NIFTY_NEXT_50"] },
  { symbol: "IRCTC.NS", name: "IRCTC", sector: "Tourism", indices: ["NIFTY_NEXT_50"] },
  { symbol: "TRENT.NS", name: "Trent", sector: "Retail", indices: ["NIFTY_NEXT_50"] },
  { symbol: "INDIGO.NS", name: "InterGlobe Aviation (IndiGo)", sector: "Airlines", indices: ["NIFTY_NEXT_50"] },
  { symbol: "ADANIGREEN.NS", name: "Adani Green Energy", sector: "Renewable Energy", indices: ["NIFTY_NEXT_50"] },
  { symbol: "ADANIPOWER.NS", name: "Adani Power", sector: "Power", indices: ["NIFTY_NEXT_50"] },
  { symbol: "AMBUJACEM.NS", name: "Ambuja Cements", sector: "Cement", indices: ["NIFTY_NEXT_50"] },
  { symbol: "ACC.NS", name: "ACC", sector: "Cement", indices: ["NIFTY_NEXT_50"] },
  { symbol: "BANKBARODA.NS", name: "Bank of Baroda", sector: "Banking", indices: ["NIFTY_NEXT_50"] },
  { symbol: "PNB.NS", name: "Punjab National Bank", sector: "Banking", indices: ["NIFTY_NEXT_50"] },
  { symbol: "CANBK.NS", name: "Canara Bank", sector: "Banking", indices: ["NIFTY_NEXT_50"] },
  { symbol: "UNIONBANK.NS", name: "Union Bank of India", sector: "Banking", indices: ["NIFTY_NEXT_50"] },
  { symbol: "INDHOTEL.NS", name: "Indian Hotels (Taj)", sector: "Hospitality", indices: ["NIFTY_NEXT_50"] },
  { symbol: "DLF.NS", name: "DLF", sector: "Real Estate", indices: ["NIFTY_NEXT_50"] },
  { symbol: "NAUKRI.NS", name: "Info Edge (Naukri)", sector: "Internet", indices: ["NIFTY_NEXT_50"] },
  { symbol: "PFC.NS", name: "Power Finance Corp", sector: "Finance", indices: ["NIFTY_NEXT_50"] },
  { symbol: "RECLTD.NS", name: "REC Limited", sector: "Finance", indices: ["NIFTY_NEXT_50"] },
  { symbol: "IRFC.NS", name: "IRFC", sector: "Finance", indices: ["NIFTY_NEXT_50"] },
  { symbol: "CGPOWER.NS", name: "CG Power & Industrial", sector: "Capital Goods", indices: ["NIFTY_NEXT_50"] },
  { symbol: "JSWENERGY.NS", name: "JSW Energy", sector: "Power", indices: ["NIFTY_NEXT_50"] },

  // ========== POPULAR MIDCAPS / MICROCAPS ==========
  { symbol: "ZOMATO.NS", name: "Zomato", sector: "Internet", indices: ["MIDCAP"] },
  { symbol: "PAYTM.NS", name: "Paytm (One97)", sector: "Fintech", indices: ["MIDCAP"] },
  { symbol: "NYKAA.NS", name: "Nykaa (FSN E-Comm)", sector: "E-Commerce", indices: ["MIDCAP"] },
  { symbol: "POLYCAB.NS", name: "Polycab India", sector: "Electricals", indices: ["MIDCAP"] },
  { symbol: "PIIND.NS", name: "PI Industries", sector: "Chemicals", indices: ["MIDCAP"] },
  { symbol: "MUTHOOTFIN.NS", name: "Muthoot Finance", sector: "Finance", indices: ["MIDCAP"] },
  { symbol: "JUBLFOOD.NS", name: "Jubilant FoodWorks", sector: "QSR", indices: ["MIDCAP"] },
  { symbol: "DIXON.NS", name: "Dixon Technologies", sector: "Electronics", indices: ["MIDCAP"] },
  { symbol: "PERSISTENT.NS", name: "Persistent Systems", sector: "IT", indices: ["MIDCAP"] },
  { symbol: "COFORGE.NS", name: "Coforge", sector: "IT", indices: ["MIDCAP"] },
  { symbol: "TATAELXSI.NS", name: "Tata Elxsi", sector: "IT", indices: ["MIDCAP"] },
  { symbol: "FEDERALBNK.NS", name: "Federal Bank", sector: "Banking", indices: ["MIDCAP"] },
  { symbol: "IDFCFIRSTB.NS", name: "IDFC First Bank", sector: "Banking", indices: ["MIDCAP"] },
  { symbol: "SAIL.NS", name: "SAIL", sector: "Metals", indices: ["MIDCAP"] },
  { symbol: "NHPC.NS", name: "NHPC", sector: "Power", indices: ["MIDCAP"] },
  { symbol: "JIOFIN.NS", name: "Jio Financial Services", sector: "Finance", indices: ["MIDCAP"] },

  // ========== NIFTY 500 (auto-generated from NSE Apr 2026) ==========
  { symbol: "ACMESOLAR.NS", name: "ACME Solar Holdings", sector: "Power", indices: ["NIFTY500"] },
  { symbol: "AIAENG.NS", name: "AIA Engineering", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "APLAPOLLO.NS", name: "APL Apollo Tubes", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "AUBANK.NS", name: "AU Small Finance Bank", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "AWL.NS", name: "AWL Agri Business", sector: "FMCG", indices: ["NIFTY500"] },
  { symbol: "AADHARHFC.NS", name: "Aadhar Housing Finance", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "AARTIIND.NS", name: "Aarti Industries", sector: "Chemicals", indices: ["NIFTY500"] },
  { symbol: "AAVAS.NS", name: "Aavas Financiers", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "ABBOTINDIA.NS", name: "Abbott India", sector: "Pharma", indices: ["NIFTY500"] },
  { symbol: "ACE.NS", name: "Action Construction Equipment", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "ACUTAAS.NS", name: "Acutaas Chemicals", sector: "Pharma", indices: ["NIFTY500"] },
  { symbol: "ADANIENSOL.NS", name: "Adani Energy Solutions", sector: "Power", indices: ["NIFTY500"] },
  { symbol: "ATGL.NS", name: "Adani Total Gas", sector: "Energy", indices: ["NIFTY500"] },
  { symbol: "ABCAPITAL.NS", name: "Aditya Birla Capital", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "ABFRL.NS", name: "Aditya Birla Fashion and Retail", sector: "Consumer", indices: ["NIFTY500"] },
  { symbol: "ABLBL.NS", name: "Aditya Birla Lifestyle Brands", sector: "Consumer", indices: ["NIFTY500"] },
  { symbol: "ABREL.NS", name: "Aditya Birla Real Estate", sector: "Real Estate", indices: ["NIFTY500"] },
  { symbol: "ABSLAMC.NS", name: "Aditya Birla Sun Life AMC", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "CPPLUS.NS", name: "Aditya Infotech", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "AEGISLOG.NS", name: "Aegis Logistics", sector: "Energy", indices: ["NIFTY500"] },
  { symbol: "AEGISVOPAK.NS", name: "Aegis Vopak Terminals", sector: "Energy", indices: ["NIFTY500"] },
  { symbol: "AFCONS.NS", name: "Afcons Infrastructure", sector: "Construction", indices: ["NIFTY500"] },
  { symbol: "AFFLE.NS", name: "Affle 3i", sector: "IT", indices: ["NIFTY500"] },
  { symbol: "AJANTPHARM.NS", name: "Ajanta Pharmaceuticals", sector: "Pharma", indices: ["NIFTY500"] },
  { symbol: "ALKEM.NS", name: "Alkem Laboratories", sector: "Pharma", indices: ["NIFTY500"] },
  { symbol: "ABDL.NS", name: "Allied Blenders and Distillers", sector: "FMCG", indices: ["NIFTY500"] },
  { symbol: "ARE&M.NS", name: "Amara Raja Energy & Mobility", sector: "Auto", indices: ["NIFTY500"] },
  { symbol: "AMBER.NS", name: "Amber Enterprises India", sector: "Consumer", indices: ["NIFTY500"] },
  { symbol: "ANANDRATHI.NS", name: "Anand Rathi Wealth", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "ANANTRAJ.NS", name: "Anant Raj", sector: "Real Estate", indices: ["NIFTY500"] },
  { symbol: "ANGELONE.NS", name: "Angel One", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "ANTHEM.NS", name: "Anthem Biosciences", sector: "Pharma", indices: ["NIFTY500"] },
  { symbol: "ANURAS.NS", name: "Anupam Rasayan India", sector: "Chemicals", indices: ["NIFTY500"] },
  { symbol: "APARINDS.NS", name: "Apar Industries", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "APTUS.NS", name: "Aptus Value Housing Finance India", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "ASAHIINDIA.NS", name: "Asahi India Glass", sector: "Auto", indices: ["NIFTY500"] },
  { symbol: "ASHOKLEY.NS", name: "Ashok Leyland", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "ASTERDM.NS", name: "Aster DM Healthcare", sector: "Pharma", indices: ["NIFTY500"] },
  { symbol: "ASTRAL.NS", name: "Astral", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "ATHERENERG.NS", name: "Ather Energy", sector: "Auto", indices: ["NIFTY500"] },
  { symbol: "ATUL.NS", name: "Atul", sector: "Chemicals", indices: ["NIFTY500"] },
  { symbol: "AUROPHARMA.NS", name: "Aurobindo Pharma", sector: "Pharma", indices: ["NIFTY500"] },
  { symbol: "AIIL.NS", name: "Authum Investment & Infrastructure", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "BEML.NS", name: "BEML", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "BLS.NS", name: "BLS International Services", sector: "Consumer", indices: ["NIFTY500"] },
  { symbol: "BSE.NS", name: "BSE", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "BAJAJHFL.NS", name: "Bajaj Housing Finance", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "BALKRISIND.NS", name: "Balkrishna Industries", sector: "Auto", indices: ["NIFTY500"] },
  { symbol: "BALRAMCHIN.NS", name: "Balrampur Chini Mills", sector: "FMCG", indices: ["NIFTY500"] },
  { symbol: "BANDHANBNK.NS", name: "Bandhan Bank", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "BANKINDIA.NS", name: "Bank of India", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "MAHABANK.NS", name: "Bank of Maharashtra", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "BATAINDIA.NS", name: "Bata India", sector: "Consumer", indices: ["NIFTY500"] },
  { symbol: "BAYERCROP.NS", name: "Bayer Cropscience", sector: "Chemicals", indices: ["NIFTY500"] },
  { symbol: "BELRISE.NS", name: "Belrise Industries", sector: "Auto", indices: ["NIFTY500"] },
  { symbol: "BERGEPAINT.NS", name: "Berger Paints India", sector: "Consumer", indices: ["NIFTY500"] },
  { symbol: "BDL.NS", name: "Bharat Dynamics", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "BHARATFORG.NS", name: "Bharat Forge", sector: "Auto", indices: ["NIFTY500"] },
  { symbol: "BHEL.NS", name: "Bharat Heavy Electricals", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "BHARTIHEXA.NS", name: "Bharti Hexacom", sector: "Telecom", indices: ["NIFTY500"] },
  { symbol: "BIKAJI.NS", name: "Bikaji Foods International", sector: "FMCG", indices: ["NIFTY500"] },
  { symbol: "GROWW.NS", name: "Billionbrains Garage Ventures", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "BIOCON.NS", name: "Biocon", sector: "Pharma", indices: ["NIFTY500"] },
  { symbol: "BSOFT.NS", name: "Birlasoft", sector: "IT", indices: ["NIFTY500"] },
  { symbol: "BLUEDART.NS", name: "Blue Dart Express", sector: "Services", indices: ["NIFTY500"] },
  { symbol: "BLUEJET.NS", name: "Blue Jet Healthcare", sector: "Pharma", indices: ["NIFTY500"] },
  { symbol: "BLUESTARCO.NS", name: "Blue Star", sector: "Consumer", indices: ["NIFTY500"] },
  { symbol: "BBTC.NS", name: "Bombay Burmah Trading Corporation", sector: "FMCG", indices: ["NIFTY500"] },
  { symbol: "FIRSTCRY.NS", name: "Brainbees Solutions", sector: "Consumer", indices: ["NIFTY500"] },
  { symbol: "BRIGADE.NS", name: "Brigade Enterprises", sector: "Real Estate", indices: ["NIFTY500"] },
  { symbol: "MAPMYINDIA.NS", name: "C.E. Info Systems", sector: "IT", indices: ["NIFTY500"] },
  { symbol: "CCL.NS", name: "CCL Products (I)", sector: "FMCG", indices: ["NIFTY500"] },
  { symbol: "CESC.NS", name: "CESC", sector: "Power", indices: ["NIFTY500"] },
  { symbol: "CRISIL.NS", name: "CRISIL", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "CANFINHOME.NS", name: "Can Fin Homes", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "CANHLIFE.NS", name: "Canara HSBC Life Insurance Company", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "CAPLIPOINT.NS", name: "Caplin Point Laboratories", sector: "Pharma", indices: ["NIFTY500"] },
  { symbol: "CGCL.NS", name: "Capri Global Capital", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "CARBORUNIV.NS", name: "Carborundum Universal", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "CARTRADE.NS", name: "Cartrade Tech", sector: "Consumer", indices: ["NIFTY500"] },
  { symbol: "CASTROLIND.NS", name: "Castrol India", sector: "Energy", indices: ["NIFTY500"] },
  { symbol: "CEATLTD.NS", name: "Ceat", sector: "Auto", indices: ["NIFTY500"] },
  { symbol: "CEMPRO.NS", name: "Cemindia Projects", sector: "Construction", indices: ["NIFTY500"] },
  { symbol: "CENTRALBK.NS", name: "Central Bank of India", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "CDSL.NS", name: "Central Depository Services (India)", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "CHALET.NS", name: "Chalet Hotels", sector: "Consumer", indices: ["NIFTY500"] },
  { symbol: "CHAMBLFERT.NS", name: "Chambal Fertilizers & Chemicals", sector: "Chemicals", indices: ["NIFTY500"] },
  { symbol: "CHENNPETRO.NS", name: "Chennai Petroleum Corporation", sector: "Energy", indices: ["NIFTY500"] },
  { symbol: "CHOICEIN.NS", name: "Choice International", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "CHOLAHLDNG.NS", name: "Cholamandalam Financial Holdings", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "CUB.NS", name: "City Union Bank", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "CLEAN.NS", name: "Clean Science and Technology", sector: "Chemicals", indices: ["NIFTY500"] },
  { symbol: "COCHINSHIP.NS", name: "Cochin Shipyard", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "COHANCE.NS", name: "Cohance Lifesciences", sector: "Pharma", indices: ["NIFTY500"] },
  { symbol: "COLPAL.NS", name: "Colgate Palmolive (India)", sector: "FMCG", indices: ["NIFTY500"] },
  { symbol: "CAMS.NS", name: "Computer Age Management Services", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "CONCORDBIO.NS", name: "Concord Biotech", sector: "Pharma", indices: ["NIFTY500"] },
  { symbol: "CONCOR.NS", name: "Container Corporation of India", sector: "Services", indices: ["NIFTY500"] },
  { symbol: "COROMANDEL.NS", name: "Coromandel International", sector: "Chemicals", indices: ["NIFTY500"] },
  { symbol: "CRAFTSMAN.NS", name: "Craftsman Automation", sector: "Auto", indices: ["NIFTY500"] },
  { symbol: "CREDITACC.NS", name: "CreditAccess Grameen", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "CROMPTON.NS", name: "Crompton Greaves Consumer Electricals", sector: "Consumer", indices: ["NIFTY500"] },
  { symbol: "CUMMINSIND.NS", name: "Cummins India", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "CYIENT.NS", name: "Cyient", sector: "IT", indices: ["NIFTY500"] },
  { symbol: "DCMSHRIRAM.NS", name: "DCM Shriram", sector: "Diversified", indices: ["NIFTY500"] },
  { symbol: "DOMS.NS", name: "DOMS Industries", sector: "FMCG", indices: ["NIFTY500"] },
  { symbol: "DALBHARAT.NS", name: "Dalmia Bharat", sector: "Cement", indices: ["NIFTY500"] },
  { symbol: "DATAPATTNS.NS", name: "Data Patterns (India)", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "DEEPAKFERT.NS", name: "Deepak Fertilisers & Petrochemicals Corp.", sector: "Chemicals", indices: ["NIFTY500"] },
  { symbol: "DEEPAKNTR.NS", name: "Deepak Nitrite", sector: "Chemicals", indices: ["NIFTY500"] },
  { symbol: "DELHIVERY.NS", name: "Delhivery", sector: "Services", indices: ["NIFTY500"] },
  { symbol: "DEVYANI.NS", name: "Devyani International", sector: "Consumer", indices: ["NIFTY500"] },
  { symbol: "LALPATHLAB.NS", name: "Dr. Lal Path Labs", sector: "Pharma", indices: ["NIFTY500"] },
  { symbol: "EIDPARRY.NS", name: "E.I.D. Parry (India)", sector: "FMCG", indices: ["NIFTY500"] },
  { symbol: "EIHOTEL.NS", name: "EIH", sector: "Consumer", indices: ["NIFTY500"] },
  { symbol: "ELECON.NS", name: "Elecon Engineering Co.", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "ELGIEQUIP.NS", name: "Elgi Equipments", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "EMAMILTD.NS", name: "Emami", sector: "FMCG", indices: ["NIFTY500"] },
  { symbol: "EMCURE.NS", name: "Emcure Pharmaceuticals", sector: "Pharma", indices: ["NIFTY500"] },
  { symbol: "EMMVEE.NS", name: "Emmvee Photovoltaic Power", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "ENDURANCE.NS", name: "Endurance Technologies", sector: "Auto", indices: ["NIFTY500"] },
  { symbol: "ENGINERSIN.NS", name: "Engineers India", sector: "Construction", indices: ["NIFTY500"] },
  { symbol: "ERIS.NS", name: "Eris Lifesciences", sector: "Pharma", indices: ["NIFTY500"] },
  { symbol: "ESCORTS.NS", name: "Escorts Kubota", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "ETERNAL.NS", name: "Eternal", sector: "Consumer", indices: ["NIFTY500"] },
  { symbol: "EXIDEIND.NS", name: "Exide Industries", sector: "Auto", indices: ["NIFTY500"] },
  { symbol: "FACT.NS", name: "Fertilisers and Chemicals Travancore", sector: "Chemicals", indices: ["NIFTY500"] },
  { symbol: "FINCABLES.NS", name: "Finolex Cables", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "FSL.NS", name: "Firstsource Solutions", sector: "Services", indices: ["NIFTY500"] },
  { symbol: "FIVESTAR.NS", name: "Five-Star Business Finance", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "FORCEMOT.NS", name: "Force Motors", sector: "Auto", indices: ["NIFTY500"] },
  { symbol: "FORTIS.NS", name: "Fortis Healthcare", sector: "Pharma", indices: ["NIFTY500"] },
  { symbol: "GVT&D.NS", name: "GE Vernova T&D India", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "GMRAIRPORT.NS", name: "GMR Airports", sector: "Services", indices: ["NIFTY500"] },
  { symbol: "GABRIEL.NS", name: "Gabriel India", sector: "Auto", indices: ["NIFTY500"] },
  { symbol: "GALLANTT.NS", name: "Gallantt Ispat", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "GRSE.NS", name: "Garden Reach Shipbuilders & Engineers", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "GICRE.NS", name: "General Insurance Corporation of India", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "GILLETTE.NS", name: "Gillette India", sector: "FMCG", indices: ["NIFTY500"] },
  { symbol: "GLAND.NS", name: "Gland Pharma", sector: "Pharma", indices: ["NIFTY500"] },
  { symbol: "GLAXO.NS", name: "Glaxosmithkline Pharmaceuticals", sector: "Pharma", indices: ["NIFTY500"] },
  { symbol: "GLENMARK.NS", name: "Glenmark Pharmaceuticals", sector: "Pharma", indices: ["NIFTY500"] },
  { symbol: "MEDANTA.NS", name: "Global Health", sector: "Pharma", indices: ["NIFTY500"] },
  { symbol: "GODIGIT.NS", name: "Go Digit General Insurance", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "GPIL.NS", name: "Godawari Power & Ispat", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "GODFRYPHLP.NS", name: "Godfrey Phillips India", sector: "FMCG", indices: ["NIFTY500"] },
  { symbol: "GODREJIND.NS", name: "Godrej Industries", sector: "Diversified", indices: ["NIFTY500"] },
  { symbol: "GODREJPROP.NS", name: "Godrej Properties", sector: "Real Estate", indices: ["NIFTY500"] },
  { symbol: "GRANULES.NS", name: "Granules India", sector: "Pharma", indices: ["NIFTY500"] },
  { symbol: "GRAPHITE.NS", name: "Graphite India", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "GRAVITA.NS", name: "Gravita India", sector: "Metals", indices: ["NIFTY500"] },
  { symbol: "GESHIP.NS", name: "Great Eastern Shipping Co.", sector: "Services", indices: ["NIFTY500"] },
  { symbol: "FLUOROCHEM.NS", name: "Gujarat Fluorochemicals", sector: "Chemicals", indices: ["NIFTY500"] },
  { symbol: "GMDCLTD.NS", name: "Gujarat Mineral Development Corporation", sector: "Metals", indices: ["NIFTY500"] },
  { symbol: "GSPL.NS", name: "Gujarat State Petronet", sector: "Energy", indices: ["NIFTY500"] },
  { symbol: "HEG.NS", name: "H.E.G.", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "HBLENGINE.NS", name: "HBL Engineering", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "HDBFS.NS", name: "HDB Financial Services", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "HDFCAMC.NS", name: "HDFC Asset Management Company", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "HFCL.NS", name: "HFCL", sector: "Telecom", indices: ["NIFTY500"] },
  { symbol: "HEXT.NS", name: "Hexaware Technologies", sector: "IT", indices: ["NIFTY500"] },
  { symbol: "HSCL.NS", name: "Himadri Speciality Chemical", sector: "Chemicals", indices: ["NIFTY500"] },
  { symbol: "HINDCOPPER.NS", name: "Hindustan Copper", sector: "Metals", indices: ["NIFTY500"] },
  { symbol: "HINDZINC.NS", name: "Hindustan Zinc", sector: "Metals", indices: ["NIFTY500"] },
  { symbol: "POWERINDIA.NS", name: "Hitachi Energy India", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "HOMEFIRST.NS", name: "Home First Finance Company India", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "HONASA.NS", name: "Honasa Consumer", sector: "FMCG", indices: ["NIFTY500"] },
  { symbol: "HONAUT.NS", name: "Honeywell Automation India", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "HUDCO.NS", name: "Housing & Urban Development Corporation", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "HYUNDAI.NS", name: "Hyundai Motor India", sector: "Auto", indices: ["NIFTY500"] },
  { symbol: "ICICIAMC.NS", name: "ICICI Prudential Asset Management Company", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "IDBI.NS", name: "IDBI Bank", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "IFCI.NS", name: "IFCI", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "IIFL.NS", name: "IIFL Finance", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "IRB.NS", name: "IRB Infrastructure Developers", sector: "Construction", indices: ["NIFTY500"] },
  { symbol: "IRCON.NS", name: "IRCON International", sector: "Construction", indices: ["NIFTY500"] },
  { symbol: "ITCHOTELS.NS", name: "ITC Hotels", sector: "Consumer", indices: ["NIFTY500"] },
  { symbol: "ITI.NS", name: "ITI", sector: "Telecom", indices: ["NIFTY500"] },
  { symbol: "INDGN.NS", name: "Indegene", sector: "Pharma", indices: ["NIFTY500"] },
  { symbol: "INDIACEM.NS", name: "India Cements", sector: "Cement", indices: ["NIFTY500"] },
  { symbol: "INDIAMART.NS", name: "Indiamart Intermesh", sector: "Consumer", indices: ["NIFTY500"] },
  { symbol: "INDIANB.NS", name: "Indian Bank", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "IEX.NS", name: "Indian Energy Exchange", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "IOB.NS", name: "Indian Overseas Bank", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "IREDA.NS", name: "Indian Renewable Energy Development Agency", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "IGL.NS", name: "Indraprastha Gas", sector: "Energy", indices: ["NIFTY500"] },
  { symbol: "INDUSTOWER.NS", name: "Indus Towers", sector: "Telecom", indices: ["NIFTY500"] },
  { symbol: "INOXWIND.NS", name: "Inox Wind", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "INTELLECT.NS", name: "Intellect Design Arena", sector: "IT", indices: ["NIFTY500"] },
  { symbol: "IGIL.NS", name: "International Gemmological Institute (India)", sector: "Services", indices: ["NIFTY500"] },
  { symbol: "IKS.NS", name: "Inventurus Knowledge Solutions", sector: "IT", indices: ["NIFTY500"] },
  { symbol: "IPCALAB.NS", name: "Ipca Laboratories", sector: "Pharma", indices: ["NIFTY500"] },
  { symbol: "JBCHEPHARM.NS", name: "J.B. Chemicals & Pharmaceuticals", sector: "Pharma", indices: ["NIFTY500"] },
  { symbol: "JKCEMENT.NS", name: "J.K. Cement", sector: "Cement", indices: ["NIFTY500"] },
  { symbol: "JBMA.NS", name: "JBM Auto", sector: "Auto", indices: ["NIFTY500"] },
  { symbol: "JKTYRE.NS", name: "JK Tyre & Industries", sector: "Auto", indices: ["NIFTY500"] },
  { symbol: "JMFINANCIL.NS", name: "JM Financial", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "JSWCEMENT.NS", name: "JSW Cement", sector: "Cement", indices: ["NIFTY500"] },
  { symbol: "JSWDULUX.NS", name: "JSW Dulux", sector: "Consumer", indices: ["NIFTY500"] },
  { symbol: "JSWINFRA.NS", name: "JSW Infrastructure", sector: "Services", indices: ["NIFTY500"] },
  { symbol: "JAINREC.NS", name: "Jain Resource Recycling", sector: "Metals", indices: ["NIFTY500"] },
  { symbol: "JPPOWER.NS", name: "Jaiprakash Power Ventures", sector: "Power", indices: ["NIFTY500"] },
  { symbol: "J&KBANK.NS", name: "Jammu & Kashmir Bank", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "JINDALSAW.NS", name: "Jindal Saw", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "JSL.NS", name: "Jindal Stainless", sector: "Metals", indices: ["NIFTY500"] },
  { symbol: "JUBLINGREA.NS", name: "Jubilant Ingrevia", sector: "Chemicals", indices: ["NIFTY500"] },
  { symbol: "JUBLPHARMA.NS", name: "Jubilant Pharmova", sector: "Pharma", indices: ["NIFTY500"] },
  { symbol: "JWL.NS", name: "Jupiter Wagons", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "JYOTICNC.NS", name: "Jyoti CNC Automation", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "KPRMILL.NS", name: "K.P.R. Mill", sector: "Textiles", indices: ["NIFTY500"] },
  { symbol: "KEI.NS", name: "KEI Industries", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "KPITTECH.NS", name: "KPIT Technologies", sector: "IT", indices: ["NIFTY500"] },
  { symbol: "KAJARIACER.NS", name: "Kajaria Ceramics", sector: "Consumer", indices: ["NIFTY500"] },
  { symbol: "KPIL.NS", name: "Kalpataru Projects International", sector: "Construction", indices: ["NIFTY500"] },
  { symbol: "KALYANKJIL.NS", name: "Kalyan Jewellers India", sector: "Consumer", indices: ["NIFTY500"] },
  { symbol: "KARURVYSYA.NS", name: "Karur Vysya Bank", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "KAYNES.NS", name: "Kaynes Technology India", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "KEC.NS", name: "Kec International", sector: "Construction", indices: ["NIFTY500"] },
  { symbol: "KFINTECH.NS", name: "Kfin Technologies", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "KIRLOSENG.NS", name: "Kirloskar Oil Eng", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "KIMS.NS", name: "Krishna Institute of Medical Sciences", sector: "Pharma", indices: ["NIFTY500"] },
  { symbol: "LTF.NS", name: "L&T Finance", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "LTTS.NS", name: "L&T Technology Services", sector: "IT", indices: ["NIFTY500"] },
  { symbol: "LGEINDIA.NS", name: "LG Electronics India", sector: "Consumer", indices: ["NIFTY500"] },
  { symbol: "LICHSGFIN.NS", name: "LIC Housing Finance", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "LTFOODS.NS", name: "LT Foods", sector: "FMCG", indices: ["NIFTY500"] },
  { symbol: "LTM.NS", name: "LTM", sector: "IT", indices: ["NIFTY500"] },
  { symbol: "LATENTVIEW.NS", name: "Latent View Analytics", sector: "IT", indices: ["NIFTY500"] },
  { symbol: "LAURUSLABS.NS", name: "Laurus Labs", sector: "Pharma", indices: ["NIFTY500"] },
  { symbol: "THELEELA.NS", name: "Leela Palaces Hotels & Resorts", sector: "Consumer", indices: ["NIFTY500"] },
  { symbol: "LEMONTREE.NS", name: "Lemon Tree Hotels", sector: "Consumer", indices: ["NIFTY500"] },
  { symbol: "LENSKART.NS", name: "Lenskart Solutions", sector: "Consumer", indices: ["NIFTY500"] },
  { symbol: "LINDEINDIA.NS", name: "Linde India", sector: "Chemicals", indices: ["NIFTY500"] },
  { symbol: "LLOYDSME.NS", name: "Lloyds Metals And Energy", sector: "Metals", indices: ["NIFTY500"] },
  { symbol: "MMTC.NS", name: "MMTC", sector: "Services", indices: ["NIFTY500"] },
  { symbol: "MRF.NS", name: "MRF", sector: "Auto", indices: ["NIFTY500"] },
  { symbol: "MGL.NS", name: "Mahanagar Gas", sector: "Energy", indices: ["NIFTY500"] },
  { symbol: "M&MFIN.NS", name: "Mahindra & Mahindra Financial Services", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "MANAPPURAM.NS", name: "Manappuram Finance", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "MRPL.NS", name: "Mangalore Refinery & Petrochemicals", sector: "Energy", indices: ["NIFTY500"] },
  { symbol: "MANKIND.NS", name: "Mankind Pharma", sector: "Pharma", indices: ["NIFTY500"] },
  { symbol: "MFSL.NS", name: "Max Financial Services", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "MAXHEALTH.NS", name: "Max Healthcare Institute", sector: "Pharma", indices: ["NIFTY500"] },
  { symbol: "MAZDOCK.NS", name: "Mazagoan Dock Shipbuilders", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "MEESHO.NS", name: "Meesho", sector: "Consumer", indices: ["NIFTY500"] },
  { symbol: "MINDACORP.NS", name: "Minda Corporation", sector: "Auto", indices: ["NIFTY500"] },
  { symbol: "MSUMI.NS", name: "Motherson Sumi Wiring India", sector: "Auto", indices: ["NIFTY500"] },
  { symbol: "MOTILALOFS.NS", name: "Motilal Oswal Financial Services", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "MCX.NS", name: "Multi Commodity Exchange of India", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "NATCOPHARM.NS", name: "NATCO Pharma", sector: "Pharma", indices: ["NIFTY500"] },
  { symbol: "NBCC.NS", name: "NBCC (India)", sector: "Construction", indices: ["NIFTY500"] },
  { symbol: "NCC.NS", name: "NCC", sector: "Construction", indices: ["NIFTY500"] },
  { symbol: "NLCINDIA.NS", name: "NLC India", sector: "Power", indices: ["NIFTY500"] },
  { symbol: "NMDC.NS", name: "NMDC", sector: "Metals", indices: ["NIFTY500"] },
  { symbol: "NSLNISP.NS", name: "NMDC Steel", sector: "Metals", indices: ["NIFTY500"] },
  { symbol: "NTPCGREEN.NS", name: "NTPC Green Energy", sector: "Power", indices: ["NIFTY500"] },
  { symbol: "NH.NS", name: "Narayana Hrudayalaya", sector: "Pharma", indices: ["NIFTY500"] },
  { symbol: "NATIONALUM.NS", name: "National Aluminium Co.", sector: "Metals", indices: ["NIFTY500"] },
  { symbol: "NAVA.NS", name: "Nava", sector: "Power", indices: ["NIFTY500"] },
  { symbol: "NAVINFLUOR.NS", name: "Navin Fluorine International", sector: "Chemicals", indices: ["NIFTY500"] },
  { symbol: "NETWEB.NS", name: "Netweb Technologies India", sector: "IT", indices: ["NIFTY500"] },
  { symbol: "NEULANDLAB.NS", name: "Neuland Laboratories", sector: "Pharma", indices: ["NIFTY500"] },
  { symbol: "NEWGEN.NS", name: "Newgen Software Technologies", sector: "IT", indices: ["NIFTY500"] },
  { symbol: "NAM-INDIA.NS", name: "Nippon Life India Asset Management", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "NIVABUPA.NS", name: "Niva Bupa Health Insurance Company", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "NUVAMA.NS", name: "Nuvama Wealth Management", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "NUVOCO.NS", name: "Nuvoco Vistas Corporation", sector: "Cement", indices: ["NIFTY500"] },
  { symbol: "OBEROIRLTY.NS", name: "Oberoi Realty", sector: "Real Estate", indices: ["NIFTY500"] },
  { symbol: "OIL.NS", name: "Oil India", sector: "Energy", indices: ["NIFTY500"] },
  { symbol: "OLAELEC.NS", name: "Ola Electric Mobility", sector: "Auto", indices: ["NIFTY500"] },
  { symbol: "OLECTRA.NS", name: "Olectra Greentech", sector: "Auto", indices: ["NIFTY500"] },
  { symbol: "ONESOURCE.NS", name: "Onesource Specialty Pharma", sector: "Pharma", indices: ["NIFTY500"] },
  { symbol: "POLICYBZR.NS", name: "PB Fintech", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "PCBL.NS", name: "PCBL Chemical", sector: "Chemicals", indices: ["NIFTY500"] },
  { symbol: "PGEL.NS", name: "PG Electroplast", sector: "Consumer", indices: ["NIFTY500"] },
  { symbol: "PNBHOUSING.NS", name: "PNB Housing Finance", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "PTCIL.NS", name: "PTC Industries", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "PVRINOX.NS", name: "PVR INOX", sector: "Media", indices: ["NIFTY500"] },
  { symbol: "PAGEIND.NS", name: "Page Industries", sector: "Textiles", indices: ["NIFTY500"] },
  { symbol: "PARADEEP.NS", name: "Paradeep Phosphates", sector: "Chemicals", indices: ["NIFTY500"] },
  { symbol: "PATANJALI.NS", name: "Patanjali Foods", sector: "FMCG", indices: ["NIFTY500"] },
  { symbol: "PETRONET.NS", name: "Petronet LNG", sector: "Energy", indices: ["NIFTY500"] },
  { symbol: "PFIZER.NS", name: "Pfizer", sector: "Pharma", indices: ["NIFTY500"] },
  { symbol: "PHOENIXLTD.NS", name: "Phoenix Mills", sector: "Real Estate", indices: ["NIFTY500"] },
  { symbol: "PWL.NS", name: "Physicswallah", sector: "Consumer", indices: ["NIFTY500"] },
  { symbol: "PINELABS.NS", name: "Pine Labs", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "PIRAMALFIN.NS", name: "Piramal Finance", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "PPLPHARMA.NS", name: "Piramal Pharma", sector: "Pharma", indices: ["NIFTY500"] },
  { symbol: "POLYMED.NS", name: "Poly Medicure", sector: "Pharma", indices: ["NIFTY500"] },
  { symbol: "POONAWALLA.NS", name: "Poonawalla Fincorp", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "PREMIERENE.NS", name: "Premier Energies", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "PRESTIGE.NS", name: "Prestige Estates Projects", sector: "Real Estate", indices: ["NIFTY500"] },
  { symbol: "RRKABEL.NS", name: "R R Kabel", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "RBLBANK.NS", name: "RBL Bank", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "RHIM.NS", name: "RHI MAGNESITA INDIA", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "RITES.NS", name: "RITES", sector: "Construction", indices: ["NIFTY500"] },
  { symbol: "RADICO.NS", name: "Radico Khaitan", sector: "FMCG", indices: ["NIFTY500"] },
  { symbol: "RVNL.NS", name: "Rail Vikas Nigam", sector: "Construction", indices: ["NIFTY500"] },
  { symbol: "RAILTEL.NS", name: "Railtel Corporation Of India", sector: "Telecom", indices: ["NIFTY500"] },
  { symbol: "RAINBOW.NS", name: "Rainbow Childrens Medicare", sector: "Pharma", indices: ["NIFTY500"] },
  { symbol: "RKFORGE.NS", name: "Ramkrishna Forgings", sector: "Auto", indices: ["NIFTY500"] },
  { symbol: "REDINGTON.NS", name: "Redington", sector: "Services", indices: ["NIFTY500"] },
  { symbol: "RPOWER.NS", name: "Reliance Power", sector: "Power", indices: ["NIFTY500"] },
  { symbol: "SBFC.NS", name: "SBFC Finance", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "SBICARD.NS", name: "SBI Cards and Payment Services", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "SJVN.NS", name: "SJVN", sector: "Power", indices: ["NIFTY500"] },
  { symbol: "SRF.NS", name: "SRF", sector: "Chemicals", indices: ["NIFTY500"] },
  { symbol: "SAGILITY.NS", name: "Sagility", sector: "IT", indices: ["NIFTY500"] },
  { symbol: "SAILIFE.NS", name: "Sai Life Sciences", sector: "Pharma", indices: ["NIFTY500"] },
  { symbol: "SAMMAANCAP.NS", name: "Sammaan Capital", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "MOTHERSON.NS", name: "Samvardhana Motherson International", sector: "Auto", indices: ["NIFTY500"] },
  { symbol: "SAPPHIRE.NS", name: "Sapphire Foods India", sector: "Consumer", indices: ["NIFTY500"] },
  { symbol: "SARDAEN.NS", name: "Sarda Energy and Minerals", sector: "Metals", indices: ["NIFTY500"] },
  { symbol: "SAREGAMA.NS", name: "Saregama India", sector: "Media", indices: ["NIFTY500"] },
  { symbol: "SCHAEFFLER.NS", name: "Schaeffler India", sector: "Auto", indices: ["NIFTY500"] },
  { symbol: "SCHNEIDER.NS", name: "Schneider Electric Infrastructure", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "SCI.NS", name: "Shipping Corporation of India", sector: "Services", indices: ["NIFTY500"] },
  { symbol: "SHREECEM.NS", name: "Shree Cement", sector: "Cement", indices: ["NIFTY500"] },
  { symbol: "SHYAMMETL.NS", name: "Shyam Metalics and Energy", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "ENRIN.NS", name: "Siemens Energy India", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "SIGNATURE.NS", name: "Signatureglobal (India)", sector: "Real Estate", indices: ["NIFTY500"] },
  { symbol: "SOBHA.NS", name: "Sobha", sector: "Real Estate", indices: ["NIFTY500"] },
  { symbol: "SOLARINDS.NS", name: "Solar Industries India", sector: "Chemicals", indices: ["NIFTY500"] },
  { symbol: "SONACOMS.NS", name: "Sona BLW Precision Forgings", sector: "Auto", indices: ["NIFTY500"] },
  { symbol: "SONATSOFTW.NS", name: "Sonata Software", sector: "IT", indices: ["NIFTY500"] },
  { symbol: "STARHEALTH.NS", name: "Star Health and Allied Insurance Company", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "SUMICHEM.NS", name: "Sumitomo Chemical India", sector: "Chemicals", indices: ["NIFTY500"] },
  { symbol: "SUNTV.NS", name: "Sun TV Network", sector: "Media", indices: ["NIFTY500"] },
  { symbol: "SUNDARMFIN.NS", name: "Sundaram Finance", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "SUPREMEIND.NS", name: "Supreme Industries", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "SPLPETRO.NS", name: "Supreme Petrochem", sector: "Chemicals", indices: ["NIFTY500"] },
  { symbol: "SUZLON.NS", name: "Suzlon Energy", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "SWANCORP.NS", name: "Swan Corp", sector: "Chemicals", indices: ["NIFTY500"] },
  { symbol: "SWIGGY.NS", name: "Swiggy", sector: "Consumer", indices: ["NIFTY500"] },
  { symbol: "SYNGENE.NS", name: "Syngene International", sector: "Pharma", indices: ["NIFTY500"] },
  { symbol: "SYRMA.NS", name: "Syrma SGS Technology", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "TBOTEK.NS", name: "TBO Tek", sector: "Consumer", indices: ["NIFTY500"] },
  { symbol: "TATACAP.NS", name: "Tata Capital", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "TATACHEM.NS", name: "Tata Chemicals", sector: "Chemicals", indices: ["NIFTY500"] },
  { symbol: "TATACOMM.NS", name: "Tata Communications", sector: "Telecom", indices: ["NIFTY500"] },
  { symbol: "TATAINVEST.NS", name: "Tata Investment Corporation", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "TMCV.NS", name: "Tata Motors", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "TMPV.NS", name: "Tata Motors Passenger Vehicles", sector: "Auto", indices: ["NIFTY500"] },
  { symbol: "TATATECH.NS", name: "Tata Technologies", sector: "IT", indices: ["NIFTY500"] },
  { symbol: "TTML.NS", name: "Tata Teleservices (Maharashtra)", sector: "Telecom", indices: ["NIFTY500"] },
  { symbol: "TECHNOE.NS", name: "Techno Electric & Engineering Company", sector: "Construction", indices: ["NIFTY500"] },
  { symbol: "TEGA.NS", name: "Tega Industries", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "TEJASNET.NS", name: "Tejas Networks", sector: "Telecom", indices: ["NIFTY500"] },
  { symbol: "TENNIND.NS", name: "Tenneco Clean Air India", sector: "Auto", indices: ["NIFTY500"] },
  { symbol: "NIACL.NS", name: "The New India Assurance Company", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "RAMCOCEM.NS", name: "The Ramco Cements", sector: "Cement", indices: ["NIFTY500"] },
  { symbol: "THERMAX.NS", name: "Thermax", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "TIMKEN.NS", name: "Timken India", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "TITAGARH.NS", name: "Titagarh Rail Systems", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "TORNTPOWER.NS", name: "Torrent Power", sector: "Power", indices: ["NIFTY500"] },
  { symbol: "TARIL.NS", name: "Transformers And Rectifiers (India)", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "TRAVELFOOD.NS", name: "Travel Food Services", sector: "Consumer", indices: ["NIFTY500"] },
  { symbol: "TRIDENT.NS", name: "Trident", sector: "Textiles", indices: ["NIFTY500"] },
  { symbol: "TRITURBINE.NS", name: "Triveni Turbine", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "TIINDIA.NS", name: "Tube Investments of India", sector: "Auto", indices: ["NIFTY500"] },
  { symbol: "UCOBANK.NS", name: "UCO Bank", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "UNOMINDA.NS", name: "UNO Minda", sector: "Auto", indices: ["NIFTY500"] },
  { symbol: "UTIAMC.NS", name: "UTI Asset Management Company", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "UBL.NS", name: "United Breweries", sector: "FMCG", indices: ["NIFTY500"] },
  { symbol: "UNITDSPR.NS", name: "United Spirits", sector: "FMCG", indices: ["NIFTY500"] },
  { symbol: "URBANCO.NS", name: "Urban Company", sector: "Consumer", indices: ["NIFTY500"] },
  { symbol: "USHAMART.NS", name: "Usha Martin", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "VTL.NS", name: "Vardhman Textiles", sector: "Textiles", indices: ["NIFTY500"] },
  { symbol: "VBL.NS", name: "Varun Beverages", sector: "FMCG", indices: ["NIFTY500"] },
  { symbol: "VIJAYA.NS", name: "Vijaya Diagnostic Centre", sector: "Pharma", indices: ["NIFTY500"] },
  { symbol: "VMM.NS", name: "Vishal Mega Mart", sector: "Consumer", indices: ["NIFTY500"] },
  { symbol: "IDEA.NS", name: "Vodafone Idea", sector: "Telecom", indices: ["NIFTY500"] },
  { symbol: "VOLTAS.NS", name: "Voltas", sector: "Consumer", indices: ["NIFTY500"] },
  { symbol: "WAAREEENER.NS", name: "Waaree Energies", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "WELCORP.NS", name: "Welspun Corp", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "WELSPUNLIV.NS", name: "Welspun Living", sector: "Textiles", indices: ["NIFTY500"] },
  { symbol: "WHIRLPOOL.NS", name: "Whirlpool of India", sector: "Consumer", indices: ["NIFTY500"] },
  { symbol: "WOCKPHARMA.NS", name: "Wockhardt", sector: "Pharma", indices: ["NIFTY500"] },
  { symbol: "YESBANK.NS", name: "Yes Bank", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "ZFCVINDIA.NS", name: "ZF Commercial Vehicle Control Systems India", sector: "Auto", indices: ["NIFTY500"] },
  { symbol: "ZEEL.NS", name: "Zee Entertainment Enterprises", sector: "Media", indices: ["NIFTY500"] },
  { symbol: "ZENTEC.NS", name: "Zen Technologies", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "ZENSARTECH.NS", name: "Zensar Technolgies", sector: "IT", indices: ["NIFTY500"] },
  { symbol: "ZYDUSWELL.NS", name: "Zydus Wellness", sector: "FMCG", indices: ["NIFTY500"] },
  { symbol: "ECLERX.NS", name: "eClerx Services", sector: "Services", indices: ["NIFTY500"] },
];

// Deduplicate defensively (in case of accidental duplicates)
const uniqueMap = new Map();
for (const s of ALL_STOCKS) {
  if (!uniqueMap.has(s.symbol)) uniqueMap.set(s.symbol, s);
}
const DEDUPED = Array.from(uniqueMap.values());

// Nifty 500 membership set — generated from NSE's ind_nifty500list.csv
// (Apr 2026). Used by getNifty500() to include existing Nifty 100 entries
// whose `indices` arrays don't explicitly carry the NIFTY500 tag. When
// NSE rebalances, regenerate via: node scripts/build-nifty500.mjs
const NIFTY500_SYMBOLS = new Set([
  "360ONE.NS",
  "3MINDIA.NS",
  "ABB.NS",
  "ACC.NS",
  "ACMESOLAR.NS",
  "AIAENG.NS",
  "APLAPOLLO.NS",
  "AUBANK.NS",
  "AWL.NS",
  "AADHARHFC.NS",
  "AARTIIND.NS",
  "AAVAS.NS",
  "ABBOTINDIA.NS",
  "ACE.NS",
  "ACUTAAS.NS",
  "ADANIENSOL.NS",
  "ADANIENT.NS",
  "ADANIGREEN.NS",
  "ADANIPORTS.NS",
  "ADANIPOWER.NS",
  "ATGL.NS",
  "ABCAPITAL.NS",
  "ABFRL.NS",
  "ABLBL.NS",
  "ABREL.NS",
  "ABSLAMC.NS",
  "CPPLUS.NS",
  "AEGISLOG.NS",
  "AEGISVOPAK.NS",
  "AFCONS.NS",
  "AFFLE.NS",
  "AJANTPHARM.NS",
  "ALKEM.NS",
  "ABDL.NS",
  "ARE&M.NS",
  "AMBER.NS",
  "AMBUJACEM.NS",
  "ANANDRATHI.NS",
  "ANANTRAJ.NS",
  "ANGELONE.NS",
  "ANTHEM.NS",
  "ANURAS.NS",
  "APARINDS.NS",
  "APOLLOHOSP.NS",
  "APOLLOTYRE.NS",
  "APTUS.NS",
  "ASAHIINDIA.NS",
  "ASHOKLEY.NS",
  "ASIANPAINT.NS",
  "ASTERDM.NS",
  "ASTRAL.NS",
  "ATHERENERG.NS",
  "ATUL.NS",
  "AUROPHARMA.NS",
  "AIIL.NS",
  "DMART.NS",
  "AXISBANK.NS",
  "BEML.NS",
  "BLS.NS",
  "BSE.NS",
  "BAJAJ-AUTO.NS",
  "BAJFINANCE.NS",
  "BAJAJFINSV.NS",
  "BAJAJHLDNG.NS",
  "BAJAJHFL.NS",
  "BALKRISIND.NS",
  "BALRAMCHIN.NS",
  "BANDHANBNK.NS",
  "BANKBARODA.NS",
  "BANKINDIA.NS",
  "MAHABANK.NS",
  "BATAINDIA.NS",
  "BAYERCROP.NS",
  "BELRISE.NS",
  "BERGEPAINT.NS",
  "BDL.NS",
  "BEL.NS",
  "BHARATFORG.NS",
  "BHEL.NS",
  "BPCL.NS",
  "BHARTIARTL.NS",
  "BHARTIHEXA.NS",
  "BIKAJI.NS",
  "GROWW.NS",
  "BIOCON.NS",
  "BSOFT.NS",
  "BLUEDART.NS",
  "BLUEJET.NS",
  "BLUESTARCO.NS",
  "BBTC.NS",
  "BOSCHLTD.NS",
  "FIRSTCRY.NS",
  "BRIGADE.NS",
  "BRITANNIA.NS",
  "MAPMYINDIA.NS",
  "CCL.NS",
  "CESC.NS",
  "CGPOWER.NS",
  "CRISIL.NS",
  "CANFINHOME.NS",
  "CANBK.NS",
  "CANHLIFE.NS",
  "CAPLIPOINT.NS",
  "CGCL.NS",
  "CARBORUNIV.NS",
  "CARTRADE.NS",
  "CASTROLIND.NS",
  "CEATLTD.NS",
  "CEMPRO.NS",
  "CENTRALBK.NS",
  "CDSL.NS",
  "CHALET.NS",
  "CHAMBLFERT.NS",
  "CHENNPETRO.NS",
  "CHOICEIN.NS",
  "CHOLAHLDNG.NS",
  "CHOLAFIN.NS",
  "CIPLA.NS",
  "CUB.NS",
  "CLEAN.NS",
  "COALINDIA.NS",
  "COCHINSHIP.NS",
  "COFORGE.NS",
  "COHANCE.NS",
  "COLPAL.NS",
  "CAMS.NS",
  "CONCORDBIO.NS",
  "CONCOR.NS",
  "COROMANDEL.NS",
  "CRAFTSMAN.NS",
  "CREDITACC.NS",
  "CROMPTON.NS",
  "CUMMINSIND.NS",
  "CYIENT.NS",
  "DCMSHRIRAM.NS",
  "DLF.NS",
  "DOMS.NS",
  "DABUR.NS",
  "DALBHARAT.NS",
  "DATAPATTNS.NS",
  "DEEPAKFERT.NS",
  "DEEPAKNTR.NS",
  "DELHIVERY.NS",
  "DEVYANI.NS",
  "DIVISLAB.NS",
  "DIXON.NS",
  "LALPATHLAB.NS",
  "DRREDDY.NS",
  "EIDPARRY.NS",
  "EIHOTEL.NS",
  "EICHERMOT.NS",
  "ELECON.NS",
  "ELGIEQUIP.NS",
  "EMAMILTD.NS",
  "EMCURE.NS",
  "EMMVEE.NS",
  "ENDURANCE.NS",
  "ENGINERSIN.NS",
  "ERIS.NS",
  "ESCORTS.NS",
  "ETERNAL.NS",
  "EXIDEIND.NS",
  "NYKAA.NS",
  "FEDERALBNK.NS",
  "FACT.NS",
  "FINCABLES.NS",
  "FSL.NS",
  "FIVESTAR.NS",
  "FORCEMOT.NS",
  "FORTIS.NS",
  "GAIL.NS",
  "GVT&D.NS",
  "GMRAIRPORT.NS",
  "GABRIEL.NS",
  "GALLANTT.NS",
  "GRSE.NS",
  "GICRE.NS",
  "GILLETTE.NS",
  "GLAND.NS",
  "GLAXO.NS",
  "GLENMARK.NS",
  "MEDANTA.NS",
  "GODIGIT.NS",
  "GPIL.NS",
  "GODFRYPHLP.NS",
  "GODREJCP.NS",
  "GODREJIND.NS",
  "GODREJPROP.NS",
  "GRANULES.NS",
  "GRAPHITE.NS",
  "GRASIM.NS",
  "GRAVITA.NS",
  "GESHIP.NS",
  "FLUOROCHEM.NS",
  "GMDCLTD.NS",
  "GSPL.NS",
  "HEG.NS",
  "HBLENGINE.NS",
  "HCLTECH.NS",
  "HDBFS.NS",
  "HDFCAMC.NS",
  "HDFCBANK.NS",
  "HDFCLIFE.NS",
  "HFCL.NS",
  "HAVELLS.NS",
  "HEROMOTOCO.NS",
  "HEXT.NS",
  "HSCL.NS",
  "HINDALCO.NS",
  "HAL.NS",
  "HINDCOPPER.NS",
  "HINDPETRO.NS",
  "HINDUNILVR.NS",
  "HINDZINC.NS",
  "POWERINDIA.NS",
  "HOMEFIRST.NS",
  "HONASA.NS",
  "HONAUT.NS",
  "HUDCO.NS",
  "HYUNDAI.NS",
  "ICICIBANK.NS",
  "ICICIGI.NS",
  "ICICIAMC.NS",
  "ICICIPRULI.NS",
  "IDBI.NS",
  "IDFCFIRSTB.NS",
  "IFCI.NS",
  "IIFL.NS",
  "IRB.NS",
  "IRCON.NS",
  "ITCHOTELS.NS",
  "ITC.NS",
  "ITI.NS",
  "INDGN.NS",
  "INDIACEM.NS",
  "INDIAMART.NS",
  "INDIANB.NS",
  "IEX.NS",
  "INDHOTEL.NS",
  "IOC.NS",
  "IOB.NS",
  "IRCTC.NS",
  "IRFC.NS",
  "IREDA.NS",
  "IGL.NS",
  "INDUSTOWER.NS",
  "INDUSINDBK.NS",
  "NAUKRI.NS",
  "INFY.NS",
  "INOXWIND.NS",
  "INTELLECT.NS",
  "INDIGO.NS",
  "IGIL.NS",
  "IKS.NS",
  "IPCALAB.NS",
  "JBCHEPHARM.NS",
  "JKCEMENT.NS",
  "JBMA.NS",
  "JKTYRE.NS",
  "JMFINANCIL.NS",
  "JSWCEMENT.NS",
  "JSWDULUX.NS",
  "JSWENERGY.NS",
  "JSWINFRA.NS",
  "JSWSTEEL.NS",
  "JAINREC.NS",
  "JPPOWER.NS",
  "J&KBANK.NS",
  "JINDALSAW.NS",
  "JSL.NS",
  "JINDALSTEL.NS",
  "JIOFIN.NS",
  "JUBLFOOD.NS",
  "JUBLINGREA.NS",
  "JUBLPHARMA.NS",
  "JWL.NS",
  "JYOTICNC.NS",
  "KPRMILL.NS",
  "KEI.NS",
  "KPITTECH.NS",
  "KAJARIACER.NS",
  "KPIL.NS",
  "KALYANKJIL.NS",
  "KARURVYSYA.NS",
  "KAYNES.NS",
  "KEC.NS",
  "KFINTECH.NS",
  "KIRLOSENG.NS",
  "KOTAKBANK.NS",
  "KIMS.NS",
  "LTF.NS",
  "LTTS.NS",
  "LGEINDIA.NS",
  "LICHSGFIN.NS",
  "LTFOODS.NS",
  "LTM.NS",
  "LT.NS",
  "LATENTVIEW.NS",
  "LAURUSLABS.NS",
  "THELEELA.NS",
  "LEMONTREE.NS",
  "LENSKART.NS",
  "LICI.NS",
  "LINDEINDIA.NS",
  "LLOYDSME.NS",
  "LODHA.NS",
  "LUPIN.NS",
  "MMTC.NS",
  "MRF.NS",
  "MGL.NS",
  "M&MFIN.NS",
  "M&M.NS",
  "MANAPPURAM.NS",
  "MRPL.NS",
  "MANKIND.NS",
  "MARICO.NS",
  "MARUTI.NS",
  "MFSL.NS",
  "MAXHEALTH.NS",
  "MAZDOCK.NS",
  "MEESHO.NS",
  "MINDACORP.NS",
  "MSUMI.NS",
  "MOTILALOFS.NS",
  "MPHASIS.NS",
  "MCX.NS",
  "MUTHOOTFIN.NS",
  "NATCOPHARM.NS",
  "NBCC.NS",
  "NCC.NS",
  "NHPC.NS",
  "NLCINDIA.NS",
  "NMDC.NS",
  "NSLNISP.NS",
  "NTPCGREEN.NS",
  "NTPC.NS",
  "NH.NS",
  "NATIONALUM.NS",
  "NAVA.NS",
  "NAVINFLUOR.NS",
  "NESTLEIND.NS",
  "NETWEB.NS",
  "NEULANDLAB.NS",
  "NEWGEN.NS",
  "NAM-INDIA.NS",
  "NIVABUPA.NS",
  "NUVAMA.NS",
  "NUVOCO.NS",
  "OBEROIRLTY.NS",
  "ONGC.NS",
  "OIL.NS",
  "OLAELEC.NS",
  "OLECTRA.NS",
  "PAYTM.NS",
  "ONESOURCE.NS",
  "OFSS.NS",
  "POLICYBZR.NS",
  "PCBL.NS",
  "PGEL.NS",
  "PIIND.NS",
  "PNBHOUSING.NS",
  "PTCIL.NS",
  "PVRINOX.NS",
  "PAGEIND.NS",
  "PARADEEP.NS",
  "PATANJALI.NS",
  "PERSISTENT.NS",
  "PETRONET.NS",
  "PFIZER.NS",
  "PHOENIXLTD.NS",
  "PWL.NS",
  "PIDILITIND.NS",
  "PINELABS.NS",
  "PIRAMALFIN.NS",
  "PPLPHARMA.NS",
  "POLYMED.NS",
  "POLYCAB.NS",
  "POONAWALLA.NS",
  "PFC.NS",
  "POWERGRID.NS",
  "PREMIERENE.NS",
  "PRESTIGE.NS",
  "PNB.NS",
  "RRKABEL.NS",
  "RBLBANK.NS",
  "RECLTD.NS",
  "RHIM.NS",
  "RITES.NS",
  "RADICO.NS",
  "RVNL.NS",
  "RAILTEL.NS",
  "RAINBOW.NS",
  "RKFORGE.NS",
  "REDINGTON.NS",
  "RELIANCE.NS",
  "RPOWER.NS",
  "SBFC.NS",
  "SBICARD.NS",
  "SBILIFE.NS",
  "SJVN.NS",
  "SRF.NS",
  "SAGILITY.NS",
  "SAILIFE.NS",
  "SAMMAANCAP.NS",
  "MOTHERSON.NS",
  "SAPPHIRE.NS",
  "SARDAEN.NS",
  "SAREGAMA.NS",
  "SCHAEFFLER.NS",
  "SCHNEIDER.NS",
  "SCI.NS",
  "SHREECEM.NS",
  "SHRIRAMFIN.NS",
  "SHYAMMETL.NS",
  "ENRIN.NS",
  "SIEMENS.NS",
  "SIGNATURE.NS",
  "SOBHA.NS",
  "SOLARINDS.NS",
  "SONACOMS.NS",
  "SONATSOFTW.NS",
  "STARHEALTH.NS",
  "SBIN.NS",
  "SAIL.NS",
  "SUMICHEM.NS",
  "SUNPHARMA.NS",
  "SUNTV.NS",
  "SUNDARMFIN.NS",
  "SUPREMEIND.NS",
  "SPLPETRO.NS",
  "SUZLON.NS",
  "SWANCORP.NS",
  "SWIGGY.NS",
  "SYNGENE.NS",
  "SYRMA.NS",
  "TBOTEK.NS",
  "TVSMOTOR.NS",
  "TATACAP.NS",
  "TATACHEM.NS",
  "TATACOMM.NS",
  "TCS.NS",
  "TATACONSUM.NS",
  "TATAELXSI.NS",
  "TATAINVEST.NS",
  "TMCV.NS",
  "TMPV.NS",
  "TATAPOWER.NS",
  "TATASTEEL.NS",
  "TATATECH.NS",
  "TTML.NS",
  "TECHM.NS",
  "TECHNOE.NS",
  "TEGA.NS",
  "TEJASNET.NS",
  "TENNIND.NS",
  "NIACL.NS",
  "RAMCOCEM.NS",
  "THERMAX.NS",
  "TIMKEN.NS",
  "TITAGARH.NS",
  "TITAN.NS",
  "TORNTPHARM.NS",
  "TORNTPOWER.NS",
  "TARIL.NS",
  "TRAVELFOOD.NS",
  "TRENT.NS",
  "TRIDENT.NS",
  "TRITURBINE.NS",
  "TIINDIA.NS",
  "UCOBANK.NS",
  "UNOMINDA.NS",
  "UPL.NS",
  "UTIAMC.NS",
  "ULTRACEMCO.NS",
  "UNIONBANK.NS",
  "UBL.NS",
  "UNITDSPR.NS",
  "URBANCO.NS",
  "USHAMART.NS",
  "VTL.NS",
  "VBL.NS",
  "VEDL.NS",
  "VIJAYA.NS",
  "VMM.NS",
  "IDEA.NS",
  "VOLTAS.NS",
  "WAAREEENER.NS",
  "WELCORP.NS",
  "WELSPUNLIV.NS",
  "WHIRLPOOL.NS",
  "WIPRO.NS",
  "WOCKPHARMA.NS",
  "YESBANK.NS",
  "ZFCVINDIA.NS",
  "ZEEL.NS",
  "ZENTEC.NS",
  "ZENSARTECH.NS",
  "ZYDUSLIFE.NS",
  "ZYDUSWELL.NS",
  "ECLERX.NS",
]);

// Build index-specific slices
function getStocksByIndex(indexTag) {
  return DEDUPED.filter((s) => s.indices.includes(indexTag));
}

function getAllStocks() {
  return DEDUPED;
}

// Nifty 100 = Nifty 50 + Nifty Next 50
function getNifty100() {
  return DEDUPED.filter((s) => s.indices.includes("NIFTY50") || s.indices.includes("NIFTY_NEXT_50"));
}

// Nifty 500 = any entry tagged NIFTY500, NIFTY50, NIFTY_NEXT_50, or in the
// NIFTY500_SYMBOLS set (covers existing Nifty 100 stocks whose `indices`
// arrays aren't explicitly tagged with "NIFTY500"). Phase 2: universe
// expansion from 116 → ~500 stocks for scanner coverage.
function getNifty500() {
  return DEDUPED.filter((s) =>
    s.indices.includes("NIFTY500") ||
    s.indices.includes("NIFTY50") ||
    s.indices.includes("NIFTY_NEXT_50") ||
    NIFTY500_SYMBOLS.has(s.symbol),
  );
}

// Phase 2 liquidity filter (applied downstream by scanner after fetching
// quotes). A stock must have 30-day median turnover ≥ ₹5 cr/day to enter
// scanner output — below that, SL/target orders can't reliably fill and
// recommendations become unexecutable.
const LIQUIDITY_MIN_TURNOVER_CR = 5;
function passesLiquidityFilter(medianTurnoverCrPerDay) {
  if (medianTurnoverCrPerDay == null || !Number.isFinite(medianTurnoverCrPerDay)) return true; // assume ok if unknown
  return medianTurnoverCrPerDay >= LIQUIDITY_MIN_TURNOVER_CR;
}

// Validate list — returns issues found. Called at server startup.
function validateStockList() {
  const issues = { duplicates: [], invalid: [] };
  const seen = new Set();
  const validPattern = /^[A-Z0-9&-]+\.(NS|BO)$/;

  for (const s of ALL_STOCKS) {
    if (seen.has(s.symbol)) issues.duplicates.push(s.symbol);
    seen.add(s.symbol);
    if (!validPattern.test(s.symbol)) {
      issues.invalid.push(s.symbol);
    }
  }
  return issues;
}

// Back-compat named exports for anything still importing old names
const NIFTY_50 = DEDUPED.filter((s) => s.indices.includes("NIFTY50"));
const NIFTY_NEXT_50 = DEDUPED.filter((s) => s.indices.includes("NIFTY_NEXT_50"));
const POPULAR_MIDCAPS = DEDUPED.filter((s) => s.indices.includes("MIDCAP"));

export {
  NIFTY_50,
  NIFTY_NEXT_50,
  POPULAR_MIDCAPS,
  DEDUPED as ALL_STOCKS,
  NIFTY500_SYMBOLS,
  getStocksByIndex,
  getAllStocks,
  getNifty100,
  getNifty500,
  passesLiquidityFilter,
  LIQUIDITY_MIN_TURNOVER_CR,
  validateStockList,
};
