// Flat stock universe with index tagging.
//
// Each entry: { symbol, isin, name, sector, indices: string[] }
// Index tags: "NIFTY50", "NIFTY_NEXT_50", "NIFTY100" (derived), "MIDCAP", "NIFTY500"
//
// `isin` added Phase 5 so portfolio-upload flows can match holdings by
// ISIN (authoritative per broker exports) rather than by ticker or name.
// Auto-populated from NSE ind_nifty500list.csv via scripts/enrich-isins.mjs.

const ALL_STOCKS = [
  // ========== NIFTY 50 ==========
  { symbol: "RELIANCE.NS", isin: "INE002A01018", name: "Reliance Industries", sector: "Energy", indices: ["NIFTY50"] },
  { symbol: "TCS.NS", isin: "INE467B01029", name: "Tata Consultancy Services", sector: "IT", indices: ["NIFTY50"] },
  { symbol: "HDFCBANK.NS", isin: "INE040A01034", name: "HDFC Bank", sector: "Banking", indices: ["NIFTY50"] },
  { symbol: "INFY.NS", isin: "INE009A01021", name: "Infosys", sector: "IT", indices: ["NIFTY50"] },
  { symbol: "ICICIBANK.NS", isin: "INE090A01021", name: "ICICI Bank", sector: "Banking", indices: ["NIFTY50"] },
  { symbol: "HINDUNILVR.NS", isin: "INE030A01027", name: "Hindustan Unilever", sector: "FMCG", indices: ["NIFTY50"] },
  { symbol: "ITC.NS", isin: "INE154A01025", name: "ITC", sector: "FMCG", indices: ["NIFTY50"] },
  { symbol: "SBIN.NS", isin: "INE062A01020", name: "State Bank of India", sector: "Banking", indices: ["NIFTY50"] },
  { symbol: "BHARTIARTL.NS", isin: "INE397D01024", name: "Bharti Airtel", sector: "Telecom", indices: ["NIFTY50"] },
  { symbol: "KOTAKBANK.NS", isin: "INE237A01036", name: "Kotak Mahindra Bank", sector: "Banking", indices: ["NIFTY50"] },
  { symbol: "LT.NS", isin: "INE018A01030", name: "Larsen & Toubro", sector: "Infrastructure", indices: ["NIFTY50"] },
  { symbol: "AXISBANK.NS", isin: "INE238A01034", name: "Axis Bank", sector: "Banking", indices: ["NIFTY50"] },
  { symbol: "WIPRO.NS", isin: "INE075A01022", name: "Wipro", sector: "IT", indices: ["NIFTY50"] },
  { symbol: "ASIANPAINT.NS", isin: "INE021A01026", name: "Asian Paints", sector: "Consumer", indices: ["NIFTY50"] },
  { symbol: "MARUTI.NS", isin: "INE585B01010", name: "Maruti Suzuki", sector: "Auto", indices: ["NIFTY50"] },
  { symbol: "HCLTECH.NS", isin: "INE860A01027", name: "HCL Technologies", sector: "IT", indices: ["NIFTY50"] },
  { symbol: "TITAN.NS", isin: "INE280A01028", name: "Titan Company", sector: "Consumer", indices: ["NIFTY50"] },
  { symbol: "SUNPHARMA.NS", isin: "INE044A01036", name: "Sun Pharma", sector: "Pharma", indices: ["NIFTY50"] },
  { symbol: "BAJFINANCE.NS", isin: "INE296A01032", name: "Bajaj Finance", sector: "Finance", indices: ["NIFTY50"] },
  { symbol: "ULTRACEMCO.NS", isin: "INE481G01011", name: "UltraTech Cement", sector: "Cement", indices: ["NIFTY50"] },
  { symbol: "NESTLEIND.NS", isin: "INE239A01024", name: "Nestle India", sector: "FMCG", indices: ["NIFTY50"] },
  { symbol: "TATAMOTORS.NS", name: "Tata Motors", sector: "Auto", indices: ["NIFTY50"] },
  { symbol: "NTPC.NS", isin: "INE733E01010", name: "NTPC", sector: "Power", indices: ["NIFTY50"] },
  { symbol: "POWERGRID.NS", isin: "INE752E01010", name: "Power Grid Corp", sector: "Power", indices: ["NIFTY50"] },
  { symbol: "M&M.NS", isin: "INE101A01026", name: "Mahindra & Mahindra", sector: "Auto", indices: ["NIFTY50"] },
  { symbol: "TATASTEEL.NS", isin: "INE081A01020", name: "Tata Steel", sector: "Metals", indices: ["NIFTY50"] },
  { symbol: "ONGC.NS", isin: "INE213A01029", name: "ONGC", sector: "Energy", indices: ["NIFTY50"] },
  { symbol: "JSWSTEEL.NS", isin: "INE019A01038", name: "JSW Steel", sector: "Metals", indices: ["NIFTY50"] },
  { symbol: "ADANIENT.NS", isin: "INE423A01024", name: "Adani Enterprises", sector: "Diversified", indices: ["NIFTY50"] },
  { symbol: "ADANIPORTS.NS", isin: "INE742F01042", name: "Adani Ports", sector: "Infrastructure", indices: ["NIFTY50"] },
  { symbol: "COALINDIA.NS", isin: "INE522F01014", name: "Coal India", sector: "Mining", indices: ["NIFTY50"] },
  { symbol: "BPCL.NS", isin: "INE029A01011", name: "BPCL", sector: "Energy", indices: ["NIFTY50"] },
  { symbol: "GRASIM.NS", isin: "INE047A01021", name: "Grasim Industries", sector: "Diversified", indices: ["NIFTY50"] },
  { symbol: "TECHM.NS", isin: "INE669C01036", name: "Tech Mahindra", sector: "IT", indices: ["NIFTY50"] },
  { symbol: "INDUSINDBK.NS", isin: "INE095A01012", name: "IndusInd Bank", sector: "Banking", indices: ["NIFTY50"] },
  { symbol: "HINDALCO.NS", isin: "INE038A01020", name: "Hindalco", sector: "Metals", indices: ["NIFTY50"] },
  { symbol: "DRREDDY.NS", isin: "INE089A01031", name: "Dr Reddy's Labs", sector: "Pharma", indices: ["NIFTY50"] },
  { symbol: "CIPLA.NS", isin: "INE059A01026", name: "Cipla", sector: "Pharma", indices: ["NIFTY50"] },
  { symbol: "DIVISLAB.NS", isin: "INE361B01024", name: "Divi's Laboratories", sector: "Pharma", indices: ["NIFTY50"] },
  { symbol: "EICHERMOT.NS", isin: "INE066A01021", name: "Eicher Motors", sector: "Auto", indices: ["NIFTY50"] },
  { symbol: "BAJAJFINSV.NS", isin: "INE918I01026", name: "Bajaj Finserv", sector: "Finance", indices: ["NIFTY50"] },
  { symbol: "BRITANNIA.NS", isin: "INE216A01030", name: "Britannia Industries", sector: "FMCG", indices: ["NIFTY50"] },
  { symbol: "HEROMOTOCO.NS", isin: "INE158A01026", name: "Hero MotoCorp", sector: "Auto", indices: ["NIFTY50"] },
  { symbol: "APOLLOHOSP.NS", isin: "INE437A01024", name: "Apollo Hospitals", sector: "Healthcare", indices: ["NIFTY50"] },
  { symbol: "SBILIFE.NS", isin: "INE123W01016", name: "SBI Life Insurance", sector: "Insurance", indices: ["NIFTY50"] },
  { symbol: "HDFCLIFE.NS", isin: "INE795G01014", name: "HDFC Life Insurance", sector: "Insurance", indices: ["NIFTY50"] },
  { symbol: "TATACONSUM.NS", isin: "INE192A01025", name: "Tata Consumer Products", sector: "FMCG", indices: ["NIFTY50"] },
  { symbol: "BAJAJ-AUTO.NS", isin: "INE917I01010", name: "Bajaj Auto", sector: "Auto", indices: ["NIFTY50"] },
  { symbol: "UPL.NS", isin: "INE628A01036", name: "UPL", sector: "Chemicals", indices: ["NIFTY50"] },
  { symbol: "SHRIRAMFIN.NS", isin: "INE721A01047", name: "Shriram Finance", sector: "Finance", indices: ["NIFTY50"] },

  // ========== NIFTY NEXT 50 ==========
  { symbol: "LICI.NS", isin: "INE0J1Y01017", name: "Life Insurance Corp", sector: "Insurance", indices: ["NIFTY_NEXT_50"] },
  { symbol: "DMART.NS", isin: "INE192R01011", name: "Avenue Supermarts (DMart)", sector: "Retail", indices: ["NIFTY_NEXT_50"] },
  { symbol: "PIDILITIND.NS", isin: "INE318A01026", name: "Pidilite Industries", sector: "Chemicals", indices: ["NIFTY_NEXT_50"] },
  { symbol: "SIEMENS.NS", isin: "INE003A01024", name: "Siemens India", sector: "Capital Goods", indices: ["NIFTY_NEXT_50"] },
  { symbol: "ABB.NS", isin: "INE117A01022", name: "ABB India", sector: "Capital Goods", indices: ["NIFTY_NEXT_50"] },
  { symbol: "BOSCHLTD.NS", isin: "INE323A01026", name: "Bosch Ltd", sector: "Auto Components", indices: ["NIFTY_NEXT_50"] },
  { symbol: "HAVELLS.NS", isin: "INE176B01034", name: "Havells India", sector: "Consumer Durables", indices: ["NIFTY_NEXT_50"] },
  { symbol: "GODREJCP.NS", isin: "INE102D01028", name: "Godrej Consumer Products", sector: "FMCG", indices: ["NIFTY_NEXT_50"] },
  { symbol: "DABUR.NS", isin: "INE016A01026", name: "Dabur India", sector: "FMCG", indices: ["NIFTY_NEXT_50"] },
  { symbol: "MARICO.NS", isin: "INE196A01026", name: "Marico", sector: "FMCG", indices: ["NIFTY_NEXT_50"] },
  { symbol: "ICICIGI.NS", isin: "INE765G01017", name: "ICICI Lombard General Insurance", sector: "Insurance", indices: ["NIFTY_NEXT_50"] },
  { symbol: "ICICIPRULI.NS", isin: "INE726G01019", name: "ICICI Prudential Life", sector: "Insurance", indices: ["NIFTY_NEXT_50"] },
  { symbol: "LODHA.NS", isin: "INE670K01029", name: "Macrotech Developers (Lodha)", sector: "Real Estate", indices: ["NIFTY_NEXT_50"] },
  { symbol: "CHOLAFIN.NS", isin: "INE121A01024", name: "Cholamandalam Investment", sector: "Finance", indices: ["NIFTY_NEXT_50"] },
  { symbol: "JINDALSTEL.NS", isin: "INE749A01030", name: "Jindal Steel & Power", sector: "Metals", indices: ["NIFTY_NEXT_50"] },
  { symbol: "VEDL.NS", isin: "INE205A01025", name: "Vedanta", sector: "Mining", indices: ["NIFTY_NEXT_50"] },
  { symbol: "LTIM.NS", name: "LTIMindtree", sector: "IT", indices: ["NIFTY_NEXT_50"] },
  { symbol: "MPHASIS.NS", isin: "INE356A01018", name: "Mphasis", sector: "IT", indices: ["NIFTY_NEXT_50"] },
  { symbol: "OFSS.NS", isin: "INE881D01027", name: "Oracle Financial Services", sector: "IT", indices: ["NIFTY_NEXT_50"] },
  { symbol: "TATAPOWER.NS", isin: "INE245A01021", name: "Tata Power", sector: "Power", indices: ["NIFTY_NEXT_50"] },
  { symbol: "TORNTPHARM.NS", isin: "INE685A01028", name: "Torrent Pharma", sector: "Pharma", indices: ["NIFTY_NEXT_50"] },
  { symbol: "ZYDUSLIFE.NS", isin: "INE010B01027", name: "Zydus Lifesciences", sector: "Pharma", indices: ["NIFTY_NEXT_50"] },
  { symbol: "LUPIN.NS", isin: "INE326A01037", name: "Lupin", sector: "Pharma", indices: ["NIFTY_NEXT_50"] },
  { symbol: "APOLLOTYRE.NS", isin: "INE438A01022", name: "Apollo Tyres", sector: "Auto Components", indices: ["NIFTY_NEXT_50"] },
  { symbol: "TVSMOTOR.NS", isin: "INE494B01023", name: "TVS Motor", sector: "Auto", indices: ["NIFTY_NEXT_50"] },
  { symbol: "BAJAJHLDNG.NS", isin: "INE118A01012", name: "Bajaj Holdings", sector: "Finance", indices: ["NIFTY_NEXT_50"] },
  { symbol: "IOC.NS", isin: "INE242A01010", name: "Indian Oil Corp", sector: "Energy", indices: ["NIFTY_NEXT_50"] },
  { symbol: "HINDPETRO.NS", isin: "INE094A01015", name: "Hindustan Petroleum", sector: "Energy", indices: ["NIFTY_NEXT_50"] },
  { symbol: "GAIL.NS", isin: "INE129A01019", name: "GAIL India", sector: "Energy", indices: ["NIFTY_NEXT_50"] },
  { symbol: "HAL.NS", isin: "INE066F01020", name: "Hindustan Aeronautics", sector: "Defence", indices: ["NIFTY_NEXT_50"] },
  { symbol: "BEL.NS", isin: "INE263A01024", name: "Bharat Electronics", sector: "Defence", indices: ["NIFTY_NEXT_50"] },
  { symbol: "IRCTC.NS", isin: "INE335Y01020", name: "IRCTC", sector: "Tourism", indices: ["NIFTY_NEXT_50"] },
  { symbol: "TRENT.NS", isin: "INE849A01020", name: "Trent", sector: "Retail", indices: ["NIFTY_NEXT_50"] },
  { symbol: "INDIGO.NS", isin: "INE646L01027", name: "InterGlobe Aviation (IndiGo)", sector: "Airlines", indices: ["NIFTY_NEXT_50"] },
  { symbol: "ADANIGREEN.NS", isin: "INE364U01010", name: "Adani Green Energy", sector: "Renewable Energy", indices: ["NIFTY_NEXT_50"] },
  { symbol: "ADANIPOWER.NS", isin: "INE814H01029", name: "Adani Power", sector: "Power", indices: ["NIFTY_NEXT_50"] },
  { symbol: "AMBUJACEM.NS", isin: "INE079A01024", name: "Ambuja Cements", sector: "Cement", indices: ["NIFTY_NEXT_50"] },
  { symbol: "ACC.NS", isin: "INE012A01025", name: "ACC", sector: "Cement", indices: ["NIFTY_NEXT_50"] },
  { symbol: "BANKBARODA.NS", isin: "INE028A01039", name: "Bank of Baroda", sector: "Banking", indices: ["NIFTY_NEXT_50"] },
  { symbol: "PNB.NS", isin: "INE160A01022", name: "Punjab National Bank", sector: "Banking", indices: ["NIFTY_NEXT_50"] },
  { symbol: "CANBK.NS", isin: "INE476A01022", name: "Canara Bank", sector: "Banking", indices: ["NIFTY_NEXT_50"] },
  { symbol: "UNIONBANK.NS", isin: "INE692A01016", name: "Union Bank of India", sector: "Banking", indices: ["NIFTY_NEXT_50"] },
  { symbol: "INDHOTEL.NS", isin: "INE053A01029", name: "Indian Hotels (Taj)", sector: "Hospitality", indices: ["NIFTY_NEXT_50"] },
  { symbol: "DLF.NS", isin: "INE271C01023", name: "DLF", sector: "Real Estate", indices: ["NIFTY_NEXT_50"] },
  { symbol: "NAUKRI.NS", isin: "INE663F01032", name: "Info Edge (Naukri)", sector: "Internet", indices: ["NIFTY_NEXT_50"] },
  { symbol: "PFC.NS", isin: "INE134E01011", name: "Power Finance Corp", sector: "Finance", indices: ["NIFTY_NEXT_50"] },
  { symbol: "RECLTD.NS", isin: "INE020B01018", name: "REC Limited", sector: "Finance", indices: ["NIFTY_NEXT_50"] },
  { symbol: "IRFC.NS", isin: "INE053F01010", name: "IRFC", sector: "Finance", indices: ["NIFTY_NEXT_50"] },
  { symbol: "CGPOWER.NS", isin: "INE067A01029", name: "CG Power & Industrial", sector: "Capital Goods", indices: ["NIFTY_NEXT_50"] },
  { symbol: "JSWENERGY.NS", isin: "INE121E01018", name: "JSW Energy", sector: "Power", indices: ["NIFTY_NEXT_50"] },

  // ========== POPULAR MIDCAPS / MICROCAPS ==========
  { symbol: "ZOMATO.NS", name: "Zomato", sector: "Internet", indices: ["MIDCAP"] },
  { symbol: "PAYTM.NS", isin: "INE982J01020", name: "Paytm (One97)", sector: "Fintech", indices: ["MIDCAP"] },
  { symbol: "NYKAA.NS", isin: "INE388Y01029", name: "Nykaa (FSN E-Comm)", sector: "E-Commerce", indices: ["MIDCAP"] },
  { symbol: "POLYCAB.NS", isin: "INE455K01017", name: "Polycab India", sector: "Electricals", indices: ["MIDCAP"] },
  { symbol: "PIIND.NS", isin: "INE603J01030", name: "PI Industries", sector: "Chemicals", indices: ["MIDCAP"] },
  { symbol: "MUTHOOTFIN.NS", isin: "INE414G01012", name: "Muthoot Finance", sector: "Finance", indices: ["MIDCAP"] },
  { symbol: "JUBLFOOD.NS", isin: "INE797F01020", name: "Jubilant FoodWorks", sector: "QSR", indices: ["MIDCAP"] },
  { symbol: "DIXON.NS", isin: "INE935N01020", name: "Dixon Technologies", sector: "Electronics", indices: ["MIDCAP"] },
  { symbol: "PERSISTENT.NS", isin: "INE262H01021", name: "Persistent Systems", sector: "IT", indices: ["MIDCAP"] },
  { symbol: "COFORGE.NS", isin: "INE591G01025", name: "Coforge", sector: "IT", indices: ["MIDCAP"] },
  { symbol: "TATAELXSI.NS", isin: "INE670A01012", name: "Tata Elxsi", sector: "IT", indices: ["MIDCAP"] },
  { symbol: "FEDERALBNK.NS", isin: "INE171A01029", name: "Federal Bank", sector: "Banking", indices: ["MIDCAP"] },
  { symbol: "IDFCFIRSTB.NS", isin: "INE092T01019", name: "IDFC First Bank", sector: "Banking", indices: ["MIDCAP"] },
  { symbol: "SAIL.NS", isin: "INE114A01011", name: "SAIL", sector: "Metals", indices: ["MIDCAP"] },
  { symbol: "NHPC.NS", isin: "INE848E01016", name: "NHPC", sector: "Power", indices: ["MIDCAP"] },
  { symbol: "JIOFIN.NS", isin: "INE758E01017", name: "Jio Financial Services", sector: "Finance", indices: ["MIDCAP"] },

  // ========== NIFTY 500 (auto-generated from NSE Apr 2026) ==========
  { symbol: "ACMESOLAR.NS", isin: "INE622W01025", name: "ACME Solar Holdings", sector: "Power", indices: ["NIFTY500"] },
  { symbol: "AIAENG.NS", isin: "INE212H01026", name: "AIA Engineering", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "APLAPOLLO.NS", isin: "INE702C01027", name: "APL Apollo Tubes", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "AUBANK.NS", isin: "INE949L01017", name: "AU Small Finance Bank", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "AWL.NS", isin: "INE699H01024", name: "AWL Agri Business", sector: "FMCG", indices: ["NIFTY500"] },
  { symbol: "AADHARHFC.NS", isin: "INE883F01010", name: "Aadhar Housing Finance", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "AARTIIND.NS", isin: "INE769A01020", name: "Aarti Industries", sector: "Chemicals", indices: ["NIFTY500"] },
  { symbol: "AAVAS.NS", isin: "INE216P01012", name: "Aavas Financiers", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "ABBOTINDIA.NS", isin: "INE358A01014", name: "Abbott India", sector: "Pharma", indices: ["NIFTY500"] },
  { symbol: "ACE.NS", isin: "INE731H01025", name: "Action Construction Equipment", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "ACUTAAS.NS", isin: "INE00FF01025", name: "Acutaas Chemicals", sector: "Pharma", indices: ["NIFTY500"] },
  { symbol: "ADANIENSOL.NS", isin: "INE931S01010", name: "Adani Energy Solutions", sector: "Power", indices: ["NIFTY500"] },
  { symbol: "ATGL.NS", isin: "INE399L01023", name: "Adani Total Gas", sector: "Energy", indices: ["NIFTY500"] },
  { symbol: "ABCAPITAL.NS", isin: "INE674K01013", name: "Aditya Birla Capital", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "ABFRL.NS", isin: "INE647O01011", name: "Aditya Birla Fashion and Retail", sector: "Consumer", indices: ["NIFTY500"] },
  { symbol: "ABLBL.NS", isin: "INE14LE01019", name: "Aditya Birla Lifestyle Brands", sector: "Consumer", indices: ["NIFTY500"] },
  { symbol: "ABREL.NS", isin: "INE055A01016", name: "Aditya Birla Real Estate", sector: "Real Estate", indices: ["NIFTY500"] },
  { symbol: "ABSLAMC.NS", isin: "INE404A01024", name: "Aditya Birla Sun Life AMC", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "CPPLUS.NS", isin: "INE819V01029", name: "Aditya Infotech", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "AEGISLOG.NS", isin: "INE208C01025", name: "Aegis Logistics", sector: "Energy", indices: ["NIFTY500"] },
  { symbol: "AEGISVOPAK.NS", isin: "INE0INX01018", name: "Aegis Vopak Terminals", sector: "Energy", indices: ["NIFTY500"] },
  { symbol: "AFCONS.NS", isin: "INE101I01011", name: "Afcons Infrastructure", sector: "Construction", indices: ["NIFTY500"] },
  { symbol: "AFFLE.NS", isin: "INE00WC01027", name: "Affle 3i", sector: "IT", indices: ["NIFTY500"] },
  { symbol: "AJANTPHARM.NS", isin: "INE031B01049", name: "Ajanta Pharmaceuticals", sector: "Pharma", indices: ["NIFTY500"] },
  { symbol: "ALKEM.NS", isin: "INE540L01014", name: "Alkem Laboratories", sector: "Pharma", indices: ["NIFTY500"] },
  { symbol: "ABDL.NS", isin: "INE552Z01027", name: "Allied Blenders and Distillers", sector: "FMCG", indices: ["NIFTY500"] },
  { symbol: "ARE&M.NS", isin: "INE885A01032", name: "Amara Raja Energy & Mobility", sector: "Auto", indices: ["NIFTY500"] },
  { symbol: "AMBER.NS", isin: "INE371P01015", name: "Amber Enterprises India", sector: "Consumer", indices: ["NIFTY500"] },
  { symbol: "ANANDRATHI.NS", isin: "INE463V01026", name: "Anand Rathi Wealth", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "ANANTRAJ.NS", isin: "INE242C01024", name: "Anant Raj", sector: "Real Estate", indices: ["NIFTY500"] },
  { symbol: "ANGELONE.NS", isin: "INE732I01021", name: "Angel One", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "ANTHEM.NS", isin: "INE0CZ201020", name: "Anthem Biosciences", sector: "Pharma", indices: ["NIFTY500"] },
  { symbol: "ANURAS.NS", isin: "INE930P01018", name: "Anupam Rasayan India", sector: "Chemicals", indices: ["NIFTY500"] },
  { symbol: "APARINDS.NS", isin: "INE372A01015", name: "Apar Industries", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "APTUS.NS", isin: "INE852O01025", name: "Aptus Value Housing Finance India", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "ASAHIINDIA.NS", isin: "INE439A01020", name: "Asahi India Glass", sector: "Auto", indices: ["NIFTY500"] },
  { symbol: "ASHOKLEY.NS", isin: "INE208A01029", name: "Ashok Leyland", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "ASTERDM.NS", isin: "INE914M01019", name: "Aster DM Healthcare", sector: "Pharma", indices: ["NIFTY500"] },
  { symbol: "ASTRAL.NS", isin: "INE006I01046", name: "Astral", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "ATHERENERG.NS", isin: "INE0LEZ01016", name: "Ather Energy", sector: "Auto", indices: ["NIFTY500"] },
  { symbol: "ATUL.NS", isin: "INE100A01010", name: "Atul", sector: "Chemicals", indices: ["NIFTY500"] },
  { symbol: "AUROPHARMA.NS", isin: "INE406A01037", name: "Aurobindo Pharma", sector: "Pharma", indices: ["NIFTY500"] },
  { symbol: "AIIL.NS", isin: "INE206F01022", name: "Authum Investment & Infrastructure", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "BEML.NS", isin: "INE258A01024", name: "BEML", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "BLS.NS", isin: "INE153T01027", name: "BLS International Services", sector: "Consumer", indices: ["NIFTY500"] },
  { symbol: "BSE.NS", isin: "INE118H01025", name: "BSE", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "BAJAJHFL.NS", isin: "INE377Y01014", name: "Bajaj Housing Finance", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "BALKRISIND.NS", isin: "INE787D01026", name: "Balkrishna Industries", sector: "Auto", indices: ["NIFTY500"] },
  { symbol: "BALRAMCHIN.NS", isin: "INE119A01028", name: "Balrampur Chini Mills", sector: "FMCG", indices: ["NIFTY500"] },
  { symbol: "BANDHANBNK.NS", isin: "INE545U01014", name: "Bandhan Bank", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "BANKINDIA.NS", isin: "INE084A01016", name: "Bank of India", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "MAHABANK.NS", isin: "INE457A01014", name: "Bank of Maharashtra", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "BATAINDIA.NS", isin: "INE176A01028", name: "Bata India", sector: "Consumer", indices: ["NIFTY500"] },
  { symbol: "BAYERCROP.NS", isin: "INE462A01022", name: "Bayer Cropscience", sector: "Chemicals", indices: ["NIFTY500"] },
  { symbol: "BELRISE.NS", isin: "INE894V01022", name: "Belrise Industries", sector: "Auto", indices: ["NIFTY500"] },
  { symbol: "BERGEPAINT.NS", isin: "INE463A01038", name: "Berger Paints India", sector: "Consumer", indices: ["NIFTY500"] },
  { symbol: "BDL.NS", isin: "INE171Z01026", name: "Bharat Dynamics", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "BHARATFORG.NS", isin: "INE465A01025", name: "Bharat Forge", sector: "Auto", indices: ["NIFTY500"] },
  { symbol: "BHEL.NS", isin: "INE257A01026", name: "Bharat Heavy Electricals", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "BHARTIHEXA.NS", isin: "INE343G01021", name: "Bharti Hexacom", sector: "Telecom", indices: ["NIFTY500"] },
  { symbol: "BIKAJI.NS", isin: "INE00E101023", name: "Bikaji Foods International", sector: "FMCG", indices: ["NIFTY500"] },
  { symbol: "GROWW.NS", isin: "INE0HOQ01053", name: "Billionbrains Garage Ventures", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "BIOCON.NS", isin: "INE376G01013", name: "Biocon", sector: "Pharma", indices: ["NIFTY500"] },
  { symbol: "BSOFT.NS", isin: "INE836A01035", name: "Birlasoft", sector: "IT", indices: ["NIFTY500"] },
  { symbol: "BLUEDART.NS", isin: "INE233B01017", name: "Blue Dart Express", sector: "Services", indices: ["NIFTY500"] },
  { symbol: "BLUEJET.NS", isin: "INE0KBH01020", name: "Blue Jet Healthcare", sector: "Pharma", indices: ["NIFTY500"] },
  { symbol: "BLUESTARCO.NS", isin: "INE472A01039", name: "Blue Star", sector: "Consumer", indices: ["NIFTY500"] },
  { symbol: "BBTC.NS", isin: "INE050A01025", name: "Bombay Burmah Trading Corporation", sector: "FMCG", indices: ["NIFTY500"] },
  { symbol: "FIRSTCRY.NS", isin: "INE02RE01045", name: "Brainbees Solutions", sector: "Consumer", indices: ["NIFTY500"] },
  { symbol: "BRIGADE.NS", isin: "INE791I01019", name: "Brigade Enterprises", sector: "Real Estate", indices: ["NIFTY500"] },
  { symbol: "MAPMYINDIA.NS", isin: "INE0BV301023", name: "C.E. Info Systems", sector: "IT", indices: ["NIFTY500"] },
  { symbol: "CCL.NS", isin: "INE421D01022", name: "CCL Products (I)", sector: "FMCG", indices: ["NIFTY500"] },
  { symbol: "CESC.NS", isin: "INE486A01021", name: "CESC", sector: "Power", indices: ["NIFTY500"] },
  { symbol: "CRISIL.NS", isin: "INE007A01025", name: "CRISIL", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "CANFINHOME.NS", isin: "INE477A01020", name: "Can Fin Homes", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "CANHLIFE.NS", isin: "INE01TY01017", name: "Canara HSBC Life Insurance Company", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "CAPLIPOINT.NS", isin: "INE475E01026", name: "Caplin Point Laboratories", sector: "Pharma", indices: ["NIFTY500"] },
  { symbol: "CGCL.NS", isin: "INE180C01042", name: "Capri Global Capital", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "CARBORUNIV.NS", isin: "INE120A01034", name: "Carborundum Universal", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "CARTRADE.NS", isin: "INE290S01011", name: "Cartrade Tech", sector: "Consumer", indices: ["NIFTY500"] },
  { symbol: "CASTROLIND.NS", isin: "INE172A01027", name: "Castrol India", sector: "Energy", indices: ["NIFTY500"] },
  { symbol: "CEATLTD.NS", isin: "INE482A01020", name: "Ceat", sector: "Auto", indices: ["NIFTY500"] },
  { symbol: "CEMPRO.NS", isin: "INE686A01026", name: "Cemindia Projects", sector: "Construction", indices: ["NIFTY500"] },
  { symbol: "CENTRALBK.NS", isin: "INE483A01010", name: "Central Bank of India", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "CDSL.NS", isin: "INE736A01011", name: "Central Depository Services (India)", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "CHALET.NS", isin: "INE427F01016", name: "Chalet Hotels", sector: "Consumer", indices: ["NIFTY500"] },
  { symbol: "CHAMBLFERT.NS", isin: "INE085A01013", name: "Chambal Fertilizers & Chemicals", sector: "Chemicals", indices: ["NIFTY500"] },
  { symbol: "CHENNPETRO.NS", isin: "INE178A01016", name: "Chennai Petroleum Corporation", sector: "Energy", indices: ["NIFTY500"] },
  { symbol: "CHOICEIN.NS", isin: "INE102B01014", name: "Choice International", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "CHOLAHLDNG.NS", isin: "INE149A01033", name: "Cholamandalam Financial Holdings", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "CUB.NS", isin: "INE491A01021", name: "City Union Bank", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "CLEAN.NS", isin: "INE227W01023", name: "Clean Science and Technology", sector: "Chemicals", indices: ["NIFTY500"] },
  { symbol: "COCHINSHIP.NS", isin: "INE704P01025", name: "Cochin Shipyard", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "COHANCE.NS", isin: "INE03QK01018", name: "Cohance Lifesciences", sector: "Pharma", indices: ["NIFTY500"] },
  { symbol: "COLPAL.NS", isin: "INE259A01022", name: "Colgate Palmolive (India)", sector: "FMCG", indices: ["NIFTY500"] },
  { symbol: "CAMS.NS", isin: "INE596I01020", name: "Computer Age Management Services", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "CONCORDBIO.NS", isin: "INE338H01029", name: "Concord Biotech", sector: "Pharma", indices: ["NIFTY500"] },
  { symbol: "CONCOR.NS", isin: "INE111A01025", name: "Container Corporation of India", sector: "Services", indices: ["NIFTY500"] },
  { symbol: "COROMANDEL.NS", isin: "INE169A01031", name: "Coromandel International", sector: "Chemicals", indices: ["NIFTY500"] },
  { symbol: "CRAFTSMAN.NS", isin: "INE00LO01017", name: "Craftsman Automation", sector: "Auto", indices: ["NIFTY500"] },
  { symbol: "CREDITACC.NS", isin: "INE741K01010", name: "CreditAccess Grameen", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "CROMPTON.NS", isin: "INE299U01018", name: "Crompton Greaves Consumer Electricals", sector: "Consumer", indices: ["NIFTY500"] },
  { symbol: "CUMMINSIND.NS", isin: "INE298A01020", name: "Cummins India", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "CYIENT.NS", isin: "INE136B01020", name: "Cyient", sector: "IT", indices: ["NIFTY500"] },
  { symbol: "DCMSHRIRAM.NS", isin: "INE499A01024", name: "DCM Shriram", sector: "Diversified", indices: ["NIFTY500"] },
  { symbol: "DOMS.NS", isin: "INE321T01012", name: "DOMS Industries", sector: "FMCG", indices: ["NIFTY500"] },
  { symbol: "DALBHARAT.NS", isin: "INE00R701025", name: "Dalmia Bharat", sector: "Cement", indices: ["NIFTY500"] },
  { symbol: "DATAPATTNS.NS", isin: "INE0IX101010", name: "Data Patterns (India)", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "DEEPAKFERT.NS", isin: "INE501A01019", name: "Deepak Fertilisers & Petrochemicals Corp.", sector: "Chemicals", indices: ["NIFTY500"] },
  { symbol: "DEEPAKNTR.NS", isin: "INE288B01029", name: "Deepak Nitrite", sector: "Chemicals", indices: ["NIFTY500"] },
  { symbol: "DELHIVERY.NS", isin: "INE148O01028", name: "Delhivery", sector: "Services", indices: ["NIFTY500"] },
  { symbol: "DEVYANI.NS", isin: "INE872J01023", name: "Devyani International", sector: "Consumer", indices: ["NIFTY500"] },
  { symbol: "LALPATHLAB.NS", isin: "INE600L01024", name: "Dr. Lal Path Labs", sector: "Pharma", indices: ["NIFTY500"] },
  { symbol: "EIDPARRY.NS", isin: "INE126A01031", name: "E.I.D. Parry (India)", sector: "FMCG", indices: ["NIFTY500"] },
  { symbol: "EIHOTEL.NS", isin: "INE230A01023", name: "EIH", sector: "Consumer", indices: ["NIFTY500"] },
  { symbol: "ELECON.NS", isin: "INE205B01031", name: "Elecon Engineering Co.", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "ELGIEQUIP.NS", isin: "INE285A01027", name: "Elgi Equipments", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "EMAMILTD.NS", isin: "INE548C01032", name: "Emami", sector: "FMCG", indices: ["NIFTY500"] },
  { symbol: "EMCURE.NS", isin: "INE168P01015", name: "Emcure Pharmaceuticals", sector: "Pharma", indices: ["NIFTY500"] },
  { symbol: "EMMVEE.NS", isin: "INE1C6T01020", name: "Emmvee Photovoltaic Power", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "ENDURANCE.NS", isin: "INE913H01037", name: "Endurance Technologies", sector: "Auto", indices: ["NIFTY500"] },
  { symbol: "ENGINERSIN.NS", isin: "INE510A01028", name: "Engineers India", sector: "Construction", indices: ["NIFTY500"] },
  { symbol: "ERIS.NS", isin: "INE406M01024", name: "Eris Lifesciences", sector: "Pharma", indices: ["NIFTY500"] },
  { symbol: "ESCORTS.NS", isin: "INE042A01014", name: "Escorts Kubota", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "ETERNAL.NS", isin: "INE758T01015", name: "Eternal", sector: "Consumer", indices: ["NIFTY500"] },
  { symbol: "EXIDEIND.NS", isin: "INE302A01020", name: "Exide Industries", sector: "Auto", indices: ["NIFTY500"] },
  { symbol: "FACT.NS", isin: "INE188A01015", name: "Fertilisers and Chemicals Travancore", sector: "Chemicals", indices: ["NIFTY500"] },
  { symbol: "FINCABLES.NS", isin: "INE235A01022", name: "Finolex Cables", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "FSL.NS", isin: "INE684F01012", name: "Firstsource Solutions", sector: "Services", indices: ["NIFTY500"] },
  { symbol: "FIVESTAR.NS", isin: "INE128S01021", name: "Five-Star Business Finance", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "FORCEMOT.NS", isin: "INE451A01017", name: "Force Motors", sector: "Auto", indices: ["NIFTY500"] },
  { symbol: "FORTIS.NS", isin: "INE061F01013", name: "Fortis Healthcare", sector: "Pharma", indices: ["NIFTY500"] },
  { symbol: "GVT&D.NS", isin: "INE200A01026", name: "GE Vernova T&D India", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "GMRAIRPORT.NS", isin: "INE776C01039", name: "GMR Airports", sector: "Services", indices: ["NIFTY500"] },
  { symbol: "GABRIEL.NS", isin: "INE524A01029", name: "Gabriel India", sector: "Auto", indices: ["NIFTY500"] },
  { symbol: "GALLANTT.NS", isin: "INE297H01019", name: "Gallantt Ispat", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "GRSE.NS", isin: "INE382Z01011", name: "Garden Reach Shipbuilders & Engineers", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "GICRE.NS", isin: "INE481Y01014", name: "General Insurance Corporation of India", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "GILLETTE.NS", isin: "INE322A01010", name: "Gillette India", sector: "FMCG", indices: ["NIFTY500"] },
  { symbol: "GLAND.NS", isin: "INE068V01023", name: "Gland Pharma", sector: "Pharma", indices: ["NIFTY500"] },
  { symbol: "GLAXO.NS", isin: "INE159A01016", name: "Glaxosmithkline Pharmaceuticals", sector: "Pharma", indices: ["NIFTY500"] },
  { symbol: "GLENMARK.NS", isin: "INE935A01035", name: "Glenmark Pharmaceuticals", sector: "Pharma", indices: ["NIFTY500"] },
  { symbol: "MEDANTA.NS", isin: "INE474Q01031", name: "Global Health", sector: "Pharma", indices: ["NIFTY500"] },
  { symbol: "GODIGIT.NS", isin: "INE03JT01014", name: "Go Digit General Insurance", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "GPIL.NS", isin: "INE177H01039", name: "Godawari Power & Ispat", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "GODFRYPHLP.NS", isin: "INE260B01028", name: "Godfrey Phillips India", sector: "FMCG", indices: ["NIFTY500"] },
  { symbol: "GODREJIND.NS", isin: "INE233A01035", name: "Godrej Industries", sector: "Diversified", indices: ["NIFTY500"] },
  { symbol: "GODREJPROP.NS", isin: "INE484J01027", name: "Godrej Properties", sector: "Real Estate", indices: ["NIFTY500"] },
  { symbol: "GRANULES.NS", isin: "INE101D01020", name: "Granules India", sector: "Pharma", indices: ["NIFTY500"] },
  { symbol: "GRAPHITE.NS", isin: "INE371A01025", name: "Graphite India", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "GRAVITA.NS", isin: "INE024L01027", name: "Gravita India", sector: "Metals", indices: ["NIFTY500"] },
  { symbol: "GESHIP.NS", isin: "INE017A01032", name: "Great Eastern Shipping Co.", sector: "Services", indices: ["NIFTY500"] },
  { symbol: "FLUOROCHEM.NS", isin: "INE09N301011", name: "Gujarat Fluorochemicals", sector: "Chemicals", indices: ["NIFTY500"] },
  { symbol: "GMDCLTD.NS", isin: "INE131A01031", name: "Gujarat Mineral Development Corporation", sector: "Metals", indices: ["NIFTY500"] },
  { symbol: "GSPL.NS", isin: "INE246F01010", name: "Gujarat State Petronet", sector: "Energy", indices: ["NIFTY500"] },
  { symbol: "HEG.NS", isin: "INE545A01024", name: "H.E.G.", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "HBLENGINE.NS", isin: "INE292B01021", name: "HBL Engineering", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "HDBFS.NS", isin: "INE756I01012", name: "HDB Financial Services", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "HDFCAMC.NS", isin: "INE127D01025", name: "HDFC Asset Management Company", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "HFCL.NS", isin: "INE548A01028", name: "HFCL", sector: "Telecom", indices: ["NIFTY500"] },
  { symbol: "HEXT.NS", isin: "INE093A01041", name: "Hexaware Technologies", sector: "IT", indices: ["NIFTY500"] },
  { symbol: "HSCL.NS", isin: "INE019C01026", name: "Himadri Speciality Chemical", sector: "Chemicals", indices: ["NIFTY500"] },
  { symbol: "HINDCOPPER.NS", isin: "INE531E01026", name: "Hindustan Copper", sector: "Metals", indices: ["NIFTY500"] },
  { symbol: "HINDZINC.NS", isin: "INE267A01025", name: "Hindustan Zinc", sector: "Metals", indices: ["NIFTY500"] },
  { symbol: "POWERINDIA.NS", isin: "INE07Y701011", name: "Hitachi Energy India", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "HOMEFIRST.NS", isin: "INE481N01025", name: "Home First Finance Company India", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "HONASA.NS", isin: "INE0J5401028", name: "Honasa Consumer", sector: "FMCG", indices: ["NIFTY500"] },
  { symbol: "HONAUT.NS", isin: "INE671A01010", name: "Honeywell Automation India", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "HUDCO.NS", isin: "INE031A01017", name: "Housing & Urban Development Corporation", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "HYUNDAI.NS", isin: "INE0V6F01027", name: "Hyundai Motor India", sector: "Auto", indices: ["NIFTY500"] },
  { symbol: "ICICIAMC.NS", isin: "INE346A01027", name: "ICICI Prudential Asset Management Company", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "IDBI.NS", isin: "INE008A01015", name: "IDBI Bank", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "IFCI.NS", isin: "INE039A01010", name: "IFCI", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "IIFL.NS", isin: "INE530B01024", name: "IIFL Finance", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "IRB.NS", isin: "INE821I01022", name: "IRB Infrastructure Developers", sector: "Construction", indices: ["NIFTY500"] },
  { symbol: "IRCON.NS", isin: "INE962Y01021", name: "IRCON International", sector: "Construction", indices: ["NIFTY500"] },
  { symbol: "ITCHOTELS.NS", isin: "INE379A01028", name: "ITC Hotels", sector: "Consumer", indices: ["NIFTY500"] },
  { symbol: "ITI.NS", isin: "INE248A01017", name: "ITI", sector: "Telecom", indices: ["NIFTY500"] },
  { symbol: "INDGN.NS", isin: "INE065X01017", name: "Indegene", sector: "Pharma", indices: ["NIFTY500"] },
  { symbol: "INDIACEM.NS", isin: "INE383A01012", name: "India Cements", sector: "Cement", indices: ["NIFTY500"] },
  { symbol: "INDIAMART.NS", isin: "INE933S01016", name: "Indiamart Intermesh", sector: "Consumer", indices: ["NIFTY500"] },
  { symbol: "INDIANB.NS", isin: "INE562A01011", name: "Indian Bank", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "IEX.NS", isin: "INE022Q01020", name: "Indian Energy Exchange", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "IOB.NS", isin: "INE565A01014", name: "Indian Overseas Bank", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "IREDA.NS", isin: "INE202E01016", name: "Indian Renewable Energy Development Agency", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "IGL.NS", isin: "INE203G01027", name: "Indraprastha Gas", sector: "Energy", indices: ["NIFTY500"] },
  { symbol: "INDUSTOWER.NS", isin: "INE121J01017", name: "Indus Towers", sector: "Telecom", indices: ["NIFTY500"] },
  { symbol: "INOXWIND.NS", isin: "INE066P01011", name: "Inox Wind", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "INTELLECT.NS", isin: "INE306R01017", name: "Intellect Design Arena", sector: "IT", indices: ["NIFTY500"] },
  { symbol: "IGIL.NS", isin: "INE0Q9301021", name: "International Gemmological Institute (India)", sector: "Services", indices: ["NIFTY500"] },
  { symbol: "IKS.NS", isin: "INE115Q01022", name: "Inventurus Knowledge Solutions", sector: "IT", indices: ["NIFTY500"] },
  { symbol: "IPCALAB.NS", isin: "INE571A01038", name: "Ipca Laboratories", sector: "Pharma", indices: ["NIFTY500"] },
  { symbol: "JBCHEPHARM.NS", isin: "INE572A01036", name: "J.B. Chemicals & Pharmaceuticals", sector: "Pharma", indices: ["NIFTY500"] },
  { symbol: "JKCEMENT.NS", isin: "INE823G01014", name: "J.K. Cement", sector: "Cement", indices: ["NIFTY500"] },
  { symbol: "JBMA.NS", isin: "INE927D01051", name: "JBM Auto", sector: "Auto", indices: ["NIFTY500"] },
  { symbol: "JKTYRE.NS", isin: "INE573A01042", name: "JK Tyre & Industries", sector: "Auto", indices: ["NIFTY500"] },
  { symbol: "JMFINANCIL.NS", isin: "INE780C01023", name: "JM Financial", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "JSWCEMENT.NS", isin: "INE718I01012", name: "JSW Cement", sector: "Cement", indices: ["NIFTY500"] },
  { symbol: "JSWDULUX.NS", isin: "INE133A01011", name: "JSW Dulux", sector: "Consumer", indices: ["NIFTY500"] },
  { symbol: "JSWINFRA.NS", isin: "INE880J01026", name: "JSW Infrastructure", sector: "Services", indices: ["NIFTY500"] },
  { symbol: "JAINREC.NS", isin: "INE0YD401026", name: "Jain Resource Recycling", sector: "Metals", indices: ["NIFTY500"] },
  { symbol: "JPPOWER.NS", isin: "INE351F01018", name: "Jaiprakash Power Ventures", sector: "Power", indices: ["NIFTY500"] },
  { symbol: "J&KBANK.NS", isin: "INE168A01041", name: "Jammu & Kashmir Bank", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "JINDALSAW.NS", isin: "INE324A01032", name: "Jindal Saw", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "JSL.NS", isin: "INE220G01021", name: "Jindal Stainless", sector: "Metals", indices: ["NIFTY500"] },
  { symbol: "JUBLINGREA.NS", isin: "INE0BY001018", name: "Jubilant Ingrevia", sector: "Chemicals", indices: ["NIFTY500"] },
  { symbol: "JUBLPHARMA.NS", isin: "INE700A01033", name: "Jubilant Pharmova", sector: "Pharma", indices: ["NIFTY500"] },
  { symbol: "JWL.NS", isin: "INE209L01016", name: "Jupiter Wagons", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "JYOTICNC.NS", isin: "INE980O01024", name: "Jyoti CNC Automation", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "KPRMILL.NS", isin: "INE930H01031", name: "K.P.R. Mill", sector: "Textiles", indices: ["NIFTY500"] },
  { symbol: "KEI.NS", isin: "INE878B01027", name: "KEI Industries", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "KPITTECH.NS", isin: "INE04I401011", name: "KPIT Technologies", sector: "IT", indices: ["NIFTY500"] },
  { symbol: "KAJARIACER.NS", isin: "INE217B01036", name: "Kajaria Ceramics", sector: "Consumer", indices: ["NIFTY500"] },
  { symbol: "KPIL.NS", isin: "INE220B01022", name: "Kalpataru Projects International", sector: "Construction", indices: ["NIFTY500"] },
  { symbol: "KALYANKJIL.NS", isin: "INE303R01014", name: "Kalyan Jewellers India", sector: "Consumer", indices: ["NIFTY500"] },
  { symbol: "KARURVYSYA.NS", isin: "INE036D01028", name: "Karur Vysya Bank", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "KAYNES.NS", isin: "INE918Z01012", name: "Kaynes Technology India", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "KEC.NS", isin: "INE389H01022", name: "Kec International", sector: "Construction", indices: ["NIFTY500"] },
  { symbol: "KFINTECH.NS", isin: "INE138Y01010", name: "Kfin Technologies", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "KIRLOSENG.NS", isin: "INE146L01010", name: "Kirloskar Oil Eng", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "KIMS.NS", isin: "INE967H01025", name: "Krishna Institute of Medical Sciences", sector: "Pharma", indices: ["NIFTY500"] },
  { symbol: "LTF.NS", isin: "INE498L01015", name: "L&T Finance", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "LTTS.NS", isin: "INE010V01017", name: "L&T Technology Services", sector: "IT", indices: ["NIFTY500"] },
  { symbol: "LGEINDIA.NS", isin: "INE324D01010", name: "LG Electronics India", sector: "Consumer", indices: ["NIFTY500"] },
  { symbol: "LICHSGFIN.NS", isin: "INE115A01026", name: "LIC Housing Finance", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "LTFOODS.NS", isin: "INE818H01020", name: "LT Foods", sector: "FMCG", indices: ["NIFTY500"] },
  { symbol: "LTM.NS", isin: "INE214T01019", name: "LTM", sector: "IT", indices: ["NIFTY500"] },
  { symbol: "LATENTVIEW.NS", isin: "INE0I7C01011", name: "Latent View Analytics", sector: "IT", indices: ["NIFTY500"] },
  { symbol: "LAURUSLABS.NS", isin: "INE947Q01028", name: "Laurus Labs", sector: "Pharma", indices: ["NIFTY500"] },
  { symbol: "THELEELA.NS", isin: "INE0AQ201015", name: "Leela Palaces Hotels & Resorts", sector: "Consumer", indices: ["NIFTY500"] },
  { symbol: "LEMONTREE.NS", isin: "INE970X01018", name: "Lemon Tree Hotels", sector: "Consumer", indices: ["NIFTY500"] },
  { symbol: "LENSKART.NS", isin: "INE956O01016", name: "Lenskart Solutions", sector: "Consumer", indices: ["NIFTY500"] },
  { symbol: "LINDEINDIA.NS", isin: "INE473A01011", name: "Linde India", sector: "Chemicals", indices: ["NIFTY500"] },
  { symbol: "LLOYDSME.NS", isin: "INE281B01032", name: "Lloyds Metals And Energy", sector: "Metals", indices: ["NIFTY500"] },
  { symbol: "MMTC.NS", isin: "INE123F01029", name: "MMTC", sector: "Services", indices: ["NIFTY500"] },
  { symbol: "MRF.NS", isin: "INE883A01011", name: "MRF", sector: "Auto", indices: ["NIFTY500"] },
  { symbol: "MGL.NS", isin: "INE002S01010", name: "Mahanagar Gas", sector: "Energy", indices: ["NIFTY500"] },
  { symbol: "M&MFIN.NS", isin: "INE774D01024", name: "Mahindra & Mahindra Financial Services", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "MANAPPURAM.NS", isin: "INE522D01027", name: "Manappuram Finance", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "MRPL.NS", isin: "INE103A01014", name: "Mangalore Refinery & Petrochemicals", sector: "Energy", indices: ["NIFTY500"] },
  { symbol: "MANKIND.NS", isin: "INE634S01028", name: "Mankind Pharma", sector: "Pharma", indices: ["NIFTY500"] },
  { symbol: "MFSL.NS", isin: "INE180A01020", name: "Max Financial Services", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "MAXHEALTH.NS", isin: "INE027H01010", name: "Max Healthcare Institute", sector: "Pharma", indices: ["NIFTY500"] },
  { symbol: "MAZDOCK.NS", isin: "INE249Z01020", name: "Mazagoan Dock Shipbuilders", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "MEESHO.NS", isin: "INE0VDM01015", name: "Meesho", sector: "Consumer", indices: ["NIFTY500"] },
  { symbol: "MINDACORP.NS", isin: "INE842C01021", name: "Minda Corporation", sector: "Auto", indices: ["NIFTY500"] },
  { symbol: "MSUMI.NS", isin: "INE0FS801015", name: "Motherson Sumi Wiring India", sector: "Auto", indices: ["NIFTY500"] },
  { symbol: "MOTILALOFS.NS", isin: "INE338I01027", name: "Motilal Oswal Financial Services", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "MCX.NS", isin: "INE745G01043", name: "Multi Commodity Exchange of India", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "NATCOPHARM.NS", isin: "INE987B01026", name: "NATCO Pharma", sector: "Pharma", indices: ["NIFTY500"] },
  { symbol: "NBCC.NS", isin: "INE095N01031", name: "NBCC (India)", sector: "Construction", indices: ["NIFTY500"] },
  { symbol: "NCC.NS", isin: "INE868B01028", name: "NCC", sector: "Construction", indices: ["NIFTY500"] },
  { symbol: "NLCINDIA.NS", isin: "INE589A01014", name: "NLC India", sector: "Power", indices: ["NIFTY500"] },
  { symbol: "NMDC.NS", isin: "INE584A01023", name: "NMDC", sector: "Metals", indices: ["NIFTY500"] },
  { symbol: "NSLNISP.NS", isin: "INE0NNS01018", name: "NMDC Steel", sector: "Metals", indices: ["NIFTY500"] },
  { symbol: "NTPCGREEN.NS", isin: "INE0ONG01011", name: "NTPC Green Energy", sector: "Power", indices: ["NIFTY500"] },
  { symbol: "NH.NS", isin: "INE410P01011", name: "Narayana Hrudayalaya", sector: "Pharma", indices: ["NIFTY500"] },
  { symbol: "NATIONALUM.NS", isin: "INE139A01034", name: "National Aluminium Co.", sector: "Metals", indices: ["NIFTY500"] },
  { symbol: "NAVA.NS", isin: "INE725A01030", name: "Nava", sector: "Power", indices: ["NIFTY500"] },
  { symbol: "NAVINFLUOR.NS", isin: "INE048G01026", name: "Navin Fluorine International", sector: "Chemicals", indices: ["NIFTY500"] },
  { symbol: "NETWEB.NS", isin: "INE0NT901020", name: "Netweb Technologies India", sector: "IT", indices: ["NIFTY500"] },
  { symbol: "NEULANDLAB.NS", isin: "INE794A01010", name: "Neuland Laboratories", sector: "Pharma", indices: ["NIFTY500"] },
  { symbol: "NEWGEN.NS", isin: "INE619B01017", name: "Newgen Software Technologies", sector: "IT", indices: ["NIFTY500"] },
  { symbol: "NAM-INDIA.NS", isin: "INE298J01013", name: "Nippon Life India Asset Management", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "NIVABUPA.NS", isin: "INE995S01015", name: "Niva Bupa Health Insurance Company", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "NUVAMA.NS", isin: "INE531F01023", name: "Nuvama Wealth Management", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "NUVOCO.NS", isin: "INE118D01016", name: "Nuvoco Vistas Corporation", sector: "Cement", indices: ["NIFTY500"] },
  { symbol: "OBEROIRLTY.NS", isin: "INE093I01010", name: "Oberoi Realty", sector: "Real Estate", indices: ["NIFTY500"] },
  { symbol: "OIL.NS", isin: "INE274J01014", name: "Oil India", sector: "Energy", indices: ["NIFTY500"] },
  { symbol: "OLAELEC.NS", isin: "INE0LXG01040", name: "Ola Electric Mobility", sector: "Auto", indices: ["NIFTY500"] },
  { symbol: "OLECTRA.NS", isin: "INE260D01016", name: "Olectra Greentech", sector: "Auto", indices: ["NIFTY500"] },
  { symbol: "ONESOURCE.NS", isin: "INE013P01021", name: "Onesource Specialty Pharma", sector: "Pharma", indices: ["NIFTY500"] },
  { symbol: "POLICYBZR.NS", isin: "INE417T01026", name: "PB Fintech", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "PCBL.NS", isin: "INE602A01031", name: "PCBL Chemical", sector: "Chemicals", indices: ["NIFTY500"] },
  { symbol: "PGEL.NS", isin: "INE457L01029", name: "PG Electroplast", sector: "Consumer", indices: ["NIFTY500"] },
  { symbol: "PNBHOUSING.NS", isin: "INE572E01012", name: "PNB Housing Finance", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "PTCIL.NS", isin: "INE596F01018", name: "PTC Industries", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "PVRINOX.NS", isin: "INE191H01014", name: "PVR INOX", sector: "Media", indices: ["NIFTY500"] },
  { symbol: "PAGEIND.NS", isin: "INE761H01022", name: "Page Industries", sector: "Textiles", indices: ["NIFTY500"] },
  { symbol: "PARADEEP.NS", isin: "INE088F01024", name: "Paradeep Phosphates", sector: "Chemicals", indices: ["NIFTY500"] },
  { symbol: "PATANJALI.NS", isin: "INE619A01035", name: "Patanjali Foods", sector: "FMCG", indices: ["NIFTY500"] },
  { symbol: "PETRONET.NS", isin: "INE347G01014", name: "Petronet LNG", sector: "Energy", indices: ["NIFTY500"] },
  { symbol: "PFIZER.NS", isin: "INE182A01018", name: "Pfizer", sector: "Pharma", indices: ["NIFTY500"] },
  { symbol: "PHOENIXLTD.NS", isin: "INE211B01039", name: "Phoenix Mills", sector: "Real Estate", indices: ["NIFTY500"] },
  { symbol: "PWL.NS", isin: "INE0LP301011", name: "Physicswallah", sector: "Consumer", indices: ["NIFTY500"] },
  { symbol: "PINELABS.NS", isin: "INE15B701018", name: "Pine Labs", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "PIRAMALFIN.NS", isin: "INE202B01038", name: "Piramal Finance", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "PPLPHARMA.NS", isin: "INE0DK501011", name: "Piramal Pharma", sector: "Pharma", indices: ["NIFTY500"] },
  { symbol: "POLYMED.NS", isin: "INE205C01021", name: "Poly Medicure", sector: "Pharma", indices: ["NIFTY500"] },
  { symbol: "POONAWALLA.NS", isin: "INE511C01022", name: "Poonawalla Fincorp", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "PREMIERENE.NS", isin: "INE0BS701011", name: "Premier Energies", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "PRESTIGE.NS", isin: "INE811K01011", name: "Prestige Estates Projects", sector: "Real Estate", indices: ["NIFTY500"] },
  { symbol: "RRKABEL.NS", isin: "INE777K01022", name: "R R Kabel", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "RBLBANK.NS", isin: "INE976G01028", name: "RBL Bank", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "RHIM.NS", isin: "INE743M01012", name: "RHI MAGNESITA INDIA", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "RITES.NS", isin: "INE320J01015", name: "RITES", sector: "Construction", indices: ["NIFTY500"] },
  { symbol: "RADICO.NS", isin: "INE944F01028", name: "Radico Khaitan", sector: "FMCG", indices: ["NIFTY500"] },
  { symbol: "RVNL.NS", isin: "INE415G01027", name: "Rail Vikas Nigam", sector: "Construction", indices: ["NIFTY500"] },
  { symbol: "RAILTEL.NS", isin: "INE0DD101019", name: "Railtel Corporation Of India", sector: "Telecom", indices: ["NIFTY500"] },
  { symbol: "RAINBOW.NS", isin: "INE961O01016", name: "Rainbow Childrens Medicare", sector: "Pharma", indices: ["NIFTY500"] },
  { symbol: "RKFORGE.NS", isin: "INE399G01023", name: "Ramkrishna Forgings", sector: "Auto", indices: ["NIFTY500"] },
  { symbol: "REDINGTON.NS", isin: "INE891D01026", name: "Redington", sector: "Services", indices: ["NIFTY500"] },
  { symbol: "RPOWER.NS", isin: "INE614G01033", name: "Reliance Power", sector: "Power", indices: ["NIFTY500"] },
  { symbol: "SBFC.NS", isin: "INE423Y01016", name: "SBFC Finance", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "SBICARD.NS", isin: "INE018E01016", name: "SBI Cards and Payment Services", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "SJVN.NS", isin: "INE002L01015", name: "SJVN", sector: "Power", indices: ["NIFTY500"] },
  { symbol: "SRF.NS", isin: "INE647A01010", name: "SRF", sector: "Chemicals", indices: ["NIFTY500"] },
  { symbol: "SAGILITY.NS", isin: "INE0W2G01015", name: "Sagility", sector: "IT", indices: ["NIFTY500"] },
  { symbol: "SAILIFE.NS", isin: "INE570L01029", name: "Sai Life Sciences", sector: "Pharma", indices: ["NIFTY500"] },
  { symbol: "SAMMAANCAP.NS", isin: "INE148I01020", name: "Sammaan Capital", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "MOTHERSON.NS", isin: "INE775A01035", name: "Samvardhana Motherson International", sector: "Auto", indices: ["NIFTY500"] },
  { symbol: "SAPPHIRE.NS", isin: "INE806T01020", name: "Sapphire Foods India", sector: "Consumer", indices: ["NIFTY500"] },
  { symbol: "SARDAEN.NS", isin: "INE385C01021", name: "Sarda Energy and Minerals", sector: "Metals", indices: ["NIFTY500"] },
  { symbol: "SAREGAMA.NS", isin: "INE979A01025", name: "Saregama India", sector: "Media", indices: ["NIFTY500"] },
  { symbol: "SCHAEFFLER.NS", isin: "INE513A01022", name: "Schaeffler India", sector: "Auto", indices: ["NIFTY500"] },
  { symbol: "SCHNEIDER.NS", isin: "INE839M01018", name: "Schneider Electric Infrastructure", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "SCI.NS", isin: "INE109A01011", name: "Shipping Corporation of India", sector: "Services", indices: ["NIFTY500"] },
  { symbol: "SHREECEM.NS", isin: "INE070A01015", name: "Shree Cement", sector: "Cement", indices: ["NIFTY500"] },
  { symbol: "SHYAMMETL.NS", isin: "INE810G01011", name: "Shyam Metalics and Energy", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "ENRIN.NS", isin: "INE1NPP01017", name: "Siemens Energy India", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "SIGNATURE.NS", isin: "INE903U01023", name: "Signatureglobal (India)", sector: "Real Estate", indices: ["NIFTY500"] },
  { symbol: "SOBHA.NS", isin: "INE671H01015", name: "Sobha", sector: "Real Estate", indices: ["NIFTY500"] },
  { symbol: "SOLARINDS.NS", isin: "INE343H01029", name: "Solar Industries India", sector: "Chemicals", indices: ["NIFTY500"] },
  { symbol: "SONACOMS.NS", isin: "INE073K01018", name: "Sona BLW Precision Forgings", sector: "Auto", indices: ["NIFTY500"] },
  { symbol: "SONATSOFTW.NS", isin: "INE269A01021", name: "Sonata Software", sector: "IT", indices: ["NIFTY500"] },
  { symbol: "STARHEALTH.NS", isin: "INE575P01011", name: "Star Health and Allied Insurance Company", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "SUMICHEM.NS", isin: "INE258G01013", name: "Sumitomo Chemical India", sector: "Chemicals", indices: ["NIFTY500"] },
  { symbol: "SUNTV.NS", isin: "INE424H01027", name: "Sun TV Network", sector: "Media", indices: ["NIFTY500"] },
  { symbol: "SUNDARMFIN.NS", isin: "INE660A01013", name: "Sundaram Finance", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "SUPREMEIND.NS", isin: "INE195A01028", name: "Supreme Industries", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "SPLPETRO.NS", isin: "INE663A01033", name: "Supreme Petrochem", sector: "Chemicals", indices: ["NIFTY500"] },
  { symbol: "SUZLON.NS", isin: "INE040H01021", name: "Suzlon Energy", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "SWANCORP.NS", isin: "INE665A01038", name: "Swan Corp", sector: "Chemicals", indices: ["NIFTY500"] },
  { symbol: "SWIGGY.NS", isin: "INE00H001014", name: "Swiggy", sector: "Consumer", indices: ["NIFTY500"] },
  { symbol: "SYNGENE.NS", isin: "INE398R01022", name: "Syngene International", sector: "Pharma", indices: ["NIFTY500"] },
  { symbol: "SYRMA.NS", isin: "INE0DYJ01015", name: "Syrma SGS Technology", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "TBOTEK.NS", isin: "INE673O01025", name: "TBO Tek", sector: "Consumer", indices: ["NIFTY500"] },
  { symbol: "TATACAP.NS", isin: "INE976I01016", name: "Tata Capital", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "TATACHEM.NS", isin: "INE092A01019", name: "Tata Chemicals", sector: "Chemicals", indices: ["NIFTY500"] },
  { symbol: "TATACOMM.NS", isin: "INE151A01013", name: "Tata Communications", sector: "Telecom", indices: ["NIFTY500"] },
  { symbol: "TATAINVEST.NS", isin: "INE672A01026", name: "Tata Investment Corporation", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "TMCV.NS", isin: "INE1TAE01010", name: "Tata Motors", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "TMPV.NS", isin: "INE155A01022", name: "Tata Motors Passenger Vehicles", sector: "Auto", indices: ["NIFTY500"] },
  { symbol: "TATATECH.NS", isin: "INE142M01025", name: "Tata Technologies", sector: "IT", indices: ["NIFTY500"] },
  { symbol: "TTML.NS", isin: "INE517B01013", name: "Tata Teleservices (Maharashtra)", sector: "Telecom", indices: ["NIFTY500"] },
  { symbol: "TECHNOE.NS", isin: "INE285K01026", name: "Techno Electric & Engineering Company", sector: "Construction", indices: ["NIFTY500"] },
  { symbol: "TEGA.NS", isin: "INE011K01018", name: "Tega Industries", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "TEJASNET.NS", isin: "INE010J01012", name: "Tejas Networks", sector: "Telecom", indices: ["NIFTY500"] },
  { symbol: "TENNIND.NS", isin: "INE19RI01016", name: "Tenneco Clean Air India", sector: "Auto", indices: ["NIFTY500"] },
  { symbol: "NIACL.NS", isin: "INE470Y01017", name: "The New India Assurance Company", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "RAMCOCEM.NS", isin: "INE331A01037", name: "The Ramco Cements", sector: "Cement", indices: ["NIFTY500"] },
  { symbol: "THERMAX.NS", isin: "INE152A01029", name: "Thermax", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "TIMKEN.NS", isin: "INE325A01013", name: "Timken India", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "TITAGARH.NS", isin: "INE615H01020", name: "Titagarh Rail Systems", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "TORNTPOWER.NS", isin: "INE813H01021", name: "Torrent Power", sector: "Power", indices: ["NIFTY500"] },
  { symbol: "TARIL.NS", isin: "INE763I01026", name: "Transformers And Rectifiers (India)", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "TRAVELFOOD.NS", isin: "INE103V01028", name: "Travel Food Services", sector: "Consumer", indices: ["NIFTY500"] },
  { symbol: "TRIDENT.NS", isin: "INE064C01022", name: "Trident", sector: "Textiles", indices: ["NIFTY500"] },
  { symbol: "TRITURBINE.NS", isin: "INE152M01016", name: "Triveni Turbine", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "TIINDIA.NS", isin: "INE974X01010", name: "Tube Investments of India", sector: "Auto", indices: ["NIFTY500"] },
  { symbol: "UCOBANK.NS", isin: "INE691A01018", name: "UCO Bank", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "UNOMINDA.NS", isin: "INE405E01023", name: "UNO Minda", sector: "Auto", indices: ["NIFTY500"] },
  { symbol: "UTIAMC.NS", isin: "INE094J01016", name: "UTI Asset Management Company", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "UBL.NS", isin: "INE686F01025", name: "United Breweries", sector: "FMCG", indices: ["NIFTY500"] },
  { symbol: "UNITDSPR.NS", isin: "INE854D01024", name: "United Spirits", sector: "FMCG", indices: ["NIFTY500"] },
  { symbol: "URBANCO.NS", isin: "INE0CAZ01013", name: "Urban Company", sector: "Consumer", indices: ["NIFTY500"] },
  { symbol: "USHAMART.NS", isin: "INE228A01035", name: "Usha Martin", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "VTL.NS", isin: "INE825A01020", name: "Vardhman Textiles", sector: "Textiles", indices: ["NIFTY500"] },
  { symbol: "VBL.NS", isin: "INE200M01039", name: "Varun Beverages", sector: "FMCG", indices: ["NIFTY500"] },
  { symbol: "VIJAYA.NS", isin: "INE043W01024", name: "Vijaya Diagnostic Centre", sector: "Pharma", indices: ["NIFTY500"] },
  { symbol: "VMM.NS", isin: "INE01EA01019", name: "Vishal Mega Mart", sector: "Consumer", indices: ["NIFTY500"] },
  { symbol: "IDEA.NS", isin: "INE669E01016", name: "Vodafone Idea", sector: "Telecom", indices: ["NIFTY500"] },
  { symbol: "VOLTAS.NS", isin: "INE226A01021", name: "Voltas", sector: "Consumer", indices: ["NIFTY500"] },
  { symbol: "WAAREEENER.NS", isin: "INE377N01017", name: "Waaree Energies", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "WELCORP.NS", isin: "INE191B01025", name: "Welspun Corp", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "WELSPUNLIV.NS", isin: "INE192B01031", name: "Welspun Living", sector: "Textiles", indices: ["NIFTY500"] },
  { symbol: "WHIRLPOOL.NS", isin: "INE716A01013", name: "Whirlpool of India", sector: "Consumer", indices: ["NIFTY500"] },
  { symbol: "WOCKPHARMA.NS", isin: "INE049B01025", name: "Wockhardt", sector: "Pharma", indices: ["NIFTY500"] },
  { symbol: "YESBANK.NS", isin: "INE528G01035", name: "Yes Bank", sector: "Finance", indices: ["NIFTY500"] },
  { symbol: "ZFCVINDIA.NS", isin: "INE342J01019", name: "ZF Commercial Vehicle Control Systems India", sector: "Auto", indices: ["NIFTY500"] },
  { symbol: "ZEEL.NS", isin: "INE256A01028", name: "Zee Entertainment Enterprises", sector: "Media", indices: ["NIFTY500"] },
  { symbol: "ZENTEC.NS", isin: "INE251B01027", name: "Zen Technologies", sector: "Capital Goods", indices: ["NIFTY500"] },
  { symbol: "ZENSARTECH.NS", isin: "INE520A01027", name: "Zensar Technolgies", sector: "IT", indices: ["NIFTY500"] },
  { symbol: "ZYDUSWELL.NS", isin: "INE768C01028", name: "Zydus Wellness", sector: "FMCG", indices: ["NIFTY500"] },
  { symbol: "ECLERX.NS", isin: "INE738I01010", name: "eClerx Services", sector: "Services", indices: ["NIFTY500"] },

  // ========== PORTFOLIO EXTENSIONS ==========
  // Off-Nifty-500 NSE-listed stocks added so portfolio uploads can resolve them by ISIN.
  // `indices: []` keeps them out of scanner universes (no live scores available) while
  // still making them matchable in findByIsin().
  { symbol: "BALUFORGE.NS", isin: "INE011E01029", name: "Balu Forge Industries", sector: "Auto Components", indices: [] },
  { symbol: "WALCHANNAG.NS", isin: "INE711A01022", name: "Walchandnagar Industries", sector: "Capital Goods", indices: [] },
];

// Deduplicate defensively (in case of accidental duplicates)
const uniqueMap = new Map();
for (const s of ALL_STOCKS) {
  if (!uniqueMap.has(s.symbol)) uniqueMap.set(s.symbol, s);
}
const DEDUPED = Array.from(uniqueMap.values());

// Nifty 500 membership set — generated from NSE's ind_nifty500list.csv
// (Apr 2026). Used by getNifty500() to include existing Nifty 100 entries
// whose `indices` arrays don't explicitly carry the NIFTY500 tag. When
// NSE rebalances, regenerate via: node scripts/build-nifty500.mjs
const NIFTY500_SYMBOLS = new Set([
  "360ONE.NS",
  "3MINDIA.NS",
  "ABB.NS",
  "ACC.NS",
  "ACMESOLAR.NS",
  "AIAENG.NS",
  "APLAPOLLO.NS",
  "AUBANK.NS",
  "AWL.NS",
  "AADHARHFC.NS",
  "AARTIIND.NS",
  "AAVAS.NS",
  "ABBOTINDIA.NS",
  "ACE.NS",
  "ACUTAAS.NS",
  "ADANIENSOL.NS",
  "ADANIENT.NS",
  "ADANIGREEN.NS",
  "ADANIPORTS.NS",
  "ADANIPOWER.NS",
  "ATGL.NS",
  "ABCAPITAL.NS",
  "ABFRL.NS",
  "ABLBL.NS",
  "ABREL.NS",
  "ABSLAMC.NS",
  "CPPLUS.NS",
  "AEGISLOG.NS",
  "AEGISVOPAK.NS",
  "AFCONS.NS",
  "AFFLE.NS",
  "AJANTPHARM.NS",
  "ALKEM.NS",
  "ABDL.NS",
  "ARE&M.NS",
  "AMBER.NS",
  "AMBUJACEM.NS",
  "ANANDRATHI.NS",
  "ANANTRAJ.NS",
  "ANGELONE.NS",
  "ANTHEM.NS",
  "ANURAS.NS",
  "APARINDS.NS",
  "APOLLOHOSP.NS",
  "APOLLOTYRE.NS",
  "APTUS.NS",
  "ASAHIINDIA.NS",
  "ASHOKLEY.NS",
  "ASIANPAINT.NS",
  "ASTERDM.NS",
  "ASTRAL.NS",
  "ATHERENERG.NS",
  "ATUL.NS",
  "AUROPHARMA.NS",
  "AIIL.NS",
  "DMART.NS",
  "AXISBANK.NS",
  "BEML.NS",
  "BLS.NS",
  "BSE.NS",
  "BAJAJ-AUTO.NS",
  "BAJFINANCE.NS",
  "BAJAJFINSV.NS",
  "BAJAJHLDNG.NS",
  "BAJAJHFL.NS",
  "BALKRISIND.NS",
  "BALRAMCHIN.NS",
  "BANDHANBNK.NS",
  "BANKBARODA.NS",
  "BANKINDIA.NS",
  "MAHABANK.NS",
  "BATAINDIA.NS",
  "BAYERCROP.NS",
  "BELRISE.NS",
  "BERGEPAINT.NS",
  "BDL.NS",
  "BEL.NS",
  "BHARATFORG.NS",
  "BHEL.NS",
  "BPCL.NS",
  "BHARTIARTL.NS",
  "BHARTIHEXA.NS",
  "BIKAJI.NS",
  "GROWW.NS",
  "BIOCON.NS",
  "BSOFT.NS",
  "BLUEDART.NS",
  "BLUEJET.NS",
  "BLUESTARCO.NS",
  "BBTC.NS",
  "BOSCHLTD.NS",
  "FIRSTCRY.NS",
  "BRIGADE.NS",
  "BRITANNIA.NS",
  "MAPMYINDIA.NS",
  "CCL.NS",
  "CESC.NS",
  "CGPOWER.NS",
  "CRISIL.NS",
  "CANFINHOME.NS",
  "CANBK.NS",
  "CANHLIFE.NS",
  "CAPLIPOINT.NS",
  "CGCL.NS",
  "CARBORUNIV.NS",
  "CARTRADE.NS",
  "CASTROLIND.NS",
  "CEATLTD.NS",
  "CEMPRO.NS",
  "CENTRALBK.NS",
  "CDSL.NS",
  "CHALET.NS",
  "CHAMBLFERT.NS",
  "CHENNPETRO.NS",
  "CHOICEIN.NS",
  "CHOLAHLDNG.NS",
  "CHOLAFIN.NS",
  "CIPLA.NS",
  "CUB.NS",
  "CLEAN.NS",
  "COALINDIA.NS",
  "COCHINSHIP.NS",
  "COFORGE.NS",
  "COHANCE.NS",
  "COLPAL.NS",
  "CAMS.NS",
  "CONCORDBIO.NS",
  "CONCOR.NS",
  "COROMANDEL.NS",
  "CRAFTSMAN.NS",
  "CREDITACC.NS",
  "CROMPTON.NS",
  "CUMMINSIND.NS",
  "CYIENT.NS",
  "DCMSHRIRAM.NS",
  "DLF.NS",
  "DOMS.NS",
  "DABUR.NS",
  "DALBHARAT.NS",
  "DATAPATTNS.NS",
  "DEEPAKFERT.NS",
  "DEEPAKNTR.NS",
  "DELHIVERY.NS",
  "DEVYANI.NS",
  "DIVISLAB.NS",
  "DIXON.NS",
  "LALPATHLAB.NS",
  "DRREDDY.NS",
  "EIDPARRY.NS",
  "EIHOTEL.NS",
  "EICHERMOT.NS",
  "ELECON.NS",
  "ELGIEQUIP.NS",
  "EMAMILTD.NS",
  "EMCURE.NS",
  "EMMVEE.NS",
  "ENDURANCE.NS",
  "ENGINERSIN.NS",
  "ERIS.NS",
  "ESCORTS.NS",
  "ETERNAL.NS",
  "EXIDEIND.NS",
  "NYKAA.NS",
  "FEDERALBNK.NS",
  "FACT.NS",
  "FINCABLES.NS",
  "FSL.NS",
  "FIVESTAR.NS",
  "FORCEMOT.NS",
  "FORTIS.NS",
  "GAIL.NS",
  "GVT&D.NS",
  "GMRAIRPORT.NS",
  "GABRIEL.NS",
  "GALLANTT.NS",
  "GRSE.NS",
  "GICRE.NS",
  "GILLETTE.NS",
  "GLAND.NS",
  "GLAXO.NS",
  "GLENMARK.NS",
  "MEDANTA.NS",
  "GODIGIT.NS",
  "GPIL.NS",
  "GODFRYPHLP.NS",
  "GODREJCP.NS",
  "GODREJIND.NS",
  "GODREJPROP.NS",
  "GRANULES.NS",
  "GRAPHITE.NS",
  "GRASIM.NS",
  "GRAVITA.NS",
  "GESHIP.NS",
  "FLUOROCHEM.NS",
  "GMDCLTD.NS",
  "GSPL.NS",
  "HEG.NS",
  "HBLENGINE.NS",
  "HCLTECH.NS",
  "HDBFS.NS",
  "HDFCAMC.NS",
  "HDFCBANK.NS",
  "HDFCLIFE.NS",
  "HFCL.NS",
  "HAVELLS.NS",
  "HEROMOTOCO.NS",
  "HEXT.NS",
  "HSCL.NS",
  "HINDALCO.NS",
  "HAL.NS",
  "HINDCOPPER.NS",
  "HINDPETRO.NS",
  "HINDUNILVR.NS",
  "HINDZINC.NS",
  "POWERINDIA.NS",
  "HOMEFIRST.NS",
  "HONASA.NS",
  "HONAUT.NS",
  "HUDCO.NS",
  "HYUNDAI.NS",
  "ICICIBANK.NS",
  "ICICIGI.NS",
  "ICICIAMC.NS",
  "ICICIPRULI.NS",
  "IDBI.NS",
  "IDFCFIRSTB.NS",
  "IFCI.NS",
  "IIFL.NS",
  "IRB.NS",
  "IRCON.NS",
  "ITCHOTELS.NS",
  "ITC.NS",
  "ITI.NS",
  "INDGN.NS",
  "INDIACEM.NS",
  "INDIAMART.NS",
  "INDIANB.NS",
  "IEX.NS",
  "INDHOTEL.NS",
  "IOC.NS",
  "IOB.NS",
  "IRCTC.NS",
  "IRFC.NS",
  "IREDA.NS",
  "IGL.NS",
  "INDUSTOWER.NS",
  "INDUSINDBK.NS",
  "NAUKRI.NS",
  "INFY.NS",
  "INOXWIND.NS",
  "INTELLECT.NS",
  "INDIGO.NS",
  "IGIL.NS",
  "IKS.NS",
  "IPCALAB.NS",
  "JBCHEPHARM.NS",
  "JKCEMENT.NS",
  "JBMA.NS",
  "JKTYRE.NS",
  "JMFINANCIL.NS",
  "JSWCEMENT.NS",
  "JSWDULUX.NS",
  "JSWENERGY.NS",
  "JSWINFRA.NS",
  "JSWSTEEL.NS",
  "JAINREC.NS",
  "JPPOWER.NS",
  "J&KBANK.NS",
  "JINDALSAW.NS",
  "JSL.NS",
  "JINDALSTEL.NS",
  "JIOFIN.NS",
  "JUBLFOOD.NS",
  "JUBLINGREA.NS",
  "JUBLPHARMA.NS",
  "JWL.NS",
  "JYOTICNC.NS",
  "KPRMILL.NS",
  "KEI.NS",
  "KPITTECH.NS",
  "KAJARIACER.NS",
  "KPIL.NS",
  "KALYANKJIL.NS",
  "KARURVYSYA.NS",
  "KAYNES.NS",
  "KEC.NS",
  "KFINTECH.NS",
  "KIRLOSENG.NS",
  "KOTAKBANK.NS",
  "KIMS.NS",
  "LTF.NS",
  "LTTS.NS",
  "LGEINDIA.NS",
  "LICHSGFIN.NS",
  "LTFOODS.NS",
  "LTM.NS",
  "LT.NS",
  "LATENTVIEW.NS",
  "LAURUSLABS.NS",
  "THELEELA.NS",
  "LEMONTREE.NS",
  "LENSKART.NS",
  "LICI.NS",
  "LINDEINDIA.NS",
  "LLOYDSME.NS",
  "LODHA.NS",
  "LUPIN.NS",
  "MMTC.NS",
  "MRF.NS",
  "MGL.NS",
  "M&MFIN.NS",
  "M&M.NS",
  "MANAPPURAM.NS",
  "MRPL.NS",
  "MANKIND.NS",
  "MARICO.NS",
  "MARUTI.NS",
  "MFSL.NS",
  "MAXHEALTH.NS",
  "MAZDOCK.NS",
  "MEESHO.NS",
  "MINDACORP.NS",
  "MSUMI.NS",
  "MOTILALOFS.NS",
  "MPHASIS.NS",
  "MCX.NS",
  "MUTHOOTFIN.NS",
  "NATCOPHARM.NS",
  "NBCC.NS",
  "NCC.NS",
  "NHPC.NS",
  "NLCINDIA.NS",
  "NMDC.NS",
  "NSLNISP.NS",
  "NTPCGREEN.NS",
  "NTPC.NS",
  "NH.NS",
  "NATIONALUM.NS",
  "NAVA.NS",
  "NAVINFLUOR.NS",
  "NESTLEIND.NS",
  "NETWEB.NS",
  "NEULANDLAB.NS",
  "NEWGEN.NS",
  "NAM-INDIA.NS",
  "NIVABUPA.NS",
  "NUVAMA.NS",
  "NUVOCO.NS",
  "OBEROIRLTY.NS",
  "ONGC.NS",
  "OIL.NS",
  "OLAELEC.NS",
  "OLECTRA.NS",
  "PAYTM.NS",
  "ONESOURCE.NS",
  "OFSS.NS",
  "POLICYBZR.NS",
  "PCBL.NS",
  "PGEL.NS",
  "PIIND.NS",
  "PNBHOUSING.NS",
  "PTCIL.NS",
  "PVRINOX.NS",
  "PAGEIND.NS",
  "PARADEEP.NS",
  "PATANJALI.NS",
  "PERSISTENT.NS",
  "PETRONET.NS",
  "PFIZER.NS",
  "PHOENIXLTD.NS",
  "PWL.NS",
  "PIDILITIND.NS",
  "PINELABS.NS",
  "PIRAMALFIN.NS",
  "PPLPHARMA.NS",
  "POLYMED.NS",
  "POLYCAB.NS",
  "POONAWALLA.NS",
  "PFC.NS",
  "POWERGRID.NS",
  "PREMIERENE.NS",
  "PRESTIGE.NS",
  "PNB.NS",
  "RRKABEL.NS",
  "RBLBANK.NS",
  "RECLTD.NS",
  "RHIM.NS",
  "RITES.NS",
  "RADICO.NS",
  "RVNL.NS",
  "RAILTEL.NS",
  "RAINBOW.NS",
  "RKFORGE.NS",
  "REDINGTON.NS",
  "RELIANCE.NS",
  "RPOWER.NS",
  "SBFC.NS",
  "SBICARD.NS",
  "SBILIFE.NS",
  "SJVN.NS",
  "SRF.NS",
  "SAGILITY.NS",
  "SAILIFE.NS",
  "SAMMAANCAP.NS",
  "MOTHERSON.NS",
  "SAPPHIRE.NS",
  "SARDAEN.NS",
  "SAREGAMA.NS",
  "SCHAEFFLER.NS",
  "SCHNEIDER.NS",
  "SCI.NS",
  "SHREECEM.NS",
  "SHRIRAMFIN.NS",
  "SHYAMMETL.NS",
  "ENRIN.NS",
  "SIEMENS.NS",
  "SIGNATURE.NS",
  "SOBHA.NS",
  "SOLARINDS.NS",
  "SONACOMS.NS",
  "SONATSOFTW.NS",
  "STARHEALTH.NS",
  "SBIN.NS",
  "SAIL.NS",
  "SUMICHEM.NS",
  "SUNPHARMA.NS",
  "SUNTV.NS",
  "SUNDARMFIN.NS",
  "SUPREMEIND.NS",
  "SPLPETRO.NS",
  "SUZLON.NS",
  "SWANCORP.NS",
  "SWIGGY.NS",
  "SYNGENE.NS",
  "SYRMA.NS",
  "TBOTEK.NS",
  "TVSMOTOR.NS",
  "TATACAP.NS",
  "TATACHEM.NS",
  "TATACOMM.NS",
  "TCS.NS",
  "TATACONSUM.NS",
  "TATAELXSI.NS",
  "TATAINVEST.NS",
  "TMCV.NS",
  "TMPV.NS",
  "TATAPOWER.NS",
  "TATASTEEL.NS",
  "TATATECH.NS",
  "TTML.NS",
  "TECHM.NS",
  "TECHNOE.NS",
  "TEGA.NS",
  "TEJASNET.NS",
  "TENNIND.NS",
  "NIACL.NS",
  "RAMCOCEM.NS",
  "THERMAX.NS",
  "TIMKEN.NS",
  "TITAGARH.NS",
  "TITAN.NS",
  "TORNTPHARM.NS",
  "TORNTPOWER.NS",
  "TARIL.NS",
  "TRAVELFOOD.NS",
  "TRENT.NS",
  "TRIDENT.NS",
  "TRITURBINE.NS",
  "TIINDIA.NS",
  "UCOBANK.NS",
  "UNOMINDA.NS",
  "UPL.NS",
  "UTIAMC.NS",
  "ULTRACEMCO.NS",
  "UNIONBANK.NS",
  "UBL.NS",
  "UNITDSPR.NS",
  "URBANCO.NS",
  "USHAMART.NS",
  "VTL.NS",
  "VBL.NS",
  "VEDL.NS",
  "VIJAYA.NS",
  "VMM.NS",
  "IDEA.NS",
  "VOLTAS.NS",
  "WAAREEENER.NS",
  "WELCORP.NS",
  "WELSPUNLIV.NS",
  "WHIRLPOOL.NS",
  "WIPRO.NS",
  "WOCKPHARMA.NS",
  "YESBANK.NS",
  "ZFCVINDIA.NS",
  "ZEEL.NS",
  "ZENTEC.NS",
  "ZENSARTECH.NS",
  "ZYDUSLIFE.NS",
  "ZYDUSWELL.NS",
  "ECLERX.NS",
]);

// Build index-specific slices
function getStocksByIndex(indexTag) {
  return DEDUPED.filter((s) => s.indices.includes(indexTag));
}

function getAllStocks() {
  return DEDUPED;
}

// Nifty 100 = Nifty 50 + Nifty Next 50
function getNifty100() {
  return DEDUPED.filter((s) => s.indices.includes("NIFTY50") || s.indices.includes("NIFTY_NEXT_50"));
}

// Nifty 500 = any entry tagged NIFTY500, NIFTY50, NIFTY_NEXT_50, or in the
// NIFTY500_SYMBOLS set (covers existing Nifty 100 stocks whose `indices`
// arrays aren't explicitly tagged with "NIFTY500"). Phase 2: universe
// expansion from 116 → ~500 stocks for scanner coverage.
function getNifty500() {
  return DEDUPED.filter((s) =>
    s.indices.includes("NIFTY500") ||
    s.indices.includes("NIFTY50") ||
    s.indices.includes("NIFTY_NEXT_50") ||
    NIFTY500_SYMBOLS.has(s.symbol),
  );
}

// Phase 2 liquidity filter (applied downstream by scanner after fetching
// quotes). A stock must have 30-day median turnover ≥ ₹5 cr/day to enter
// scanner output — below that, SL/target orders can't reliably fill and
// recommendations become unexecutable.
const LIQUIDITY_MIN_TURNOVER_CR = 5;
function passesLiquidityFilter(medianTurnoverCrPerDay) {
  if (medianTurnoverCrPerDay == null || !Number.isFinite(medianTurnoverCrPerDay)) return true; // assume ok if unknown
  return medianTurnoverCrPerDay >= LIQUIDITY_MIN_TURNOVER_CR;
}

// Phase 5: ISIN and name-based resolution helpers for the Portfolio Analyzer.
// Broker exports (Groww/Zerodha) identify holdings by ISIN primarily. When
// the ISIN isn't in our universe, we fall back to fuzzy-normalised name
// match so partial-coverage portfolios still analyze what they can.

// Build the ISIN → stock index once at module load.
const ISIN_INDEX = new Map();
for (const s of DEDUPED) {
  if (s.isin) ISIN_INDEX.set(s.isin, s);
}

// ─── Supplement index: NSE Total Market + Microcap/Smallcap/Nifty500 ───
//
// Curated ALL_STOCKS covers ~503 quality large/midcaps. Real portfolio
// uploads regularly contain names outside that list (Azad Engineering,
// Ujjivan SFB, and many other recently-listed or lesser-known smallcaps).
// nseUniverseSupplement.json is built by scripts/build-nse-supplement.mjs
// from NSE's index-stockIndices endpoint — it carries symbol+ISIN+name+
// sector for every NSE-listed name not already in ALL_STOCKS.
//
// These supplement entries let findByIsin/findBySymbol resolve holdings
// for portfolio analysis (real-time price + per-stock risk metrics still
// work). They're intentionally NOT surfaced in the scanners because
// the fundamental scoring model depends on the curated fundamentals.json
// snapshot which only covers ALL_STOCKS.
const SUPPLEMENT_BY_ISIN = new Map();
const SUPPLEMENT_BY_SYMBOL = new Map();
try {
  const supplementPath = new URL("./nseUniverseSupplement.json", import.meta.url);
  const { readFileSync } = await import("fs");
  const raw = readFileSync(supplementPath, "utf-8");
  const supplement = JSON.parse(raw);
  for (const [bare, rec] of Object.entries(supplement.bySymbol || {})) {
    const enriched = {
      symbol: rec.symbol,
      isin: rec.isin,
      name: rec.name,
      sector: rec.sector,
      indices: rec.indices || [],
      // Flag so downstream code can tell curated vs supplement
      source: "nse-supplement",
    };
    if (rec.isin) SUPPLEMENT_BY_ISIN.set(rec.isin, enriched);
    SUPPLEMENT_BY_SYMBOL.set(bare, enriched);
    SUPPLEMENT_BY_SYMBOL.set(rec.symbol.toUpperCase(), enriched);
  }
} catch (err) {
  // Supplement is optional — if the file is missing (e.g. first-run
  // dev checkout before the build script ran), we just fall back to
  // the primary curated list. Log once so engineers notice.
  if (err?.code !== "ENOENT") {
    console.warn("[stockList] supplement load failed:", err.message);
  }
}

// Symbol → stock index. Keyed by BARE ticker (no exchange suffix) because
// that's what users type into portfolio CSVs — "TCS", "RELIANCE", "HDFCBANK"
// — even though our canonical symbols are ".NS" / ".BO" suffixed. We ALSO
// register the full suffixed form so uploads like "TCS.NS" or "TCS.BO"
// resolve identically.
//
// Collision strategy: NSE listing wins over BSE when the same bare ticker
// exists on both exchanges (almost universally the liquid one). Our
// scored universe is NSE-primary, so this is the right tie-break.
const SYMBOL_INDEX = new Map();
for (const s of DEDUPED) {
  if (!s.symbol) continue;
  const full = String(s.symbol).toUpperCase();
  const bare = full.replace(/\.(NS|BO)$/, "");
  // Prefer NSE on collision — only fill BSE slot if nothing claimed it yet
  if (full.endsWith(".NS")) {
    SYMBOL_INDEX.set(bare, s);
    SYMBOL_INDEX.set(full, s);
  } else {
    if (!SYMBOL_INDEX.has(bare)) SYMBOL_INDEX.set(bare, s);
    SYMBOL_INDEX.set(full, s);
  }
}

/**
 * Resolve a user-supplied ticker string to a scored-universe stock.
 *
 * Handles the three shapes brokers and users actually submit:
 *   • "TCS"        → bare NSE ticker
 *   • "TCS.NS"     → full NSE symbol
 *   • "TCS.BO"     → BSE fallback
 *
 * Resolution order:
 *   1. Curated ALL_STOCKS (has sector/indices metadata for scanners)
 *   2. NSE supplement (wider net — any NSE-listed name for holdings)
 *
 * Canonicalisation: uppercase, strip whitespace. Returns null on miss
 * rather than throwing, so the parser's fallback chain stays simple.
 */
function findBySymbol(raw) {
  if (!raw) return null;
  const key = String(raw).toUpperCase().replace(/\s+/g, "").trim();
  if (!key) return null;
  const primary = SYMBOL_INDEX.get(key);
  if (primary) return primary;
  // Supplement keyed by both bare ("TCS") and full ("TCS.NS") — strip any
  // exchange suffix so we match both shapes against the bare-symbol key.
  const bare = key.replace(/\.(NS|BO)$/, "");
  return SUPPLEMENT_BY_SYMBOL.get(bare) || SUPPLEMENT_BY_SYMBOL.get(key) || null;
}

function normalizeName(name) {
  if (!name) return "";
  return String(name)
    .toUpperCase()
    .replace(/[^A-Z0-9 ]/g, " ")
    // Drop common suffixes that vary across exports
    .replace(/\b(LTD|LIMITED|CORP|CORPORATION|INDUSTRIES|INDIA|CO|COMPANY|AUTO|INC)\b/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

function findByIsin(isin) {
  if (!isin) return null;
  const key = String(isin).trim().toUpperCase();
  return ISIN_INDEX.get(key) || SUPPLEMENT_BY_ISIN.get(key) || null;
}

function findByName(name) {
  if (!name) return null;
  const target = normalizeName(name);
  if (!target) return null;

  // Strategy: choose the candidate with highest token overlap that also
  // has at least 60% of the target's tokens present.
  const targetTokens = new Set(target.split(" ").filter((t) => t.length >= 3));
  if (targetTokens.size === 0) return null;

  let best = null;
  let bestScore = 0;
  for (const s of DEDUPED) {
    const cand = normalizeName(s.name);
    const candTokens = new Set(cand.split(" ").filter((t) => t.length >= 3));
    let match = 0;
    for (const t of targetTokens) if (candTokens.has(t)) match++;
    const score = match / targetTokens.size;
    if (score > bestScore && score >= 0.6) {
      bestScore = score;
      best = s;
    }
  }
  return best;
}

// Validate list — returns issues found. Called at server startup.
function validateStockList() {
  const issues = { duplicates: [], invalid: [] };
  const seen = new Set();
  const validPattern = /^[A-Z0-9&-]+\.(NS|BO)$/;

  for (const s of ALL_STOCKS) {
    if (seen.has(s.symbol)) issues.duplicates.push(s.symbol);
    seen.add(s.symbol);
    if (!validPattern.test(s.symbol)) {
      issues.invalid.push(s.symbol);
    }
  }
  return issues;
}

// Back-compat named exports for anything still importing old names
const NIFTY_50 = DEDUPED.filter((s) => s.indices.includes("NIFTY50"));
const NIFTY_NEXT_50 = DEDUPED.filter((s) => s.indices.includes("NIFTY_NEXT_50"));
const POPULAR_MIDCAPS = DEDUPED.filter((s) => s.indices.includes("MIDCAP"));

export {
  NIFTY_50,
  NIFTY_NEXT_50,
  POPULAR_MIDCAPS,
  DEDUPED as ALL_STOCKS,
  NIFTY500_SYMBOLS,
  getStocksByIndex,
  getAllStocks,
  getNifty100,
  getNifty500,
  passesLiquidityFilter,
  LIQUIDITY_MIN_TURNOVER_CR,
  validateStockList,
  findByIsin,
  findBySymbol,
  findByName,
  normalizeName,
};
