#!/usr/bin/env bash
# Shared generated-data shipper for SWS refresh jobs.
#
# Source this file from a refresh script, then call:
#   SWS_SHIP_MARKET=us \
#   SWS_SHIP_MIN_SCORED=5000 \
#   SWS_SHIP_PICKS_PATH=data/sws-us/picks-latest.json \
#   SWS_SHIP_LAST_REFRESH_PATH=data/sws-us/last-refresh.json \
#   sws_auto_ship_market data/sws-us/picks-latest.json ...
#
# The helper deliberately stages from a temporary worktree based on origin/main
# so a noisy operator checkout cannot leak unrelated local/generated files into
# the data PR.

sws_auto_ship_market() {
  local market="${SWS_SHIP_MARKET:-}"
  if [ -z "${market}" ]; then
    echo "[auto-ship] SWS_SHIP_MARKET is required; skipping"
    return 0
  fi

  local market_upper
  market_upper="$(printf '%s' "${market}" | tr '[:lower:]-' '[:upper:]_')"
  local auto_pr_var="SWS_${market_upper}_AUTO_PR"
  local auto_merge_var="SWS_${market_upper}_AUTO_MERGE"
  local auto_pr="${!auto_pr_var:-${SWS_AUTO_PR:-1}}"
  local auto_merge="${!auto_merge_var:-${SWS_AUTO_MERGE:-1}}"

  if [ "${auto_pr}" = "0" ]; then
    echo "[auto-ship] ${market}: SWS_AUTO_PR/${auto_pr_var}=0 — skipping"
    return 0
  fi
  if [ -n "${SWS_SCRAPE_LIMIT:-}" ]; then
    echo "[auto-ship] ${market}: SWS_SCRAPE_LIMIT=${SWS_SCRAPE_LIMIT} seed/capped run — skipping"
    return 0
  fi
  if [ "${SWS_SHIP_SCRAPE_SKIPPED:-false}" = "true" ]; then
    echo "[auto-ship] ${market}: scrape was skipped because shards were already live — skipping"
    return 0
  fi
  if [ "${SWS_SHIP_FAILED_SHARDS:-0}" != "0" ]; then
    echo "[auto-ship] ${market}: ${SWS_SHIP_FAILED_SHARDS} shard(s) failed — skipping"
    return 0
  fi
  if ! command -v gh >/dev/null 2>&1; then
    echo "[auto-ship] ${market}: gh CLI unavailable — skipping"
    return 0
  fi

  local allow_without_picks="${SWS_SHIP_ALLOW_WITHOUT_PICKS:-0}"
  if [ "${allow_without_picks}" != "1" ]; then
    SWS_SHIP_MARKET="${market}" \
    SWS_SHIP_MIN_SCORED="${SWS_SHIP_MIN_SCORED:-1}" \
    SWS_SHIP_PICKS_PATH="${SWS_SHIP_PICKS_PATH:-}" \
    SWS_SHIP_LAST_REFRESH_PATH="${SWS_SHIP_LAST_REFRESH_PATH:-}" \
      node --input-type=module - <<'EOF'
import { existsSync, readFileSync } from "node:fs";

const market = process.env.SWS_SHIP_MARKET;
const minScored = Number(process.env.SWS_SHIP_MIN_SCORED || 1);
const picksPath = process.env.SWS_SHIP_PICKS_PATH;
const lastRefreshPath = process.env.SWS_SHIP_LAST_REFRESH_PATH;

function fail(message) {
  console.error(`[auto-ship] ${market}: ${message}`);
  process.exit(1);
}

if (!picksPath || !lastRefreshPath) fail("picks and last-refresh paths are required");
if (!existsSync(picksPath)) fail(`${picksPath} is missing`);
if (!existsSync(lastRefreshPath)) fail(`${lastRefreshPath} is missing`);

let picks;
let lastRefresh;
try {
  picks = JSON.parse(readFileSync(picksPath, "utf-8"));
  lastRefresh = JSON.parse(readFileSync(lastRefreshPath, "utf-8"));
} catch (error) {
  fail(`could not parse picks/last-refresh JSON: ${error.message}`);
}

const scored = Number(picks.scored_count ?? lastRefresh.scored_count ?? 0);
if (!Number.isFinite(scored) || scored < minScored) {
  fail(`scored_count ${scored} is below minimum ${minScored}`);
}
if (!lastRefresh.finished_at) fail(`${lastRefreshPath} has no finished_at`);
EOF
    local validation_rc=$?
    if [ "${validation_rc}" -ne 0 ]; then
      echo "[auto-ship] ${market}: validation failed — skipping"
      return 0
    fi
  fi

  if [ "$#" -eq 0 ]; then
    echo "[auto-ship] ${market}: no artifact paths supplied — skipping"
    return 0
  fi

  local repo_root
  repo_root="$(git rev-parse --show-toplevel 2>/dev/null)" || {
    echo "[auto-ship] ${market}: not inside a git repository — skipping"
    return 0
  }

  local stamp run_label branch subject body pr_title pr_body tmpdir pr_output pr_url
  stamp="$(date -u +%Y%m%dT%H%M%SZ)"
  run_label="${SWS_SHIP_RUN_LABEL:-$(date -u '+%Y-%m-%d %H:%M UTC')}"
  branch="${SWS_SHIP_BRANCH:-chore/data-refresh-${market}-${stamp}}"
  subject="${SWS_SHIP_COMMIT_SUBJECT:-chore(data): refresh ${market} data ${run_label}}"
  pr_title="${SWS_SHIP_PR_TITLE:-${subject}}"
  body="${SWS_SHIP_COMMIT_BODY:-Automated generated-data refresh for ${market}.}"
  pr_body="${SWS_SHIP_PR_BODY:-${body}

Auto-generated by a SWS refresh script. The ship worktree is based on origin/main and contains only the explicit generated artifact allow-list for this market.}"

  echo "[auto-ship] ${market}: fetching origin/main..."
  if ! git -C "${repo_root}" fetch origin main 2>&1 | sed 's/^/[git] /'; then
    echo "[auto-ship] ${market}: git fetch failed — skipping"
    return 0
  fi

  tmpdir="$(mktemp -d "${TMPDIR:-/tmp}/sws-auto-ship-${market}.XXXXXX")"
  cleanup_auto_ship_worktree() {
    git -C "${repo_root}" worktree remove --force "${tmpdir}" >/dev/null 2>&1 || true
    rm -rf "${tmpdir}" >/dev/null 2>&1 || true
  }

  git -C "${repo_root}" branch -D "${branch}" >/dev/null 2>&1 || true
  if ! git -C "${repo_root}" worktree add -B "${branch}" "${tmpdir}" origin/main 2>&1 | sed 's/^/[git] /'; then
    echo "[auto-ship] ${market}: worktree add failed — skipping"
    rm -rf "${tmpdir}" >/dev/null 2>&1 || true
    return 0
  fi

  local path src dst copied=0
  local copied_paths=()
  for path in "$@"; do
    src="${repo_root}/${path%/}"
    dst="${tmpdir}/${path%/}"
    if [ ! -e "${src}" ]; then
      echo "[auto-ship] ${market}: missing artifact ${path} — not staged"
      continue
    fi
    mkdir -p "$(dirname "${dst}")"
    if [ -d "${src}" ]; then
      mkdir -p "${dst}"
      rsync -a --delete "${src}/" "${dst}/"
    else
      cp "${src}" "${dst}"
    fi
    copied_paths+=("${path}")
    copied=$((copied + 1))
  done

  if [ "${copied}" -eq 0 ]; then
    echo "[auto-ship] ${market}: no supplied artifacts exist — skipping"
    cleanup_auto_ship_worktree
    return 0
  fi

  git -C "${tmpdir}" add -- "${copied_paths[@]}"
  if git -C "${tmpdir}" diff --cached --quiet --exit-code; then
    echo "[auto-ship] ${market}: no staged changes versus origin/main — skipping"
    cleanup_auto_ship_worktree
    return 0
  fi

  if ! git -C "${tmpdir}" commit -m "${subject}

${body}" 2>&1 | sed 's/^/[git] /'; then
    echo "[auto-ship] ${market}: commit failed — skipping push"
    cleanup_auto_ship_worktree
    return 0
  fi

  if ! git -C "${tmpdir}" push -u origin "${branch}" 2>&1 | sed 's/^/[git] /'; then
    echo "[auto-ship] ${market}: push failed — leaving local branch ${branch}"
    cleanup_auto_ship_worktree
    return 0
  fi

  pr_output="$(cd "${tmpdir}" && gh pr create --base main --head "${branch}" --title "${pr_title}" --body "${pr_body}" 2>&1)"
  pr_url="$(printf '%s\n' "${pr_output}" | grep -oE 'https://github\.com/[^[:space:]]+/pull/[0-9]+' | tail -1)"
  if [ -z "${pr_url}" ]; then
    echo "[auto-ship] ${market}: gh pr create failed: ${pr_output}"
    cleanup_auto_ship_worktree
    return 0
  fi

  echo "[auto-ship] ${market}: PR created ${pr_url}"
  if [ "${auto_merge}" = "0" ]; then
    echo "[auto-ship] ${market}: SWS_AUTO_MERGE/${auto_merge_var}=0 — PR left open"
    cleanup_auto_ship_worktree
    return 0
  fi

  if ! gh pr merge "${pr_url}" --squash --auto 2>&1 | sed 's/^/[gh] /'; then
    echo "[auto-ship] ${market}: --auto merge failed, trying immediate squash merge..."
    gh pr merge "${pr_url}" --squash 2>&1 | sed 's/^/[gh] /' || \
      echo "[auto-ship] ${market}: merge failed — manual review required"
  fi

  cleanup_auto_ship_worktree
  return 0
}
